import equational_theories.Definability.Basic
import equational_theories.Definability.Simple
import equational_theories.Definability.Law43
import equational_theories.Definability.Law46
import equational_theories.Definability.Tarski543
