import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 4000-4694 (end) -/

equation 4000 := x ◇ y = (z ◇ (x ◇ w)) ◇ x
equation 4001 := x ◇ y = (z ◇ (x ◇ w)) ◇ y
equation 4002 := x ◇ y = (z ◇ (x ◇ w)) ◇ z
equation 4003 := x ◇ y = (z ◇ (x ◇ w)) ◇ w
equation 4004 := x ◇ y = (z ◇ (x ◇ w)) ◇ u
equation 4005 := x ◇ y = (z ◇ (y ◇ x)) ◇ x
equation 4006 := x ◇ y = (z ◇ (y ◇ x)) ◇ y
equation 4007 := x ◇ y = (z ◇ (y ◇ x)) ◇ z
equation 4008 := x ◇ y = (z ◇ (y ◇ x)) ◇ w
equation 4009 := x ◇ y = (z ◇ (y ◇ y)) ◇ x
equation 4010 := x ◇ y = (z ◇ (y ◇ y)) ◇ y
equation 4011 := x ◇ y = (z ◇ (y ◇ y)) ◇ z
equation 4012 := x ◇ y = (z ◇ (y ◇ y)) ◇ w
equation 4013 := x ◇ y = (z ◇ (y ◇ z)) ◇ x
equation 4014 := x ◇ y = (z ◇ (y ◇ z)) ◇ y
equation 4015 := x ◇ y = (z ◇ (y ◇ z)) ◇ z
equation 4016 := x ◇ y = (z ◇ (y ◇ z)) ◇ w
equation 4017 := x ◇ y = (z ◇ (y ◇ w)) ◇ x
equation 4018 := x ◇ y = (z ◇ (y ◇ w)) ◇ y
equation 4019 := x ◇ y = (z ◇ (y ◇ w)) ◇ z
equation 4020 := x ◇ y = (z ◇ (y ◇ w)) ◇ w
equation 4021 := x ◇ y = (z ◇ (y ◇ w)) ◇ u
equation 4022 := x ◇ y = (z ◇ (z ◇ x)) ◇ x
equation 4023 := x ◇ y = (z ◇ (z ◇ x)) ◇ y
equation 4024 := x ◇ y = (z ◇ (z ◇ x)) ◇ z
equation 4025 := x ◇ y = (z ◇ (z ◇ x)) ◇ w
equation 4026 := x ◇ y = (z ◇ (z ◇ y)) ◇ x
equation 4027 := x ◇ y = (z ◇ (z ◇ y)) ◇ y
equation 4028 := x ◇ y = (z ◇ (z ◇ y)) ◇ z
equation 4029 := x ◇ y = (z ◇ (z ◇ y)) ◇ w
equation 4030 := x ◇ y = (z ◇ (z ◇ z)) ◇ x
equation 4031 := x ◇ y = (z ◇ (z ◇ z)) ◇ y
equation 4032 := x ◇ y = (z ◇ (z ◇ z)) ◇ z
equation 4033 := x ◇ y = (z ◇ (z ◇ z)) ◇ w
equation 4034 := x ◇ y = (z ◇ (z ◇ w)) ◇ x
equation 4035 := x ◇ y = (z ◇ (z ◇ w)) ◇ y
equation 4036 := x ◇ y = (z ◇ (z ◇ w)) ◇ z
equation 4037 := x ◇ y = (z ◇ (z ◇ w)) ◇ w
equation 4038 := x ◇ y = (z ◇ (z ◇ w)) ◇ u
equation 4039 := x ◇ y = (z ◇ (w ◇ x)) ◇ x
equation 4040 := x ◇ y = (z ◇ (w ◇ x)) ◇ y
equation 4041 := x ◇ y = (z ◇ (w ◇ x)) ◇ z
equation 4042 := x ◇ y = (z ◇ (w ◇ x)) ◇ w
equation 4043 := x ◇ y = (z ◇ (w ◇ x)) ◇ u
equation 4044 := x ◇ y = (z ◇ (w ◇ y)) ◇ x
equation 4045 := x ◇ y = (z ◇ (w ◇ y)) ◇ y
equation 4046 := x ◇ y = (z ◇ (w ◇ y)) ◇ z
equation 4047 := x ◇ y = (z ◇ (w ◇ y)) ◇ w
equation 4048 := x ◇ y = (z ◇ (w ◇ y)) ◇ u
equation 4049 := x ◇ y = (z ◇ (w ◇ z)) ◇ x
equation 4050 := x ◇ y = (z ◇ (w ◇ z)) ◇ y
equation 4051 := x ◇ y = (z ◇ (w ◇ z)) ◇ z
equation 4052 := x ◇ y = (z ◇ (w ◇ z)) ◇ w
equation 4053 := x ◇ y = (z ◇ (w ◇ z)) ◇ u
equation 4054 := x ◇ y = (z ◇ (w ◇ w)) ◇ x
equation 4055 := x ◇ y = (z ◇ (w ◇ w)) ◇ y
equation 4056 := x ◇ y = (z ◇ (w ◇ w)) ◇ z
equation 4057 := x ◇ y = (z ◇ (w ◇ w)) ◇ w
equation 4058 := x ◇ y = (z ◇ (w ◇ w)) ◇ u
equation 4059 := x ◇ y = (z ◇ (w ◇ u)) ◇ x
equation 4060 := x ◇ y = (z ◇ (w ◇ u)) ◇ y
equation 4061 := x ◇ y = (z ◇ (w ◇ u)) ◇ z
equation 4062 := x ◇ y = (z ◇ (w ◇ u)) ◇ w
equation 4063 := x ◇ y = (z ◇ (w ◇ u)) ◇ u
equation 4064 := x ◇ y = (z ◇ (w ◇ u)) ◇ v
-- equation 4065 := x ◇ x = ((x ◇ x) ◇ x) ◇ x
equation 4066 := x ◇ x = ((x ◇ x) ◇ x) ◇ y
equation 4067 := x ◇ x = ((x ◇ x) ◇ y) ◇ x
equation 4068 := x ◇ x = ((x ◇ x) ◇ y) ◇ y
equation 4069 := x ◇ x = ((x ◇ x) ◇ y) ◇ z
equation 4070 := x ◇ x = ((x ◇ y) ◇ x) ◇ x
equation 4071 := x ◇ x = ((x ◇ y) ◇ x) ◇ y
equation 4072 := x ◇ x = ((x ◇ y) ◇ x) ◇ z
equation 4073 := x ◇ x = ((x ◇ y) ◇ y) ◇ x
equation 4074 := x ◇ x = ((x ◇ y) ◇ y) ◇ y
equation 4075 := x ◇ x = ((x ◇ y) ◇ y) ◇ z
equation 4076 := x ◇ x = ((x ◇ y) ◇ z) ◇ x
equation 4077 := x ◇ x = ((x ◇ y) ◇ z) ◇ y
equation 4078 := x ◇ x = ((x ◇ y) ◇ z) ◇ z
equation 4079 := x ◇ x = ((x ◇ y) ◇ z) ◇ w
equation 4080 := x ◇ x = ((y ◇ x) ◇ x) ◇ x
equation 4081 := x ◇ x = ((y ◇ x) ◇ x) ◇ y
equation 4082 := x ◇ x = ((y ◇ x) ◇ x) ◇ z
equation 4083 := x ◇ x = ((y ◇ x) ◇ y) ◇ x
equation 4084 := x ◇ x = ((y ◇ x) ◇ y) ◇ y
equation 4085 := x ◇ x = ((y ◇ x) ◇ y) ◇ z
equation 4086 := x ◇ x = ((y ◇ x) ◇ z) ◇ x
equation 4087 := x ◇ x = ((y ◇ x) ◇ z) ◇ y
equation 4088 := x ◇ x = ((y ◇ x) ◇ z) ◇ z
equation 4089 := x ◇ x = ((y ◇ x) ◇ z) ◇ w
equation 4090 := x ◇ x = ((y ◇ y) ◇ x) ◇ x
equation 4091 := x ◇ x = ((y ◇ y) ◇ x) ◇ y
equation 4092 := x ◇ x = ((y ◇ y) ◇ x) ◇ z
equation 4093 := x ◇ x = ((y ◇ y) ◇ y) ◇ x
equation 4094 := x ◇ x = ((y ◇ y) ◇ y) ◇ y
equation 4095 := x ◇ x = ((y ◇ y) ◇ y) ◇ z
equation 4096 := x ◇ x = ((y ◇ y) ◇ z) ◇ x
equation 4097 := x ◇ x = ((y ◇ y) ◇ z) ◇ y
equation 4098 := x ◇ x = ((y ◇ y) ◇ z) ◇ z
equation 4099 := x ◇ x = ((y ◇ y) ◇ z) ◇ w
equation 4100 := x ◇ x = ((y ◇ z) ◇ x) ◇ x
equation 4101 := x ◇ x = ((y ◇ z) ◇ x) ◇ y
equation 4102 := x ◇ x = ((y ◇ z) ◇ x) ◇ z
equation 4103 := x ◇ x = ((y ◇ z) ◇ x) ◇ w
equation 4104 := x ◇ x = ((y ◇ z) ◇ y) ◇ x
equation 4105 := x ◇ x = ((y ◇ z) ◇ y) ◇ y
equation 4106 := x ◇ x = ((y ◇ z) ◇ y) ◇ z
equation 4107 := x ◇ x = ((y ◇ z) ◇ y) ◇ w
equation 4108 := x ◇ x = ((y ◇ z) ◇ z) ◇ x
equation 4109 := x ◇ x = ((y ◇ z) ◇ z) ◇ y
equation 4110 := x ◇ x = ((y ◇ z) ◇ z) ◇ z
equation 4111 := x ◇ x = ((y ◇ z) ◇ z) ◇ w
equation 4112 := x ◇ x = ((y ◇ z) ◇ w) ◇ x
equation 4113 := x ◇ x = ((y ◇ z) ◇ w) ◇ y
equation 4114 := x ◇ x = ((y ◇ z) ◇ w) ◇ z
equation 4115 := x ◇ x = ((y ◇ z) ◇ w) ◇ w
equation 4116 := x ◇ x = ((y ◇ z) ◇ w) ◇ u
equation 4117 := x ◇ y = ((x ◇ x) ◇ x) ◇ x
equation 4118 := x ◇ y = ((x ◇ x) ◇ x) ◇ y
equation 4119 := x ◇ y = ((x ◇ x) ◇ x) ◇ z
equation 4120 := x ◇ y = ((x ◇ x) ◇ y) ◇ x
equation 4121 := x ◇ y = ((x ◇ x) ◇ y) ◇ y
equation 4122 := x ◇ y = ((x ◇ x) ◇ y) ◇ z
equation 4123 := x ◇ y = ((x ◇ x) ◇ z) ◇ x
equation 4124 := x ◇ y = ((x ◇ x) ◇ z) ◇ y
equation 4125 := x ◇ y = ((x ◇ x) ◇ z) ◇ z
equation 4126 := x ◇ y = ((x ◇ x) ◇ z) ◇ w
equation 4127 := x ◇ y = ((x ◇ y) ◇ x) ◇ x
equation 4128 := x ◇ y = ((x ◇ y) ◇ x) ◇ y
equation 4129 := x ◇ y = ((x ◇ y) ◇ x) ◇ z
equation 4130 := x ◇ y = ((x ◇ y) ◇ y) ◇ x
equation 4131 := x ◇ y = ((x ◇ y) ◇ y) ◇ y
equation 4132 := x ◇ y = ((x ◇ y) ◇ y) ◇ z
equation 4133 := x ◇ y = ((x ◇ y) ◇ z) ◇ x
equation 4134 := x ◇ y = ((x ◇ y) ◇ z) ◇ y
equation 4135 := x ◇ y = ((x ◇ y) ◇ z) ◇ z
equation 4136 := x ◇ y = ((x ◇ y) ◇ z) ◇ w
equation 4137 := x ◇ y = ((x ◇ z) ◇ x) ◇ x
equation 4138 := x ◇ y = ((x ◇ z) ◇ x) ◇ y
equation 4139 := x ◇ y = ((x ◇ z) ◇ x) ◇ z
equation 4140 := x ◇ y = ((x ◇ z) ◇ x) ◇ w
equation 4141 := x ◇ y = ((x ◇ z) ◇ y) ◇ x
equation 4142 := x ◇ y = ((x ◇ z) ◇ y) ◇ y
equation 4143 := x ◇ y = ((x ◇ z) ◇ y) ◇ z
equation 4144 := x ◇ y = ((x ◇ z) ◇ y) ◇ w
equation 4145 := x ◇ y = ((x ◇ z) ◇ z) ◇ x
equation 4146 := x ◇ y = ((x ◇ z) ◇ z) ◇ y
equation 4147 := x ◇ y = ((x ◇ z) ◇ z) ◇ z
equation 4148 := x ◇ y = ((x ◇ z) ◇ z) ◇ w
equation 4149 := x ◇ y = ((x ◇ z) ◇ w) ◇ x
equation 4150 := x ◇ y = ((x ◇ z) ◇ w) ◇ y
equation 4151 := x ◇ y = ((x ◇ z) ◇ w) ◇ z
equation 4152 := x ◇ y = ((x ◇ z) ◇ w) ◇ w
equation 4153 := x ◇ y = ((x ◇ z) ◇ w) ◇ u
equation 4154 := x ◇ y = ((y ◇ x) ◇ x) ◇ x
equation 4155 := x ◇ y = ((y ◇ x) ◇ x) ◇ y
equation 4156 := x ◇ y = ((y ◇ x) ◇ x) ◇ z
equation 4157 := x ◇ y = ((y ◇ x) ◇ y) ◇ x
equation 4158 := x ◇ y = ((y ◇ x) ◇ y) ◇ y
equation 4159 := x ◇ y = ((y ◇ x) ◇ y) ◇ z
equation 4160 := x ◇ y = ((y ◇ x) ◇ z) ◇ x
equation 4161 := x ◇ y = ((y ◇ x) ◇ z) ◇ y
equation 4162 := x ◇ y = ((y ◇ x) ◇ z) ◇ z
equation 4163 := x ◇ y = ((y ◇ x) ◇ z) ◇ w
equation 4164 := x ◇ y = ((y ◇ y) ◇ x) ◇ x
equation 4165 := x ◇ y = ((y ◇ y) ◇ x) ◇ y
equation 4166 := x ◇ y = ((y ◇ y) ◇ x) ◇ z
equation 4167 := x ◇ y = ((y ◇ y) ◇ y) ◇ x
equation 4168 := x ◇ y = ((y ◇ y) ◇ y) ◇ y
equation 4169 := x ◇ y = ((y ◇ y) ◇ y) ◇ z
equation 4170 := x ◇ y = ((y ◇ y) ◇ z) ◇ x
equation 4171 := x ◇ y = ((y ◇ y) ◇ z) ◇ y
equation 4172 := x ◇ y = ((y ◇ y) ◇ z) ◇ z
equation 4173 := x ◇ y = ((y ◇ y) ◇ z) ◇ w
equation 4174 := x ◇ y = ((y ◇ z) ◇ x) ◇ x
equation 4175 := x ◇ y = ((y ◇ z) ◇ x) ◇ y
equation 4176 := x ◇ y = ((y ◇ z) ◇ x) ◇ z
equation 4177 := x ◇ y = ((y ◇ z) ◇ x) ◇ w
equation 4178 := x ◇ y = ((y ◇ z) ◇ y) ◇ x
equation 4179 := x ◇ y = ((y ◇ z) ◇ y) ◇ y
equation 4180 := x ◇ y = ((y ◇ z) ◇ y) ◇ z
equation 4181 := x ◇ y = ((y ◇ z) ◇ y) ◇ w
equation 4182 := x ◇ y = ((y ◇ z) ◇ z) ◇ x
equation 4183 := x ◇ y = ((y ◇ z) ◇ z) ◇ y
equation 4184 := x ◇ y = ((y ◇ z) ◇ z) ◇ z
equation 4185 := x ◇ y = ((y ◇ z) ◇ z) ◇ w
equation 4186 := x ◇ y = ((y ◇ z) ◇ w) ◇ x
equation 4187 := x ◇ y = ((y ◇ z) ◇ w) ◇ y
equation 4188 := x ◇ y = ((y ◇ z) ◇ w) ◇ z
equation 4189 := x ◇ y = ((y ◇ z) ◇ w) ◇ w
equation 4190 := x ◇ y = ((y ◇ z) ◇ w) ◇ u
equation 4191 := x ◇ y = ((z ◇ x) ◇ x) ◇ x
equation 4192 := x ◇ y = ((z ◇ x) ◇ x) ◇ y
equation 4193 := x ◇ y = ((z ◇ x) ◇ x) ◇ z
equation 4194 := x ◇ y = ((z ◇ x) ◇ x) ◇ w
equation 4195 := x ◇ y = ((z ◇ x) ◇ y) ◇ x
equation 4196 := x ◇ y = ((z ◇ x) ◇ y) ◇ y
equation 4197 := x ◇ y = ((z ◇ x) ◇ y) ◇ z
equation 4198 := x ◇ y = ((z ◇ x) ◇ y) ◇ w
equation 4199 := x ◇ y = ((z ◇ x) ◇ z) ◇ x
equation 4200 := x ◇ y = ((z ◇ x) ◇ z) ◇ y
equation 4201 := x ◇ y = ((z ◇ x) ◇ z) ◇ z
equation 4202 := x ◇ y = ((z ◇ x) ◇ z) ◇ w
equation 4203 := x ◇ y = ((z ◇ x) ◇ w) ◇ x
equation 4204 := x ◇ y = ((z ◇ x) ◇ w) ◇ y
equation 4205 := x ◇ y = ((z ◇ x) ◇ w) ◇ z
equation 4206 := x ◇ y = ((z ◇ x) ◇ w) ◇ w
equation 4207 := x ◇ y = ((z ◇ x) ◇ w) ◇ u
equation 4208 := x ◇ y = ((z ◇ y) ◇ x) ◇ x
equation 4209 := x ◇ y = ((z ◇ y) ◇ x) ◇ y
equation 4210 := x ◇ y = ((z ◇ y) ◇ x) ◇ z
equation 4211 := x ◇ y = ((z ◇ y) ◇ x) ◇ w
equation 4212 := x ◇ y = ((z ◇ y) ◇ y) ◇ x
equation 4213 := x ◇ y = ((z ◇ y) ◇ y) ◇ y
equation 4214 := x ◇ y = ((z ◇ y) ◇ y) ◇ z
equation 4215 := x ◇ y = ((z ◇ y) ◇ y) ◇ w
equation 4216 := x ◇ y = ((z ◇ y) ◇ z) ◇ x
equation 4217 := x ◇ y = ((z ◇ y) ◇ z) ◇ y
equation 4218 := x ◇ y = ((z ◇ y) ◇ z) ◇ z
equation 4219 := x ◇ y = ((z ◇ y) ◇ z) ◇ w
equation 4220 := x ◇ y = ((z ◇ y) ◇ w) ◇ x
equation 4221 := x ◇ y = ((z ◇ y) ◇ w) ◇ y
equation 4222 := x ◇ y = ((z ◇ y) ◇ w) ◇ z
equation 4223 := x ◇ y = ((z ◇ y) ◇ w) ◇ w
equation 4224 := x ◇ y = ((z ◇ y) ◇ w) ◇ u
equation 4225 := x ◇ y = ((z ◇ z) ◇ x) ◇ x
equation 4226 := x ◇ y = ((z ◇ z) ◇ x) ◇ y
equation 4227 := x ◇ y = ((z ◇ z) ◇ x) ◇ z
equation 4228 := x ◇ y = ((z ◇ z) ◇ x) ◇ w
equation 4229 := x ◇ y = ((z ◇ z) ◇ y) ◇ x
equation 4230 := x ◇ y = ((z ◇ z) ◇ y) ◇ y
equation 4231 := x ◇ y = ((z ◇ z) ◇ y) ◇ z
equation 4232 := x ◇ y = ((z ◇ z) ◇ y) ◇ w
equation 4233 := x ◇ y = ((z ◇ z) ◇ z) ◇ x
equation 4234 := x ◇ y = ((z ◇ z) ◇ z) ◇ y
equation 4235 := x ◇ y = ((z ◇ z) ◇ z) ◇ z
equation 4236 := x ◇ y = ((z ◇ z) ◇ z) ◇ w
equation 4237 := x ◇ y = ((z ◇ z) ◇ w) ◇ x
equation 4238 := x ◇ y = ((z ◇ z) ◇ w) ◇ y
equation 4239 := x ◇ y = ((z ◇ z) ◇ w) ◇ z
equation 4240 := x ◇ y = ((z ◇ z) ◇ w) ◇ w
equation 4241 := x ◇ y = ((z ◇ z) ◇ w) ◇ u
equation 4242 := x ◇ y = ((z ◇ w) ◇ x) ◇ x
equation 4243 := x ◇ y = ((z ◇ w) ◇ x) ◇ y
equation 4244 := x ◇ y = ((z ◇ w) ◇ x) ◇ z
equation 4245 := x ◇ y = ((z ◇ w) ◇ x) ◇ w
equation 4246 := x ◇ y = ((z ◇ w) ◇ x) ◇ u
equation 4247 := x ◇ y = ((z ◇ w) ◇ y) ◇ x
equation 4248 := x ◇ y = ((z ◇ w) ◇ y) ◇ y
equation 4249 := x ◇ y = ((z ◇ w) ◇ y) ◇ z
equation 4250 := x ◇ y = ((z ◇ w) ◇ y) ◇ w
equation 4251 := x ◇ y = ((z ◇ w) ◇ y) ◇ u
equation 4252 := x ◇ y = ((z ◇ w) ◇ z) ◇ x
equation 4253 := x ◇ y = ((z ◇ w) ◇ z) ◇ y
equation 4254 := x ◇ y = ((z ◇ w) ◇ z) ◇ z
equation 4255 := x ◇ y = ((z ◇ w) ◇ z) ◇ w
equation 4256 := x ◇ y = ((z ◇ w) ◇ z) ◇ u
equation 4257 := x ◇ y = ((z ◇ w) ◇ w) ◇ x
equation 4258 := x ◇ y = ((z ◇ w) ◇ w) ◇ y
equation 4259 := x ◇ y = ((z ◇ w) ◇ w) ◇ z
equation 4260 := x ◇ y = ((z ◇ w) ◇ w) ◇ w
equation 4261 := x ◇ y = ((z ◇ w) ◇ w) ◇ u
equation 4262 := x ◇ y = ((z ◇ w) ◇ u) ◇ x
equation 4263 := x ◇ y = ((z ◇ w) ◇ u) ◇ y
equation 4264 := x ◇ y = ((z ◇ w) ◇ u) ◇ z
equation 4265 := x ◇ y = ((z ◇ w) ◇ u) ◇ w
equation 4266 := x ◇ y = ((z ◇ w) ◇ u) ◇ u
equation 4267 := x ◇ y = ((z ◇ w) ◇ u) ◇ v
equation 4268 := x ◇ (x ◇ x) = x ◇ (x ◇ y)
equation 4269 := x ◇ (x ◇ x) = x ◇ (y ◇ x)
equation 4270 := x ◇ (x ◇ x) = x ◇ (y ◇ y)
equation 4271 := x ◇ (x ◇ x) = x ◇ (y ◇ z)
equation 4272 := x ◇ (x ◇ x) = y ◇ (x ◇ x)
equation 4273 := x ◇ (x ◇ x) = y ◇ (x ◇ y)
equation 4274 := x ◇ (x ◇ x) = y ◇ (x ◇ z)
equation 4275 := x ◇ (x ◇ x) = y ◇ (y ◇ x)
equation 4276 := x ◇ (x ◇ x) = y ◇ (y ◇ y)
equation 4277 := x ◇ (x ◇ x) = y ◇ (y ◇ z)
equation 4278 := x ◇ (x ◇ x) = y ◇ (z ◇ x)
equation 4279 := x ◇ (x ◇ x) = y ◇ (z ◇ y)
equation 4280 := x ◇ (x ◇ x) = y ◇ (z ◇ z)
equation 4281 := x ◇ (x ◇ x) = y ◇ (z ◇ w)
equation 4282 := x ◇ (x ◇ y) = x ◇ (x ◇ z)
equation 4283 := x ◇ (x ◇ y) = x ◇ (y ◇ x)
equation 4284 := x ◇ (x ◇ y) = x ◇ (y ◇ y)
equation 4285 := x ◇ (x ◇ y) = x ◇ (y ◇ z)
equation 4286 := x ◇ (x ◇ y) = x ◇ (z ◇ x)
equation 4287 := x ◇ (x ◇ y) = x ◇ (z ◇ y)
equation 4288 := x ◇ (x ◇ y) = x ◇ (z ◇ z)
equation 4289 := x ◇ (x ◇ y) = x ◇ (z ◇ w)
equation 4290 := x ◇ (x ◇ y) = y ◇ (x ◇ x)
equation 4291 := x ◇ (x ◇ y) = y ◇ (x ◇ y)
equation 4292 := x ◇ (x ◇ y) = y ◇ (x ◇ z)
equation 4293 := x ◇ (x ◇ y) = y ◇ (y ◇ x)
equation 4294 := x ◇ (x ◇ y) = y ◇ (y ◇ z)
equation 4295 := x ◇ (x ◇ y) = y ◇ (z ◇ x)
equation 4296 := x ◇ (x ◇ y) = y ◇ (z ◇ y)
equation 4297 := x ◇ (x ◇ y) = y ◇ (z ◇ z)
equation 4298 := x ◇ (x ◇ y) = y ◇ (z ◇ w)
equation 4299 := x ◇ (x ◇ y) = z ◇ (x ◇ x)
equation 4300 := x ◇ (x ◇ y) = z ◇ (x ◇ y)
equation 4301 := x ◇ (x ◇ y) = z ◇ (x ◇ z)
equation 4302 := x ◇ (x ◇ y) = z ◇ (x ◇ w)
equation 4303 := x ◇ (x ◇ y) = z ◇ (y ◇ x)
equation 4304 := x ◇ (x ◇ y) = z ◇ (y ◇ y)
equation 4305 := x ◇ (x ◇ y) = z ◇ (y ◇ z)
equation 4306 := x ◇ (x ◇ y) = z ◇ (y ◇ w)
equation 4307 := x ◇ (x ◇ y) = z ◇ (z ◇ y)
equation 4308 := x ◇ (x ◇ y) = z ◇ (z ◇ w)
equation 4309 := x ◇ (x ◇ y) = z ◇ (w ◇ x)
equation 4310 := x ◇ (x ◇ y) = z ◇ (w ◇ y)
equation 4311 := x ◇ (x ◇ y) = z ◇ (w ◇ z)
equation 4312 := x ◇ (x ◇ y) = z ◇ (w ◇ w)
equation 4313 := x ◇ (x ◇ y) = z ◇ (w ◇ u)
equation 4314 := x ◇ (y ◇ x) = x ◇ (y ◇ y)
-- equation 4315 := x ◇ (y ◇ x) = x ◇ (y ◇ z)
equation 4316 := x ◇ (y ◇ x) = x ◇ (z ◇ x)
equation 4317 := x ◇ (y ◇ x) = x ◇ (z ◇ y)
equation 4318 := x ◇ (y ◇ x) = x ◇ (z ◇ z)
equation 4319 := x ◇ (y ◇ x) = x ◇ (z ◇ w)
equation 4320 := x ◇ (y ◇ x) = y ◇ (x ◇ x)
equation 4321 := x ◇ (y ◇ x) = y ◇ (x ◇ y)
equation 4322 := x ◇ (y ◇ x) = y ◇ (x ◇ z)
equation 4323 := x ◇ (y ◇ x) = y ◇ (z ◇ x)
equation 4324 := x ◇ (y ◇ x) = y ◇ (z ◇ y)
equation 4325 := x ◇ (y ◇ x) = y ◇ (z ◇ z)
equation 4326 := x ◇ (y ◇ x) = y ◇ (z ◇ w)
equation 4327 := x ◇ (y ◇ x) = z ◇ (x ◇ x)
equation 4328 := x ◇ (y ◇ x) = z ◇ (x ◇ y)
equation 4329 := x ◇ (y ◇ x) = z ◇ (x ◇ w)
equation 4330 := x ◇ (y ◇ x) = z ◇ (y ◇ x)
equation 4331 := x ◇ (y ◇ x) = z ◇ (y ◇ y)
equation 4332 := x ◇ (y ◇ x) = z ◇ (y ◇ z)
equation 4333 := x ◇ (y ◇ x) = z ◇ (y ◇ w)
equation 4334 := x ◇ (y ◇ x) = z ◇ (w ◇ x)
equation 4335 := x ◇ (y ◇ x) = z ◇ (w ◇ y)
equation 4336 := x ◇ (y ◇ x) = z ◇ (w ◇ z)
equation 4337 := x ◇ (y ◇ x) = z ◇ (w ◇ w)
equation 4338 := x ◇ (y ◇ x) = z ◇ (w ◇ u)
equation 4339 := x ◇ (y ◇ y) = x ◇ (y ◇ z)
equation 4340 := x ◇ (y ◇ y) = x ◇ (z ◇ y)
equation 4341 := x ◇ (y ◇ y) = x ◇ (z ◇ z)
equation 4342 := x ◇ (y ◇ y) = x ◇ (z ◇ w)
equation 4343 := x ◇ (y ◇ y) = y ◇ (x ◇ x)
equation 4344 := x ◇ (y ◇ y) = y ◇ (x ◇ z)
equation 4345 := x ◇ (y ◇ y) = y ◇ (z ◇ x)
equation 4346 := x ◇ (y ◇ y) = y ◇ (z ◇ z)
equation 4347 := x ◇ (y ◇ y) = y ◇ (z ◇ w)
equation 4348 := x ◇ (y ◇ y) = z ◇ (x ◇ y)
equation 4349 := x ◇ (y ◇ y) = z ◇ (x ◇ w)
equation 4350 := x ◇ (y ◇ y) = z ◇ (y ◇ x)
equation 4351 := x ◇ (y ◇ y) = z ◇ (y ◇ y)
equation 4352 := x ◇ (y ◇ y) = z ◇ (y ◇ w)
equation 4353 := x ◇ (y ◇ y) = z ◇ (w ◇ x)
equation 4354 := x ◇ (y ◇ y) = z ◇ (w ◇ y)
equation 4355 := x ◇ (y ◇ y) = z ◇ (w ◇ w)
equation 4356 := x ◇ (y ◇ y) = z ◇ (w ◇ u)
equation 4357 := x ◇ (y ◇ z) = x ◇ (y ◇ w)
equation 4358 := x ◇ (y ◇ z) = x ◇ (z ◇ y)
equation 4359 := x ◇ (y ◇ z) = x ◇ (z ◇ w)
equation 4360 := x ◇ (y ◇ z) = x ◇ (w ◇ z)
equation 4361 := x ◇ (y ◇ z) = x ◇ (w ◇ u)
equation 4362 := x ◇ (y ◇ z) = y ◇ (x ◇ z)
equation 4363 := x ◇ (y ◇ z) = y ◇ (x ◇ w)
equation 4364 := x ◇ (y ◇ z) = y ◇ (z ◇ x)
equation 4365 := x ◇ (y ◇ z) = y ◇ (z ◇ w)
equation 4366 := x ◇ (y ◇ z) = y ◇ (w ◇ x)
equation 4367 := x ◇ (y ◇ z) = y ◇ (w ◇ z)
equation 4368 := x ◇ (y ◇ z) = y ◇ (w ◇ u)
equation 4369 := x ◇ (y ◇ z) = z ◇ (y ◇ x)
equation 4370 := x ◇ (y ◇ z) = z ◇ (y ◇ w)
equation 4371 := x ◇ (y ◇ z) = z ◇ (w ◇ x)
equation 4372 := x ◇ (y ◇ z) = z ◇ (w ◇ y)
equation 4373 := x ◇ (y ◇ z) = z ◇ (w ◇ u)
equation 4374 := x ◇ (y ◇ z) = w ◇ (y ◇ z)
equation 4375 := x ◇ (y ◇ z) = w ◇ (y ◇ u)
equation 4376 := x ◇ (y ◇ z) = w ◇ (z ◇ y)
equation 4377 := x ◇ (y ◇ z) = w ◇ (z ◇ u)
equation 4378 := x ◇ (y ◇ z) = w ◇ (u ◇ z)
equation 4379 := x ◇ (y ◇ z) = w ◇ (u ◇ v)
equation 4380 := x ◇ (x ◇ x) = (x ◇ x) ◇ x
equation 4381 := x ◇ (x ◇ x) = (x ◇ x) ◇ y
equation 4382 := x ◇ (x ◇ x) = (x ◇ y) ◇ x
equation 4383 := x ◇ (x ◇ x) = (x ◇ y) ◇ y
equation 4384 := x ◇ (x ◇ x) = (x ◇ y) ◇ z
equation 4385 := x ◇ (x ◇ x) = (y ◇ x) ◇ x
equation 4386 := x ◇ (x ◇ x) = (y ◇ x) ◇ y
equation 4387 := x ◇ (x ◇ x) = (y ◇ x) ◇ z
equation 4388 := x ◇ (x ◇ x) = (y ◇ y) ◇ x
equation 4389 := x ◇ (x ◇ x) = (y ◇ y) ◇ y
equation 4390 := x ◇ (x ◇ x) = (y ◇ y) ◇ z
equation 4391 := x ◇ (x ◇ x) = (y ◇ z) ◇ x
equation 4392 := x ◇ (x ◇ x) = (y ◇ z) ◇ y
equation 4393 := x ◇ (x ◇ x) = (y ◇ z) ◇ z
equation 4394 := x ◇ (x ◇ x) = (y ◇ z) ◇ w
equation 4395 := x ◇ (x ◇ y) = (x ◇ x) ◇ x
equation 4396 := x ◇ (x ◇ y) = (x ◇ x) ◇ y
equation 4397 := x ◇ (x ◇ y) = (x ◇ x) ◇ z
equation 4398 := x ◇ (x ◇ y) = (x ◇ y) ◇ x
equation 4399 := x ◇ (x ◇ y) = (x ◇ y) ◇ y
equation 4400 := x ◇ (x ◇ y) = (x ◇ y) ◇ z
equation 4401 := x ◇ (x ◇ y) = (x ◇ z) ◇ x
equation 4402 := x ◇ (x ◇ y) = (x ◇ z) ◇ y
equation 4403 := x ◇ (x ◇ y) = (x ◇ z) ◇ z
equation 4404 := x ◇ (x ◇ y) = (x ◇ z) ◇ w
equation 4405 := x ◇ (x ◇ y) = (y ◇ x) ◇ x
equation 4406 := x ◇ (x ◇ y) = (y ◇ x) ◇ y
equation 4407 := x ◇ (x ◇ y) = (y ◇ x) ◇ z
equation 4408 := x ◇ (x ◇ y) = (y ◇ y) ◇ x
equation 4409 := x ◇ (x ◇ y) = (y ◇ y) ◇ y
equation 4410 := x ◇ (x ◇ y) = (y ◇ y) ◇ z
equation 4411 := x ◇ (x ◇ y) = (y ◇ z) ◇ x
equation 4412 := x ◇ (x ◇ y) = (y ◇ z) ◇ y
equation 4413 := x ◇ (x ◇ y) = (y ◇ z) ◇ z
equation 4414 := x ◇ (x ◇ y) = (y ◇ z) ◇ w
equation 4415 := x ◇ (x ◇ y) = (z ◇ x) ◇ x
equation 4416 := x ◇ (x ◇ y) = (z ◇ x) ◇ y
equation 4417 := x ◇ (x ◇ y) = (z ◇ x) ◇ z
equation 4418 := x ◇ (x ◇ y) = (z ◇ x) ◇ w
equation 4419 := x ◇ (x ◇ y) = (z ◇ y) ◇ x
equation 4420 := x ◇ (x ◇ y) = (z ◇ y) ◇ y
equation 4421 := x ◇ (x ◇ y) = (z ◇ y) ◇ z
equation 4422 := x ◇ (x ◇ y) = (z ◇ y) ◇ w
equation 4423 := x ◇ (x ◇ y) = (z ◇ z) ◇ x
equation 4424 := x ◇ (x ◇ y) = (z ◇ z) ◇ y
equation 4425 := x ◇ (x ◇ y) = (z ◇ z) ◇ z
equation 4426 := x ◇ (x ◇ y) = (z ◇ z) ◇ w
equation 4427 := x ◇ (x ◇ y) = (z ◇ w) ◇ x
equation 4428 := x ◇ (x ◇ y) = (z ◇ w) ◇ y
equation 4429 := x ◇ (x ◇ y) = (z ◇ w) ◇ z
equation 4430 := x ◇ (x ◇ y) = (z ◇ w) ◇ w
equation 4431 := x ◇ (x ◇ y) = (z ◇ w) ◇ u
equation 4432 := x ◇ (y ◇ x) = (x ◇ x) ◇ x
equation 4433 := x ◇ (y ◇ x) = (x ◇ x) ◇ y
equation 4434 := x ◇ (y ◇ x) = (x ◇ x) ◇ z
equation 4435 := x ◇ (y ◇ x) = (x ◇ y) ◇ x
equation 4436 := x ◇ (y ◇ x) = (x ◇ y) ◇ y
equation 4437 := x ◇ (y ◇ x) = (x ◇ y) ◇ z
equation 4438 := x ◇ (y ◇ x) = (x ◇ z) ◇ x
equation 4439 := x ◇ (y ◇ x) = (x ◇ z) ◇ y
equation 4440 := x ◇ (y ◇ x) = (x ◇ z) ◇ z
equation 4441 := x ◇ (y ◇ x) = (x ◇ z) ◇ w
equation 4442 := x ◇ (y ◇ x) = (y ◇ x) ◇ x
equation 4443 := x ◇ (y ◇ x) = (y ◇ x) ◇ y
equation 4444 := x ◇ (y ◇ x) = (y ◇ x) ◇ z
equation 4445 := x ◇ (y ◇ x) = (y ◇ y) ◇ x
equation 4446 := x ◇ (y ◇ x) = (y ◇ y) ◇ y
equation 4447 := x ◇ (y ◇ x) = (y ◇ y) ◇ z
equation 4448 := x ◇ (y ◇ x) = (y ◇ z) ◇ x
equation 4449 := x ◇ (y ◇ x) = (y ◇ z) ◇ y
equation 4450 := x ◇ (y ◇ x) = (y ◇ z) ◇ z
equation 4451 := x ◇ (y ◇ x) = (y ◇ z) ◇ w
equation 4452 := x ◇ (y ◇ x) = (z ◇ x) ◇ x
equation 4453 := x ◇ (y ◇ x) = (z ◇ x) ◇ y
equation 4454 := x ◇ (y ◇ x) = (z ◇ x) ◇ z
equation 4455 := x ◇ (y ◇ x) = (z ◇ x) ◇ w
equation 4456 := x ◇ (y ◇ x) = (z ◇ y) ◇ x
equation 4457 := x ◇ (y ◇ x) = (z ◇ y) ◇ y
equation 4458 := x ◇ (y ◇ x) = (z ◇ y) ◇ z
equation 4459 := x ◇ (y ◇ x) = (z ◇ y) ◇ w
equation 4460 := x ◇ (y ◇ x) = (z ◇ z) ◇ x
equation 4461 := x ◇ (y ◇ x) = (z ◇ z) ◇ y
equation 4462 := x ◇ (y ◇ x) = (z ◇ z) ◇ z
equation 4463 := x ◇ (y ◇ x) = (z ◇ z) ◇ w
equation 4464 := x ◇ (y ◇ x) = (z ◇ w) ◇ x
equation 4465 := x ◇ (y ◇ x) = (z ◇ w) ◇ y
equation 4466 := x ◇ (y ◇ x) = (z ◇ w) ◇ z
equation 4467 := x ◇ (y ◇ x) = (z ◇ w) ◇ w
equation 4468 := x ◇ (y ◇ x) = (z ◇ w) ◇ u
equation 4469 := x ◇ (y ◇ y) = (x ◇ x) ◇ x
equation 4470 := x ◇ (y ◇ y) = (x ◇ x) ◇ y
equation 4471 := x ◇ (y ◇ y) = (x ◇ x) ◇ z
equation 4472 := x ◇ (y ◇ y) = (x ◇ y) ◇ x
equation 4473 := x ◇ (y ◇ y) = (x ◇ y) ◇ y
equation 4474 := x ◇ (y ◇ y) = (x ◇ y) ◇ z
equation 4475 := x ◇ (y ◇ y) = (x ◇ z) ◇ x
equation 4476 := x ◇ (y ◇ y) = (x ◇ z) ◇ y
equation 4477 := x ◇ (y ◇ y) = (x ◇ z) ◇ z
equation 4478 := x ◇ (y ◇ y) = (x ◇ z) ◇ w
equation 4479 := x ◇ (y ◇ y) = (y ◇ x) ◇ x
equation 4480 := x ◇ (y ◇ y) = (y ◇ x) ◇ y
equation 4481 := x ◇ (y ◇ y) = (y ◇ x) ◇ z
equation 4482 := x ◇ (y ◇ y) = (y ◇ y) ◇ x
equation 4483 := x ◇ (y ◇ y) = (y ◇ y) ◇ y
equation 4484 := x ◇ (y ◇ y) = (y ◇ y) ◇ z
equation 4485 := x ◇ (y ◇ y) = (y ◇ z) ◇ x
equation 4486 := x ◇ (y ◇ y) = (y ◇ z) ◇ y
equation 4487 := x ◇ (y ◇ y) = (y ◇ z) ◇ z
equation 4488 := x ◇ (y ◇ y) = (y ◇ z) ◇ w
equation 4489 := x ◇ (y ◇ y) = (z ◇ x) ◇ x
equation 4490 := x ◇ (y ◇ y) = (z ◇ x) ◇ y
equation 4491 := x ◇ (y ◇ y) = (z ◇ x) ◇ z
equation 4492 := x ◇ (y ◇ y) = (z ◇ x) ◇ w
equation 4493 := x ◇ (y ◇ y) = (z ◇ y) ◇ x
equation 4494 := x ◇ (y ◇ y) = (z ◇ y) ◇ y
equation 4495 := x ◇ (y ◇ y) = (z ◇ y) ◇ z
equation 4496 := x ◇ (y ◇ y) = (z ◇ y) ◇ w
equation 4497 := x ◇ (y ◇ y) = (z ◇ z) ◇ x
equation 4498 := x ◇ (y ◇ y) = (z ◇ z) ◇ y
equation 4499 := x ◇ (y ◇ y) = (z ◇ z) ◇ z
equation 4500 := x ◇ (y ◇ y) = (z ◇ z) ◇ w
equation 4501 := x ◇ (y ◇ y) = (z ◇ w) ◇ x
equation 4502 := x ◇ (y ◇ y) = (z ◇ w) ◇ y
equation 4503 := x ◇ (y ◇ y) = (z ◇ w) ◇ z
equation 4504 := x ◇ (y ◇ y) = (z ◇ w) ◇ w
equation 4505 := x ◇ (y ◇ y) = (z ◇ w) ◇ u
equation 4506 := x ◇ (y ◇ z) = (x ◇ x) ◇ x
equation 4507 := x ◇ (y ◇ z) = (x ◇ x) ◇ y
equation 4508 := x ◇ (y ◇ z) = (x ◇ x) ◇ z
equation 4509 := x ◇ (y ◇ z) = (x ◇ x) ◇ w
equation 4510 := x ◇ (y ◇ z) = (x ◇ y) ◇ x
equation 4511 := x ◇ (y ◇ z) = (x ◇ y) ◇ y
-- equation 4512 := x ◇ (y ◇ z) = (x ◇ y) ◇ z
-- equation 4513 := x ◇ (y ◇ z) = (x ◇ y) ◇ w
equation 4514 := x ◇ (y ◇ z) = (x ◇ z) ◇ x
equation 4515 := x ◇ (y ◇ z) = (x ◇ z) ◇ y
equation 4516 := x ◇ (y ◇ z) = (x ◇ z) ◇ z
equation 4517 := x ◇ (y ◇ z) = (x ◇ z) ◇ w
equation 4518 := x ◇ (y ◇ z) = (x ◇ w) ◇ x
equation 4519 := x ◇ (y ◇ z) = (x ◇ w) ◇ y
equation 4520 := x ◇ (y ◇ z) = (x ◇ w) ◇ z
equation 4521 := x ◇ (y ◇ z) = (x ◇ w) ◇ w
-- equation 4522 := x ◇ (y ◇ z) = (x ◇ w) ◇ u
equation 4523 := x ◇ (y ◇ z) = (y ◇ x) ◇ x
equation 4524 := x ◇ (y ◇ z) = (y ◇ x) ◇ y
equation 4525 := x ◇ (y ◇ z) = (y ◇ x) ◇ z
equation 4526 := x ◇ (y ◇ z) = (y ◇ x) ◇ w
equation 4527 := x ◇ (y ◇ z) = (y ◇ y) ◇ x
equation 4528 := x ◇ (y ◇ z) = (y ◇ y) ◇ y
equation 4529 := x ◇ (y ◇ z) = (y ◇ y) ◇ z
equation 4530 := x ◇ (y ◇ z) = (y ◇ y) ◇ w
equation 4531 := x ◇ (y ◇ z) = (y ◇ z) ◇ x
equation 4532 := x ◇ (y ◇ z) = (y ◇ z) ◇ y
equation 4533 := x ◇ (y ◇ z) = (y ◇ z) ◇ z
equation 4534 := x ◇ (y ◇ z) = (y ◇ z) ◇ w
equation 4535 := x ◇ (y ◇ z) = (y ◇ w) ◇ x
equation 4536 := x ◇ (y ◇ z) = (y ◇ w) ◇ y
equation 4537 := x ◇ (y ◇ z) = (y ◇ w) ◇ z
equation 4538 := x ◇ (y ◇ z) = (y ◇ w) ◇ w
equation 4539 := x ◇ (y ◇ z) = (y ◇ w) ◇ u
equation 4540 := x ◇ (y ◇ z) = (z ◇ x) ◇ x
equation 4541 := x ◇ (y ◇ z) = (z ◇ x) ◇ y
equation 4542 := x ◇ (y ◇ z) = (z ◇ x) ◇ z
equation 4543 := x ◇ (y ◇ z) = (z ◇ x) ◇ w
equation 4544 := x ◇ (y ◇ z) = (z ◇ y) ◇ x
equation 4545 := x ◇ (y ◇ z) = (z ◇ y) ◇ y
equation 4546 := x ◇ (y ◇ z) = (z ◇ y) ◇ z
equation 4547 := x ◇ (y ◇ z) = (z ◇ y) ◇ w
equation 4548 := x ◇ (y ◇ z) = (z ◇ z) ◇ x
equation 4549 := x ◇ (y ◇ z) = (z ◇ z) ◇ y
equation 4550 := x ◇ (y ◇ z) = (z ◇ z) ◇ z
equation 4551 := x ◇ (y ◇ z) = (z ◇ z) ◇ w
equation 4552 := x ◇ (y ◇ z) = (z ◇ w) ◇ x
equation 4553 := x ◇ (y ◇ z) = (z ◇ w) ◇ y
equation 4554 := x ◇ (y ◇ z) = (z ◇ w) ◇ z
equation 4555 := x ◇ (y ◇ z) = (z ◇ w) ◇ w
equation 4556 := x ◇ (y ◇ z) = (z ◇ w) ◇ u
equation 4557 := x ◇ (y ◇ z) = (w ◇ x) ◇ x
equation 4558 := x ◇ (y ◇ z) = (w ◇ x) ◇ y
equation 4559 := x ◇ (y ◇ z) = (w ◇ x) ◇ z
equation 4560 := x ◇ (y ◇ z) = (w ◇ x) ◇ w
equation 4561 := x ◇ (y ◇ z) = (w ◇ x) ◇ u
equation 4562 := x ◇ (y ◇ z) = (w ◇ y) ◇ x
equation 4563 := x ◇ (y ◇ z) = (w ◇ y) ◇ y
-- equation 4564 := x ◇ (y ◇ z) = (w ◇ y) ◇ z
equation 4565 := x ◇ (y ◇ z) = (w ◇ y) ◇ w
equation 4566 := x ◇ (y ◇ z) = (w ◇ y) ◇ u
equation 4567 := x ◇ (y ◇ z) = (w ◇ z) ◇ x
equation 4568 := x ◇ (y ◇ z) = (w ◇ z) ◇ y
equation 4569 := x ◇ (y ◇ z) = (w ◇ z) ◇ z
equation 4570 := x ◇ (y ◇ z) = (w ◇ z) ◇ w
equation 4571 := x ◇ (y ◇ z) = (w ◇ z) ◇ u
equation 4572 := x ◇ (y ◇ z) = (w ◇ w) ◇ x
equation 4573 := x ◇ (y ◇ z) = (w ◇ w) ◇ y
equation 4574 := x ◇ (y ◇ z) = (w ◇ w) ◇ z
equation 4575 := x ◇ (y ◇ z) = (w ◇ w) ◇ w
equation 4576 := x ◇ (y ◇ z) = (w ◇ w) ◇ u
equation 4577 := x ◇ (y ◇ z) = (w ◇ u) ◇ x
equation 4578 := x ◇ (y ◇ z) = (w ◇ u) ◇ y
-- equation 4579 := x ◇ (y ◇ z) = (w ◇ u) ◇ z
equation 4580 := x ◇ (y ◇ z) = (w ◇ u) ◇ w
equation 4581 := x ◇ (y ◇ z) = (w ◇ u) ◇ u
-- equation 4582 := x ◇ (y ◇ z) = (w ◇ u) ◇ v
equation 4583 := (x ◇ x) ◇ x = (x ◇ x) ◇ y
equation 4584 := (x ◇ x) ◇ x = (x ◇ y) ◇ x
equation 4585 := (x ◇ x) ◇ x = (x ◇ y) ◇ y
equation 4586 := (x ◇ x) ◇ x = (x ◇ y) ◇ z
equation 4587 := (x ◇ x) ◇ x = (y ◇ x) ◇ x
equation 4588 := (x ◇ x) ◇ x = (y ◇ x) ◇ y
equation 4589 := (x ◇ x) ◇ x = (y ◇ x) ◇ z
equation 4590 := (x ◇ x) ◇ x = (y ◇ y) ◇ x
equation 4591 := (x ◇ x) ◇ x = (y ◇ y) ◇ y
equation 4592 := (x ◇ x) ◇ x = (y ◇ y) ◇ z
equation 4593 := (x ◇ x) ◇ x = (y ◇ z) ◇ x
equation 4594 := (x ◇ x) ◇ x = (y ◇ z) ◇ y
equation 4595 := (x ◇ x) ◇ x = (y ◇ z) ◇ z
equation 4596 := (x ◇ x) ◇ x = (y ◇ z) ◇ w
equation 4597 := (x ◇ x) ◇ y = (x ◇ x) ◇ z
equation 4598 := (x ◇ x) ◇ y = (x ◇ y) ◇ x
equation 4599 := (x ◇ x) ◇ y = (x ◇ y) ◇ y
equation 4600 := (x ◇ x) ◇ y = (x ◇ y) ◇ z
equation 4601 := (x ◇ x) ◇ y = (x ◇ z) ◇ x
equation 4602 := (x ◇ x) ◇ y = (x ◇ z) ◇ y
equation 4603 := (x ◇ x) ◇ y = (x ◇ z) ◇ z
equation 4604 := (x ◇ x) ◇ y = (x ◇ z) ◇ w
equation 4605 := (x ◇ x) ◇ y = (y ◇ x) ◇ x
equation 4606 := (x ◇ x) ◇ y = (y ◇ x) ◇ y
equation 4607 := (x ◇ x) ◇ y = (y ◇ x) ◇ z
equation 4608 := (x ◇ x) ◇ y = (y ◇ y) ◇ x
equation 4609 := (x ◇ x) ◇ y = (y ◇ y) ◇ z
equation 4610 := (x ◇ x) ◇ y = (y ◇ z) ◇ x
equation 4611 := (x ◇ x) ◇ y = (y ◇ z) ◇ y
equation 4612 := (x ◇ x) ◇ y = (y ◇ z) ◇ z
equation 4613 := (x ◇ x) ◇ y = (y ◇ z) ◇ w
equation 4614 := (x ◇ x) ◇ y = (z ◇ x) ◇ x
equation 4615 := (x ◇ x) ◇ y = (z ◇ x) ◇ y
equation 4616 := (x ◇ x) ◇ y = (z ◇ x) ◇ z
equation 4617 := (x ◇ x) ◇ y = (z ◇ x) ◇ w
equation 4618 := (x ◇ x) ◇ y = (z ◇ y) ◇ x
equation 4619 := (x ◇ x) ◇ y = (z ◇ y) ◇ y
equation 4620 := (x ◇ x) ◇ y = (z ◇ y) ◇ z
equation 4621 := (x ◇ x) ◇ y = (z ◇ y) ◇ w
equation 4622 := (x ◇ x) ◇ y = (z ◇ z) ◇ y
equation 4623 := (x ◇ x) ◇ y = (z ◇ z) ◇ w
equation 4624 := (x ◇ x) ◇ y = (z ◇ w) ◇ x
equation 4625 := (x ◇ x) ◇ y = (z ◇ w) ◇ y
equation 4626 := (x ◇ x) ◇ y = (z ◇ w) ◇ z
equation 4627 := (x ◇ x) ◇ y = (z ◇ w) ◇ w
equation 4628 := (x ◇ x) ◇ y = (z ◇ w) ◇ u
equation 4629 := (x ◇ y) ◇ x = (x ◇ y) ◇ y
equation 4630 := (x ◇ y) ◇ x = (x ◇ y) ◇ z
equation 4631 := (x ◇ y) ◇ x = (x ◇ z) ◇ x
equation 4632 := (x ◇ y) ◇ x = (x ◇ z) ◇ y
equation 4633 := (x ◇ y) ◇ x = (x ◇ z) ◇ z
equation 4634 := (x ◇ y) ◇ x = (x ◇ z) ◇ w
equation 4635 := (x ◇ y) ◇ x = (y ◇ x) ◇ x
equation 4636 := (x ◇ y) ◇ x = (y ◇ x) ◇ y
equation 4637 := (x ◇ y) ◇ x = (y ◇ x) ◇ z
equation 4638 := (x ◇ y) ◇ x = (y ◇ z) ◇ x
equation 4639 := (x ◇ y) ◇ x = (y ◇ z) ◇ y
equation 4640 := (x ◇ y) ◇ x = (y ◇ z) ◇ z
equation 4641 := (x ◇ y) ◇ x = (y ◇ z) ◇ w
equation 4642 := (x ◇ y) ◇ x = (z ◇ x) ◇ x
equation 4643 := (x ◇ y) ◇ x = (z ◇ x) ◇ y
equation 4644 := (x ◇ y) ◇ x = (z ◇ x) ◇ w
equation 4645 := (x ◇ y) ◇ x = (z ◇ y) ◇ x
equation 4646 := (x ◇ y) ◇ x = (z ◇ y) ◇ y
equation 4647 := (x ◇ y) ◇ x = (z ◇ y) ◇ z
equation 4648 := (x ◇ y) ◇ x = (z ◇ y) ◇ w
equation 4649 := (x ◇ y) ◇ x = (z ◇ w) ◇ x
equation 4650 := (x ◇ y) ◇ x = (z ◇ w) ◇ y
equation 4651 := (x ◇ y) ◇ x = (z ◇ w) ◇ z
equation 4652 := (x ◇ y) ◇ x = (z ◇ w) ◇ w
equation 4653 := (x ◇ y) ◇ x = (z ◇ w) ◇ u
equation 4654 := (x ◇ y) ◇ y = (x ◇ y) ◇ z
equation 4655 := (x ◇ y) ◇ y = (x ◇ z) ◇ y
equation 4656 := (x ◇ y) ◇ y = (x ◇ z) ◇ z
equation 4657 := (x ◇ y) ◇ y = (x ◇ z) ◇ w
equation 4658 := (x ◇ y) ◇ y = (y ◇ x) ◇ x
equation 4659 := (x ◇ y) ◇ y = (y ◇ x) ◇ z
equation 4660 := (x ◇ y) ◇ y = (y ◇ z) ◇ x
equation 4661 := (x ◇ y) ◇ y = (y ◇ z) ◇ z
equation 4662 := (x ◇ y) ◇ y = (y ◇ z) ◇ w
equation 4663 := (x ◇ y) ◇ y = (z ◇ x) ◇ y
equation 4664 := (x ◇ y) ◇ y = (z ◇ x) ◇ w
equation 4665 := (x ◇ y) ◇ y = (z ◇ y) ◇ x
equation 4666 := (x ◇ y) ◇ y = (z ◇ y) ◇ y
equation 4667 := (x ◇ y) ◇ y = (z ◇ y) ◇ w
equation 4668 := (x ◇ y) ◇ y = (z ◇ w) ◇ x
equation 4669 := (x ◇ y) ◇ y = (z ◇ w) ◇ y
equation 4670 := (x ◇ y) ◇ y = (z ◇ w) ◇ w
equation 4671 := (x ◇ y) ◇ y = (z ◇ w) ◇ u
equation 4672 := (x ◇ y) ◇ z = (x ◇ y) ◇ w
equation 4673 := (x ◇ y) ◇ z = (x ◇ z) ◇ y
equation 4674 := (x ◇ y) ◇ z = (x ◇ z) ◇ w
equation 4675 := (x ◇ y) ◇ z = (x ◇ w) ◇ z
equation 4676 := (x ◇ y) ◇ z = (x ◇ w) ◇ u
equation 4677 := (x ◇ y) ◇ z = (y ◇ x) ◇ z
equation 4678 := (x ◇ y) ◇ z = (y ◇ x) ◇ w
equation 4679 := (x ◇ y) ◇ z = (y ◇ z) ◇ x
equation 4680 := (x ◇ y) ◇ z = (y ◇ z) ◇ w
equation 4681 := (x ◇ y) ◇ z = (y ◇ w) ◇ x
equation 4682 := (x ◇ y) ◇ z = (y ◇ w) ◇ z
equation 4683 := (x ◇ y) ◇ z = (y ◇ w) ◇ u
equation 4684 := (x ◇ y) ◇ z = (z ◇ y) ◇ x
equation 4685 := (x ◇ y) ◇ z = (z ◇ y) ◇ w
equation 4686 := (x ◇ y) ◇ z = (z ◇ w) ◇ x
equation 4687 := (x ◇ y) ◇ z = (z ◇ w) ◇ y
equation 4688 := (x ◇ y) ◇ z = (z ◇ w) ◇ u
equation 4689 := (x ◇ y) ◇ z = (w ◇ y) ◇ z
equation 4690 := (x ◇ y) ◇ z = (w ◇ y) ◇ u
equation 4691 := (x ◇ y) ◇ z = (w ◇ z) ◇ y
equation 4692 := (x ◇ y) ◇ z = (w ◇ z) ◇ u
equation 4693 := (x ◇ y) ◇ z = (w ◇ u) ◇ z
equation 4694 := (x ◇ y) ◇ z = (w ◇ u) ◇ v
