import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 1-999 -/

-- equation 1 := x = x
-- equation 2 := x = y
-- equation 3 := x = x ◇ x
-- equation 4 := x = x ◇ y
-- equation 5 := x = y ◇ x
-- equation 6 := x = y ◇ y
-- equation 7 := x = y ◇ z
-- equation 8 := x = x ◇ (x ◇ x)
equation 9 := x = x ◇ (x ◇ y)
equation 10 := x = x ◇ (y ◇ x)
equation 11 := x = x ◇ (y ◇ y)
equation 12 := x = x ◇ (y ◇ z)
equation 13 := x = y ◇ (x ◇ x)
-- equation 14 := x = y ◇ (x ◇ y)
equation 15 := x = y ◇ (x ◇ z)
-- equation 16 := x = y ◇ (y ◇ x)
equation 17 := x = y ◇ (y ◇ y)
equation 18 := x = y ◇ (y ◇ z)
equation 19 := x = y ◇ (z ◇ x)
equation 20 := x = y ◇ (z ◇ y)
equation 21 := x = y ◇ (z ◇ z)
equation 22 := x = y ◇ (z ◇ w)
-- equation 23 := x = (x ◇ x) ◇ x
equation 24 := x = (x ◇ x) ◇ y
equation 25 := x = (x ◇ y) ◇ x
equation 26 := x = (x ◇ y) ◇ y
equation 27 := x = (x ◇ y) ◇ z
equation 28 := x = (y ◇ x) ◇ x
-- equation 29 := x = (y ◇ x) ◇ y
equation 30 := x = (y ◇ x) ◇ z
equation 31 := x = (y ◇ y) ◇ x
equation 32 := x = (y ◇ y) ◇ y
equation 33 := x = (y ◇ y) ◇ z
equation 34 := x = (y ◇ z) ◇ x
equation 35 := x = (y ◇ z) ◇ y
equation 36 := x = (y ◇ z) ◇ z
equation 37 := x = (y ◇ z) ◇ w
-- equation 38 := x ◇ x = x ◇ y
-- equation 39 := x ◇ x = y ◇ x
-- equation 40 := x ◇ x = y ◇ y
-- equation 41 := x ◇ x = y ◇ z
-- equation 42 := x ◇ y = x ◇ z
-- equation 43 := x ◇ y = y ◇ x
equation 44 := x ◇ y = y ◇ z
-- equation 45 := x ◇ y = z ◇ y
-- equation 46 := x ◇ y = z ◇ w
equation 47 := x = x ◇ (x ◇ (x ◇ x))
equation 48 := x = x ◇ (x ◇ (x ◇ y))
equation 49 := x = x ◇ (x ◇ (y ◇ x))
equation 50 := x = x ◇ (x ◇ (y ◇ y))
equation 51 := x = x ◇ (x ◇ (y ◇ z))
equation 52 := x = x ◇ (y ◇ (x ◇ x))
equation 53 := x = x ◇ (y ◇ (x ◇ y))
equation 54 := x = x ◇ (y ◇ (x ◇ z))
equation 55 := x = x ◇ (y ◇ (y ◇ x))
equation 56 := x = x ◇ (y ◇ (y ◇ y))
equation 57 := x = x ◇ (y ◇ (y ◇ z))
equation 58 := x = x ◇ (y ◇ (z ◇ x))
equation 59 := x = x ◇ (y ◇ (z ◇ y))
equation 60 := x = x ◇ (y ◇ (z ◇ z))
equation 61 := x = x ◇ (y ◇ (z ◇ w))
equation 62 := x = y ◇ (x ◇ (x ◇ x))
equation 63 := x = y ◇ (x ◇ (x ◇ y))
equation 64 := x = y ◇ (x ◇ (x ◇ z))
equation 65 := x = y ◇ (x ◇ (y ◇ x))
equation 66 := x = y ◇ (x ◇ (y ◇ y))
equation 67 := x = y ◇ (x ◇ (y ◇ z))
equation 68 := x = y ◇ (x ◇ (z ◇ x))
equation 69 := x = y ◇ (x ◇ (z ◇ y))
equation 70 := x = y ◇ (x ◇ (z ◇ z))
equation 71 := x = y ◇ (x ◇ (z ◇ w))
equation 72 := x = y ◇ (y ◇ (x ◇ x))
equation 73 := x = y ◇ (y ◇ (x ◇ y))
equation 74 := x = y ◇ (y ◇ (x ◇ z))
equation 75 := x = y ◇ (y ◇ (y ◇ x))
equation 76 := x = y ◇ (y ◇ (y ◇ y))
equation 77 := x = y ◇ (y ◇ (y ◇ z))
equation 78 := x = y ◇ (y ◇ (z ◇ x))
equation 79 := x = y ◇ (y ◇ (z ◇ y))
equation 80 := x = y ◇ (y ◇ (z ◇ z))
equation 81 := x = y ◇ (y ◇ (z ◇ w))
equation 82 := x = y ◇ (z ◇ (x ◇ x))
equation 83 := x = y ◇ (z ◇ (x ◇ y))
equation 84 := x = y ◇ (z ◇ (x ◇ z))
equation 85 := x = y ◇ (z ◇ (x ◇ w))
equation 86 := x = y ◇ (z ◇ (y ◇ x))
equation 87 := x = y ◇ (z ◇ (y ◇ y))
equation 88 := x = y ◇ (z ◇ (y ◇ z))
equation 89 := x = y ◇ (z ◇ (y ◇ w))
equation 90 := x = y ◇ (z ◇ (z ◇ x))
equation 91 := x = y ◇ (z ◇ (z ◇ y))
equation 92 := x = y ◇ (z ◇ (z ◇ z))
equation 93 := x = y ◇ (z ◇ (z ◇ w))
equation 94 := x = y ◇ (z ◇ (w ◇ x))
equation 95 := x = y ◇ (z ◇ (w ◇ y))
equation 96 := x = y ◇ (z ◇ (w ◇ z))
equation 97 := x = y ◇ (z ◇ (w ◇ w))
equation 98 := x = y ◇ (z ◇ (w ◇ u))
equation 99 := x = x ◇ ((x ◇ x) ◇ x)
equation 100 := x = x ◇ ((x ◇ x) ◇ y)
equation 101 := x = x ◇ ((x ◇ y) ◇ x)
equation 102 := x = x ◇ ((x ◇ y) ◇ y)
equation 103 := x = x ◇ ((x ◇ y) ◇ z)
equation 104 := x = x ◇ ((y ◇ x) ◇ x)
equation 105 := x = x ◇ ((y ◇ x) ◇ y)
equation 106 := x = x ◇ ((y ◇ x) ◇ z)
equation 107 := x = x ◇ ((y ◇ y) ◇ x)
equation 108 := x = x ◇ ((y ◇ y) ◇ y)
equation 109 := x = x ◇ ((y ◇ y) ◇ z)
equation 110 := x = x ◇ ((y ◇ z) ◇ x)
equation 111 := x = x ◇ ((y ◇ z) ◇ y)
equation 112 := x = x ◇ ((y ◇ z) ◇ z)
equation 113 := x = x ◇ ((y ◇ z) ◇ w)
equation 114 := x = y ◇ ((x ◇ x) ◇ x)
equation 115 := x = y ◇ ((x ◇ x) ◇ y)
equation 116 := x = y ◇ ((x ◇ x) ◇ z)
equation 117 := x = y ◇ ((x ◇ y) ◇ x)
equation 118 := x = y ◇ ((x ◇ y) ◇ y)
equation 119 := x = y ◇ ((x ◇ y) ◇ z)
equation 120 := x = y ◇ ((x ◇ z) ◇ x)
equation 121 := x = y ◇ ((x ◇ z) ◇ y)
equation 122 := x = y ◇ ((x ◇ z) ◇ z)
equation 123 := x = y ◇ ((x ◇ z) ◇ w)
equation 124 := x = y ◇ ((y ◇ x) ◇ x)
equation 125 := x = y ◇ ((y ◇ x) ◇ y)
equation 126 := x = y ◇ ((y ◇ x) ◇ z)
equation 127 := x = y ◇ ((y ◇ y) ◇ x)
equation 128 := x = y ◇ ((y ◇ y) ◇ y)
equation 129 := x = y ◇ ((y ◇ y) ◇ z)
equation 130 := x = y ◇ ((y ◇ z) ◇ x)
equation 131 := x = y ◇ ((y ◇ z) ◇ y)
equation 132 := x = y ◇ ((y ◇ z) ◇ z)
equation 133 := x = y ◇ ((y ◇ z) ◇ w)
equation 134 := x = y ◇ ((z ◇ x) ◇ x)
equation 135 := x = y ◇ ((z ◇ x) ◇ y)
equation 136 := x = y ◇ ((z ◇ x) ◇ z)
equation 137 := x = y ◇ ((z ◇ x) ◇ w)
equation 138 := x = y ◇ ((z ◇ y) ◇ x)
equation 139 := x = y ◇ ((z ◇ y) ◇ y)
equation 140 := x = y ◇ ((z ◇ y) ◇ z)
equation 141 := x = y ◇ ((z ◇ y) ◇ w)
equation 142 := x = y ◇ ((z ◇ z) ◇ x)
equation 143 := x = y ◇ ((z ◇ z) ◇ y)
equation 144 := x = y ◇ ((z ◇ z) ◇ z)
equation 145 := x = y ◇ ((z ◇ z) ◇ w)
equation 146 := x = y ◇ ((z ◇ w) ◇ x)
equation 147 := x = y ◇ ((z ◇ w) ◇ y)
equation 148 := x = y ◇ ((z ◇ w) ◇ z)
equation 149 := x = y ◇ ((z ◇ w) ◇ w)
equation 150 := x = y ◇ ((z ◇ w) ◇ u)
equation 151 := x = (x ◇ x) ◇ (x ◇ x)
equation 152 := x = (x ◇ x) ◇ (x ◇ y)
equation 153 := x = (x ◇ x) ◇ (y ◇ x)
equation 154 := x = (x ◇ x) ◇ (y ◇ y)
equation 155 := x = (x ◇ x) ◇ (y ◇ z)
equation 156 := x = (x ◇ y) ◇ (x ◇ x)
equation 157 := x = (x ◇ y) ◇ (x ◇ y)
equation 158 := x = (x ◇ y) ◇ (x ◇ z)
equation 159 := x = (x ◇ y) ◇ (y ◇ x)
equation 160 := x = (x ◇ y) ◇ (y ◇ y)
equation 161 := x = (x ◇ y) ◇ (y ◇ z)
equation 162 := x = (x ◇ y) ◇ (z ◇ x)
equation 163 := x = (x ◇ y) ◇ (z ◇ y)
equation 164 := x = (x ◇ y) ◇ (z ◇ z)
equation 165 := x = (x ◇ y) ◇ (z ◇ w)
equation 166 := x = (y ◇ x) ◇ (x ◇ x)
equation 167 := x = (y ◇ x) ◇ (x ◇ y)
-- equation 168 := x = (y ◇ x) ◇ (x ◇ z)
equation 169 := x = (y ◇ x) ◇ (y ◇ x)
equation 170 := x = (y ◇ x) ◇ (y ◇ y)
equation 171 := x = (y ◇ x) ◇ (y ◇ z)
equation 172 := x = (y ◇ x) ◇ (z ◇ x)
equation 173 := x = (y ◇ x) ◇ (z ◇ y)
equation 174 := x = (y ◇ x) ◇ (z ◇ z)
equation 175 := x = (y ◇ x) ◇ (z ◇ w)
equation 176 := x = (y ◇ y) ◇ (x ◇ x)
equation 177 := x = (y ◇ y) ◇ (x ◇ y)
equation 178 := x = (y ◇ y) ◇ (x ◇ z)
equation 179 := x = (y ◇ y) ◇ (y ◇ x)
equation 180 := x = (y ◇ y) ◇ (y ◇ y)
equation 181 := x = (y ◇ y) ◇ (y ◇ z)
equation 182 := x = (y ◇ y) ◇ (z ◇ x)
equation 183 := x = (y ◇ y) ◇ (z ◇ y)
equation 184 := x = (y ◇ y) ◇ (z ◇ z)
equation 185 := x = (y ◇ y) ◇ (z ◇ w)
equation 186 := x = (y ◇ z) ◇ (x ◇ x)
equation 187 := x = (y ◇ z) ◇ (x ◇ y)
equation 188 := x = (y ◇ z) ◇ (x ◇ z)
equation 189 := x = (y ◇ z) ◇ (x ◇ w)
equation 190 := x = (y ◇ z) ◇ (y ◇ x)
equation 191 := x = (y ◇ z) ◇ (y ◇ y)
equation 192 := x = (y ◇ z) ◇ (y ◇ z)
equation 193 := x = (y ◇ z) ◇ (y ◇ w)
equation 194 := x = (y ◇ z) ◇ (z ◇ x)
equation 195 := x = (y ◇ z) ◇ (z ◇ y)
equation 196 := x = (y ◇ z) ◇ (z ◇ z)
equation 197 := x = (y ◇ z) ◇ (z ◇ w)
equation 198 := x = (y ◇ z) ◇ (w ◇ x)
equation 199 := x = (y ◇ z) ◇ (w ◇ y)
equation 200 := x = (y ◇ z) ◇ (w ◇ z)
equation 201 := x = (y ◇ z) ◇ (w ◇ w)
equation 202 := x = (y ◇ z) ◇ (w ◇ u)
equation 203 := x = (x ◇ (x ◇ x)) ◇ x
equation 204 := x = (x ◇ (x ◇ x)) ◇ y
equation 205 := x = (x ◇ (x ◇ y)) ◇ x
equation 206 := x = (x ◇ (x ◇ y)) ◇ y
equation 207 := x = (x ◇ (x ◇ y)) ◇ z
equation 208 := x = (x ◇ (y ◇ x)) ◇ x
equation 209 := x = (x ◇ (y ◇ x)) ◇ y
equation 210 := x = (x ◇ (y ◇ x)) ◇ z
equation 211 := x = (x ◇ (y ◇ y)) ◇ x
equation 212 := x = (x ◇ (y ◇ y)) ◇ y
equation 213 := x = (x ◇ (y ◇ y)) ◇ z
equation 214 := x = (x ◇ (y ◇ z)) ◇ x
equation 215 := x = (x ◇ (y ◇ z)) ◇ y
equation 216 := x = (x ◇ (y ◇ z)) ◇ z
equation 217 := x = (x ◇ (y ◇ z)) ◇ w
equation 218 := x = (y ◇ (x ◇ x)) ◇ x
equation 219 := x = (y ◇ (x ◇ x)) ◇ y
equation 220 := x = (y ◇ (x ◇ x)) ◇ z
equation 221 := x = (y ◇ (x ◇ y)) ◇ x
equation 222 := x = (y ◇ (x ◇ y)) ◇ y
equation 223 := x = (y ◇ (x ◇ y)) ◇ z
equation 224 := x = (y ◇ (x ◇ z)) ◇ x
equation 225 := x = (y ◇ (x ◇ z)) ◇ y
equation 226 := x = (y ◇ (x ◇ z)) ◇ z
equation 227 := x = (y ◇ (x ◇ z)) ◇ w
equation 228 := x = (y ◇ (y ◇ x)) ◇ x
equation 229 := x = (y ◇ (y ◇ x)) ◇ y
equation 230 := x = (y ◇ (y ◇ x)) ◇ z
equation 231 := x = (y ◇ (y ◇ y)) ◇ x
equation 232 := x = (y ◇ (y ◇ y)) ◇ y
equation 233 := x = (y ◇ (y ◇ y)) ◇ z
equation 234 := x = (y ◇ (y ◇ z)) ◇ x
equation 235 := x = (y ◇ (y ◇ z)) ◇ y
equation 236 := x = (y ◇ (y ◇ z)) ◇ z
equation 237 := x = (y ◇ (y ◇ z)) ◇ w
equation 238 := x = (y ◇ (z ◇ x)) ◇ x
equation 239 := x = (y ◇ (z ◇ x)) ◇ y
equation 240 := x = (y ◇ (z ◇ x)) ◇ z
equation 241 := x = (y ◇ (z ◇ x)) ◇ w
equation 242 := x = (y ◇ (z ◇ y)) ◇ x
equation 243 := x = (y ◇ (z ◇ y)) ◇ y
equation 244 := x = (y ◇ (z ◇ y)) ◇ z
equation 245 := x = (y ◇ (z ◇ y)) ◇ w
equation 246 := x = (y ◇ (z ◇ z)) ◇ x
equation 247 := x = (y ◇ (z ◇ z)) ◇ y
equation 248 := x = (y ◇ (z ◇ z)) ◇ z
equation 249 := x = (y ◇ (z ◇ z)) ◇ w
equation 250 := x = (y ◇ (z ◇ w)) ◇ x
equation 251 := x = (y ◇ (z ◇ w)) ◇ y
equation 252 := x = (y ◇ (z ◇ w)) ◇ z
equation 253 := x = (y ◇ (z ◇ w)) ◇ w
equation 254 := x = (y ◇ (z ◇ w)) ◇ u
equation 255 := x = ((x ◇ x) ◇ x) ◇ x
equation 256 := x = ((x ◇ x) ◇ x) ◇ y
equation 257 := x = ((x ◇ x) ◇ y) ◇ x
equation 258 := x = ((x ◇ x) ◇ y) ◇ y
equation 259 := x = ((x ◇ x) ◇ y) ◇ z
equation 260 := x = ((x ◇ y) ◇ x) ◇ x
equation 261 := x = ((x ◇ y) ◇ x) ◇ y
equation 262 := x = ((x ◇ y) ◇ x) ◇ z
equation 263 := x = ((x ◇ y) ◇ y) ◇ x
equation 264 := x = ((x ◇ y) ◇ y) ◇ y
equation 265 := x = ((x ◇ y) ◇ y) ◇ z
equation 266 := x = ((x ◇ y) ◇ z) ◇ x
equation 267 := x = ((x ◇ y) ◇ z) ◇ y
equation 268 := x = ((x ◇ y) ◇ z) ◇ z
equation 269 := x = ((x ◇ y) ◇ z) ◇ w
equation 270 := x = ((y ◇ x) ◇ x) ◇ x
equation 271 := x = ((y ◇ x) ◇ x) ◇ y
equation 272 := x = ((y ◇ x) ◇ x) ◇ z
equation 273 := x = ((y ◇ x) ◇ y) ◇ x
equation 274 := x = ((y ◇ x) ◇ y) ◇ y
equation 275 := x = ((y ◇ x) ◇ y) ◇ z
equation 276 := x = ((y ◇ x) ◇ z) ◇ x
equation 277 := x = ((y ◇ x) ◇ z) ◇ y
equation 278 := x = ((y ◇ x) ◇ z) ◇ z
equation 279 := x = ((y ◇ x) ◇ z) ◇ w
equation 280 := x = ((y ◇ y) ◇ x) ◇ x
equation 281 := x = ((y ◇ y) ◇ x) ◇ y
equation 282 := x = ((y ◇ y) ◇ x) ◇ z
equation 283 := x = ((y ◇ y) ◇ y) ◇ x
equation 284 := x = ((y ◇ y) ◇ y) ◇ y
equation 285 := x = ((y ◇ y) ◇ y) ◇ z
equation 286 := x = ((y ◇ y) ◇ z) ◇ x
equation 287 := x = ((y ◇ y) ◇ z) ◇ y
equation 288 := x = ((y ◇ y) ◇ z) ◇ z
equation 289 := x = ((y ◇ y) ◇ z) ◇ w
equation 290 := x = ((y ◇ z) ◇ x) ◇ x
equation 291 := x = ((y ◇ z) ◇ x) ◇ y
equation 292 := x = ((y ◇ z) ◇ x) ◇ z
equation 293 := x = ((y ◇ z) ◇ x) ◇ w
equation 294 := x = ((y ◇ z) ◇ y) ◇ x
equation 295 := x = ((y ◇ z) ◇ y) ◇ y
equation 296 := x = ((y ◇ z) ◇ y) ◇ z
equation 297 := x = ((y ◇ z) ◇ y) ◇ w
equation 298 := x = ((y ◇ z) ◇ z) ◇ x
equation 299 := x = ((y ◇ z) ◇ z) ◇ y
equation 300 := x = ((y ◇ z) ◇ z) ◇ z
equation 301 := x = ((y ◇ z) ◇ z) ◇ w
equation 302 := x = ((y ◇ z) ◇ w) ◇ x
equation 303 := x = ((y ◇ z) ◇ w) ◇ y
equation 304 := x = ((y ◇ z) ◇ w) ◇ z
equation 305 := x = ((y ◇ z) ◇ w) ◇ w
equation 306 := x = ((y ◇ z) ◇ w) ◇ u
equation 307 := x ◇ x = x ◇ (x ◇ x)
equation 308 := x ◇ x = x ◇ (x ◇ y)
equation 309 := x ◇ x = x ◇ (y ◇ x)
equation 310 := x ◇ x = x ◇ (y ◇ y)
equation 311 := x ◇ x = x ◇ (y ◇ z)
equation 312 := x ◇ x = y ◇ (x ◇ x)
equation 313 := x ◇ x = y ◇ (x ◇ y)
equation 314 := x ◇ x = y ◇ (x ◇ z)
equation 315 := x ◇ x = y ◇ (y ◇ x)
equation 316 := x ◇ x = y ◇ (y ◇ y)
equation 317 := x ◇ x = y ◇ (y ◇ z)
equation 318 := x ◇ x = y ◇ (z ◇ x)
equation 319 := x ◇ x = y ◇ (z ◇ y)
equation 320 := x ◇ x = y ◇ (z ◇ z)
equation 321 := x ◇ x = y ◇ (z ◇ w)
equation 322 := x ◇ y = x ◇ (x ◇ x)
equation 323 := x ◇ y = x ◇ (x ◇ y)
equation 324 := x ◇ y = x ◇ (x ◇ z)
equation 325 := x ◇ y = x ◇ (y ◇ x)
equation 326 := x ◇ y = x ◇ (y ◇ y)
equation 327 := x ◇ y = x ◇ (y ◇ z)
equation 328 := x ◇ y = x ◇ (z ◇ x)
equation 329 := x ◇ y = x ◇ (z ◇ y)
equation 330 := x ◇ y = x ◇ (z ◇ z)
equation 331 := x ◇ y = x ◇ (z ◇ w)
equation 332 := x ◇ y = y ◇ (x ◇ x)
equation 333 := x ◇ y = y ◇ (x ◇ y)
equation 334 := x ◇ y = y ◇ (x ◇ z)
equation 335 := x ◇ y = y ◇ (y ◇ x)
equation 336 := x ◇ y = y ◇ (y ◇ y)
equation 337 := x ◇ y = y ◇ (y ◇ z)
equation 338 := x ◇ y = y ◇ (z ◇ x)
equation 339 := x ◇ y = y ◇ (z ◇ y)
equation 340 := x ◇ y = y ◇ (z ◇ z)
equation 341 := x ◇ y = y ◇ (z ◇ w)
equation 342 := x ◇ y = z ◇ (x ◇ x)
equation 343 := x ◇ y = z ◇ (x ◇ y)
equation 344 := x ◇ y = z ◇ (x ◇ z)
equation 345 := x ◇ y = z ◇ (x ◇ w)
equation 346 := x ◇ y = z ◇ (y ◇ x)
equation 347 := x ◇ y = z ◇ (y ◇ y)
equation 348 := x ◇ y = z ◇ (y ◇ z)
equation 349 := x ◇ y = z ◇ (y ◇ w)
equation 350 := x ◇ y = z ◇ (z ◇ x)
equation 351 := x ◇ y = z ◇ (z ◇ y)
equation 352 := x ◇ y = z ◇ (z ◇ z)
equation 353 := x ◇ y = z ◇ (z ◇ w)
equation 354 := x ◇ y = z ◇ (w ◇ x)
equation 355 := x ◇ y = z ◇ (w ◇ y)
equation 356 := x ◇ y = z ◇ (w ◇ z)
equation 357 := x ◇ y = z ◇ (w ◇ w)
equation 358 := x ◇ y = z ◇ (w ◇ u)
equation 359 := x ◇ x = (x ◇ x) ◇ x
equation 360 := x ◇ x = (x ◇ x) ◇ y
equation 361 := x ◇ x = (x ◇ y) ◇ x
equation 362 := x ◇ x = (x ◇ y) ◇ y
equation 363 := x ◇ x = (x ◇ y) ◇ z
equation 364 := x ◇ x = (y ◇ x) ◇ x
equation 365 := x ◇ x = (y ◇ x) ◇ y
equation 366 := x ◇ x = (y ◇ x) ◇ z
equation 367 := x ◇ x = (y ◇ y) ◇ x
equation 368 := x ◇ x = (y ◇ y) ◇ y
equation 369 := x ◇ x = (y ◇ y) ◇ z
equation 370 := x ◇ x = (y ◇ z) ◇ x
equation 371 := x ◇ x = (y ◇ z) ◇ y
equation 372 := x ◇ x = (y ◇ z) ◇ z
equation 373 := x ◇ x = (y ◇ z) ◇ w
equation 374 := x ◇ y = (x ◇ x) ◇ x
equation 375 := x ◇ y = (x ◇ x) ◇ y
equation 376 := x ◇ y = (x ◇ x) ◇ z
equation 377 := x ◇ y = (x ◇ y) ◇ x
equation 378 := x ◇ y = (x ◇ y) ◇ y
equation 379 := x ◇ y = (x ◇ y) ◇ z
equation 380 := x ◇ y = (x ◇ z) ◇ x
-- equation 381 := x ◇ y = (x ◇ z) ◇ y
equation 382 := x ◇ y = (x ◇ z) ◇ z
equation 383 := x ◇ y = (x ◇ z) ◇ w
equation 384 := x ◇ y = (y ◇ x) ◇ x
equation 385 := x ◇ y = (y ◇ x) ◇ y
equation 386 := x ◇ y = (y ◇ x) ◇ z
-- equation 387 := x ◇ y = (y ◇ y) ◇ x
equation 388 := x ◇ y = (y ◇ y) ◇ y
equation 389 := x ◇ y = (y ◇ y) ◇ z
equation 390 := x ◇ y = (y ◇ z) ◇ x
equation 391 := x ◇ y = (y ◇ z) ◇ y
equation 392 := x ◇ y = (y ◇ z) ◇ z
equation 393 := x ◇ y = (y ◇ z) ◇ w
equation 394 := x ◇ y = (z ◇ x) ◇ x
equation 395 := x ◇ y = (z ◇ x) ◇ y
equation 396 := x ◇ y = (z ◇ x) ◇ z
equation 397 := x ◇ y = (z ◇ x) ◇ w
equation 398 := x ◇ y = (z ◇ y) ◇ x
equation 399 := x ◇ y = (z ◇ y) ◇ y
equation 400 := x ◇ y = (z ◇ y) ◇ z
equation 401 := x ◇ y = (z ◇ y) ◇ w
equation 402 := x ◇ y = (z ◇ z) ◇ x
equation 403 := x ◇ y = (z ◇ z) ◇ y
equation 404 := x ◇ y = (z ◇ z) ◇ z
equation 405 := x ◇ y = (z ◇ z) ◇ w
equation 406 := x ◇ y = (z ◇ w) ◇ x
equation 407 := x ◇ y = (z ◇ w) ◇ y
equation 408 := x ◇ y = (z ◇ w) ◇ z
equation 409 := x ◇ y = (z ◇ w) ◇ w
equation 410 := x ◇ y = (z ◇ w) ◇ u
equation 411 := x = x ◇ (x ◇ (x ◇ (x ◇ x)))
equation 412 := x = x ◇ (x ◇ (x ◇ (x ◇ y)))
equation 413 := x = x ◇ (x ◇ (x ◇ (y ◇ x)))
equation 414 := x = x ◇ (x ◇ (x ◇ (y ◇ y)))
equation 415 := x = x ◇ (x ◇ (x ◇ (y ◇ z)))
equation 416 := x = x ◇ (x ◇ (y ◇ (x ◇ x)))
equation 417 := x = x ◇ (x ◇ (y ◇ (x ◇ y)))
equation 418 := x = x ◇ (x ◇ (y ◇ (x ◇ z)))
equation 419 := x = x ◇ (x ◇ (y ◇ (y ◇ x)))
equation 420 := x = x ◇ (x ◇ (y ◇ (y ◇ y)))
equation 421 := x = x ◇ (x ◇ (y ◇ (y ◇ z)))
equation 422 := x = x ◇ (x ◇ (y ◇ (z ◇ x)))
equation 423 := x = x ◇ (x ◇ (y ◇ (z ◇ y)))
equation 424 := x = x ◇ (x ◇ (y ◇ (z ◇ z)))
equation 425 := x = x ◇ (x ◇ (y ◇ (z ◇ w)))
equation 426 := x = x ◇ (y ◇ (x ◇ (x ◇ x)))
equation 427 := x = x ◇ (y ◇ (x ◇ (x ◇ y)))
equation 428 := x = x ◇ (y ◇ (x ◇ (x ◇ z)))
equation 429 := x = x ◇ (y ◇ (x ◇ (y ◇ x)))
equation 430 := x = x ◇ (y ◇ (x ◇ (y ◇ y)))
equation 431 := x = x ◇ (y ◇ (x ◇ (y ◇ z)))
equation 432 := x = x ◇ (y ◇ (x ◇ (z ◇ x)))
equation 433 := x = x ◇ (y ◇ (x ◇ (z ◇ y)))
equation 434 := x = x ◇ (y ◇ (x ◇ (z ◇ z)))
equation 435 := x = x ◇ (y ◇ (x ◇ (z ◇ w)))
equation 436 := x = x ◇ (y ◇ (y ◇ (x ◇ x)))
equation 437 := x = x ◇ (y ◇ (y ◇ (x ◇ y)))
equation 438 := x = x ◇ (y ◇ (y ◇ (x ◇ z)))
equation 439 := x = x ◇ (y ◇ (y ◇ (y ◇ x)))
equation 440 := x = x ◇ (y ◇ (y ◇ (y ◇ y)))
equation 441 := x = x ◇ (y ◇ (y ◇ (y ◇ z)))
equation 442 := x = x ◇ (y ◇ (y ◇ (z ◇ x)))
equation 443 := x = x ◇ (y ◇ (y ◇ (z ◇ y)))
equation 444 := x = x ◇ (y ◇ (y ◇ (z ◇ z)))
equation 445 := x = x ◇ (y ◇ (y ◇ (z ◇ w)))
equation 446 := x = x ◇ (y ◇ (z ◇ (x ◇ x)))
equation 447 := x = x ◇ (y ◇ (z ◇ (x ◇ y)))
equation 448 := x = x ◇ (y ◇ (z ◇ (x ◇ z)))
equation 449 := x = x ◇ (y ◇ (z ◇ (x ◇ w)))
equation 450 := x = x ◇ (y ◇ (z ◇ (y ◇ x)))
equation 451 := x = x ◇ (y ◇ (z ◇ (y ◇ y)))
equation 452 := x = x ◇ (y ◇ (z ◇ (y ◇ z)))
equation 453 := x = x ◇ (y ◇ (z ◇ (y ◇ w)))
equation 454 := x = x ◇ (y ◇ (z ◇ (z ◇ x)))
equation 455 := x = x ◇ (y ◇ (z ◇ (z ◇ y)))
equation 456 := x = x ◇ (y ◇ (z ◇ (z ◇ z)))
equation 457 := x = x ◇ (y ◇ (z ◇ (z ◇ w)))
equation 458 := x = x ◇ (y ◇ (z ◇ (w ◇ x)))
equation 459 := x = x ◇ (y ◇ (z ◇ (w ◇ y)))
equation 460 := x = x ◇ (y ◇ (z ◇ (w ◇ z)))
equation 461 := x = x ◇ (y ◇ (z ◇ (w ◇ w)))
equation 462 := x = x ◇ (y ◇ (z ◇ (w ◇ u)))
equation 463 := x = y ◇ (x ◇ (x ◇ (x ◇ x)))
equation 464 := x = y ◇ (x ◇ (x ◇ (x ◇ y)))
equation 465 := x = y ◇ (x ◇ (x ◇ (x ◇ z)))
equation 466 := x = y ◇ (x ◇ (x ◇ (y ◇ x)))
equation 467 := x = y ◇ (x ◇ (x ◇ (y ◇ y)))
equation 468 := x = y ◇ (x ◇ (x ◇ (y ◇ z)))
equation 469 := x = y ◇ (x ◇ (x ◇ (z ◇ x)))
equation 470 := x = y ◇ (x ◇ (x ◇ (z ◇ y)))
equation 471 := x = y ◇ (x ◇ (x ◇ (z ◇ z)))
equation 472 := x = y ◇ (x ◇ (x ◇ (z ◇ w)))
equation 473 := x = y ◇ (x ◇ (y ◇ (x ◇ x)))
equation 474 := x = y ◇ (x ◇ (y ◇ (x ◇ y)))
equation 475 := x = y ◇ (x ◇ (y ◇ (x ◇ z)))
equation 476 := x = y ◇ (x ◇ (y ◇ (y ◇ x)))
equation 477 := x = y ◇ (x ◇ (y ◇ (y ◇ y)))
equation 478 := x = y ◇ (x ◇ (y ◇ (y ◇ z)))
equation 479 := x = y ◇ (x ◇ (y ◇ (z ◇ x)))
equation 480 := x = y ◇ (x ◇ (y ◇ (z ◇ y)))
equation 481 := x = y ◇ (x ◇ (y ◇ (z ◇ z)))
equation 482 := x = y ◇ (x ◇ (y ◇ (z ◇ w)))
equation 483 := x = y ◇ (x ◇ (z ◇ (x ◇ x)))
equation 484 := x = y ◇ (x ◇ (z ◇ (x ◇ y)))
equation 485 := x = y ◇ (x ◇ (z ◇ (x ◇ z)))
equation 486 := x = y ◇ (x ◇ (z ◇ (x ◇ w)))
equation 487 := x = y ◇ (x ◇ (z ◇ (y ◇ x)))
equation 488 := x = y ◇ (x ◇ (z ◇ (y ◇ y)))
equation 489 := x = y ◇ (x ◇ (z ◇ (y ◇ z)))
equation 490 := x = y ◇ (x ◇ (z ◇ (y ◇ w)))
equation 491 := x = y ◇ (x ◇ (z ◇ (z ◇ x)))
equation 492 := x = y ◇ (x ◇ (z ◇ (z ◇ y)))
equation 493 := x = y ◇ (x ◇ (z ◇ (z ◇ z)))
equation 494 := x = y ◇ (x ◇ (z ◇ (z ◇ w)))
equation 495 := x = y ◇ (x ◇ (z ◇ (w ◇ x)))
equation 496 := x = y ◇ (x ◇ (z ◇ (w ◇ y)))
equation 497 := x = y ◇ (x ◇ (z ◇ (w ◇ z)))
equation 498 := x = y ◇ (x ◇ (z ◇ (w ◇ w)))
equation 499 := x = y ◇ (x ◇ (z ◇ (w ◇ u)))
equation 500 := x = y ◇ (y ◇ (x ◇ (x ◇ x)))
equation 501 := x = y ◇ (y ◇ (x ◇ (x ◇ y)))
equation 502 := x = y ◇ (y ◇ (x ◇ (x ◇ z)))
equation 503 := x = y ◇ (y ◇ (x ◇ (y ◇ x)))
equation 504 := x = y ◇ (y ◇ (x ◇ (y ◇ y)))
equation 505 := x = y ◇ (y ◇ (x ◇ (y ◇ z)))
equation 506 := x = y ◇ (y ◇ (x ◇ (z ◇ x)))
equation 507 := x = y ◇ (y ◇ (x ◇ (z ◇ y)))
equation 508 := x = y ◇ (y ◇ (x ◇ (z ◇ z)))
equation 509 := x = y ◇ (y ◇ (x ◇ (z ◇ w)))
equation 510 := x = y ◇ (y ◇ (y ◇ (x ◇ x)))
equation 511 := x = y ◇ (y ◇ (y ◇ (x ◇ y)))
equation 512 := x = y ◇ (y ◇ (y ◇ (x ◇ z)))
equation 513 := x = y ◇ (y ◇ (y ◇ (y ◇ x)))
equation 514 := x = y ◇ (y ◇ (y ◇ (y ◇ y)))
equation 515 := x = y ◇ (y ◇ (y ◇ (y ◇ z)))
equation 516 := x = y ◇ (y ◇ (y ◇ (z ◇ x)))
equation 517 := x = y ◇ (y ◇ (y ◇ (z ◇ y)))
equation 518 := x = y ◇ (y ◇ (y ◇ (z ◇ z)))
equation 519 := x = y ◇ (y ◇ (y ◇ (z ◇ w)))
equation 520 := x = y ◇ (y ◇ (z ◇ (x ◇ x)))
equation 521 := x = y ◇ (y ◇ (z ◇ (x ◇ y)))
equation 522 := x = y ◇ (y ◇ (z ◇ (x ◇ z)))
equation 523 := x = y ◇ (y ◇ (z ◇ (x ◇ w)))
equation 524 := x = y ◇ (y ◇ (z ◇ (y ◇ x)))
equation 525 := x = y ◇ (y ◇ (z ◇ (y ◇ y)))
equation 526 := x = y ◇ (y ◇ (z ◇ (y ◇ z)))
equation 527 := x = y ◇ (y ◇ (z ◇ (y ◇ w)))
equation 528 := x = y ◇ (y ◇ (z ◇ (z ◇ x)))
equation 529 := x = y ◇ (y ◇ (z ◇ (z ◇ y)))
equation 530 := x = y ◇ (y ◇ (z ◇ (z ◇ z)))
equation 531 := x = y ◇ (y ◇ (z ◇ (z ◇ w)))
equation 532 := x = y ◇ (y ◇ (z ◇ (w ◇ x)))
equation 533 := x = y ◇ (y ◇ (z ◇ (w ◇ y)))
equation 534 := x = y ◇ (y ◇ (z ◇ (w ◇ z)))
equation 535 := x = y ◇ (y ◇ (z ◇ (w ◇ w)))
equation 536 := x = y ◇ (y ◇ (z ◇ (w ◇ u)))
equation 537 := x = y ◇ (z ◇ (x ◇ (x ◇ x)))
equation 538 := x = y ◇ (z ◇ (x ◇ (x ◇ y)))
equation 539 := x = y ◇ (z ◇ (x ◇ (x ◇ z)))
equation 540 := x = y ◇ (z ◇ (x ◇ (x ◇ w)))
equation 541 := x = y ◇ (z ◇ (x ◇ (y ◇ x)))
equation 542 := x = y ◇ (z ◇ (x ◇ (y ◇ y)))
equation 543 := x = y ◇ (z ◇ (x ◇ (y ◇ z)))
equation 544 := x = y ◇ (z ◇ (x ◇ (y ◇ w)))
equation 545 := x = y ◇ (z ◇ (x ◇ (z ◇ x)))
equation 546 := x = y ◇ (z ◇ (x ◇ (z ◇ y)))
equation 547 := x = y ◇ (z ◇ (x ◇ (z ◇ z)))
equation 548 := x = y ◇ (z ◇ (x ◇ (z ◇ w)))
equation 549 := x = y ◇ (z ◇ (x ◇ (w ◇ x)))
equation 550 := x = y ◇ (z ◇ (x ◇ (w ◇ y)))
equation 551 := x = y ◇ (z ◇ (x ◇ (w ◇ z)))
equation 552 := x = y ◇ (z ◇ (x ◇ (w ◇ w)))
equation 553 := x = y ◇ (z ◇ (x ◇ (w ◇ u)))
equation 554 := x = y ◇ (z ◇ (y ◇ (x ◇ x)))
equation 555 := x = y ◇ (z ◇ (y ◇ (x ◇ y)))
equation 556 := x = y ◇ (z ◇ (y ◇ (x ◇ z)))
equation 557 := x = y ◇ (z ◇ (y ◇ (x ◇ w)))
equation 558 := x = y ◇ (z ◇ (y ◇ (y ◇ x)))
equation 559 := x = y ◇ (z ◇ (y ◇ (y ◇ y)))
equation 560 := x = y ◇ (z ◇ (y ◇ (y ◇ z)))
equation 561 := x = y ◇ (z ◇ (y ◇ (y ◇ w)))
equation 562 := x = y ◇ (z ◇ (y ◇ (z ◇ x)))
equation 563 := x = y ◇ (z ◇ (y ◇ (z ◇ y)))
equation 564 := x = y ◇ (z ◇ (y ◇ (z ◇ z)))
equation 565 := x = y ◇ (z ◇ (y ◇ (z ◇ w)))
equation 566 := x = y ◇ (z ◇ (y ◇ (w ◇ x)))
equation 567 := x = y ◇ (z ◇ (y ◇ (w ◇ y)))
equation 568 := x = y ◇ (z ◇ (y ◇ (w ◇ z)))
equation 569 := x = y ◇ (z ◇ (y ◇ (w ◇ w)))
equation 570 := x = y ◇ (z ◇ (y ◇ (w ◇ u)))
equation 571 := x = y ◇ (z ◇ (z ◇ (x ◇ x)))
equation 572 := x = y ◇ (z ◇ (z ◇ (x ◇ y)))
equation 573 := x = y ◇ (z ◇ (z ◇ (x ◇ z)))
equation 574 := x = y ◇ (z ◇ (z ◇ (x ◇ w)))
equation 575 := x = y ◇ (z ◇ (z ◇ (y ◇ x)))
equation 576 := x = y ◇ (z ◇ (z ◇ (y ◇ y)))
equation 577 := x = y ◇ (z ◇ (z ◇ (y ◇ z)))
equation 578 := x = y ◇ (z ◇ (z ◇ (y ◇ w)))
equation 579 := x = y ◇ (z ◇ (z ◇ (z ◇ x)))
equation 580 := x = y ◇ (z ◇ (z ◇ (z ◇ y)))
equation 581 := x = y ◇ (z ◇ (z ◇ (z ◇ z)))
equation 582 := x = y ◇ (z ◇ (z ◇ (z ◇ w)))
equation 583 := x = y ◇ (z ◇ (z ◇ (w ◇ x)))
equation 584 := x = y ◇ (z ◇ (z ◇ (w ◇ y)))
equation 585 := x = y ◇ (z ◇ (z ◇ (w ◇ z)))
equation 586 := x = y ◇ (z ◇ (z ◇ (w ◇ w)))
equation 587 := x = y ◇ (z ◇ (z ◇ (w ◇ u)))
equation 588 := x = y ◇ (z ◇ (w ◇ (x ◇ x)))
equation 589 := x = y ◇ (z ◇ (w ◇ (x ◇ y)))
equation 590 := x = y ◇ (z ◇ (w ◇ (x ◇ z)))
equation 591 := x = y ◇ (z ◇ (w ◇ (x ◇ w)))
equation 592 := x = y ◇ (z ◇ (w ◇ (x ◇ u)))
equation 593 := x = y ◇ (z ◇ (w ◇ (y ◇ x)))
equation 594 := x = y ◇ (z ◇ (w ◇ (y ◇ y)))
equation 595 := x = y ◇ (z ◇ (w ◇ (y ◇ z)))
equation 596 := x = y ◇ (z ◇ (w ◇ (y ◇ w)))
equation 597 := x = y ◇ (z ◇ (w ◇ (y ◇ u)))
equation 598 := x = y ◇ (z ◇ (w ◇ (z ◇ x)))
equation 599 := x = y ◇ (z ◇ (w ◇ (z ◇ y)))
equation 600 := x = y ◇ (z ◇ (w ◇ (z ◇ z)))
equation 601 := x = y ◇ (z ◇ (w ◇ (z ◇ w)))
equation 602 := x = y ◇ (z ◇ (w ◇ (z ◇ u)))
equation 603 := x = y ◇ (z ◇ (w ◇ (w ◇ x)))
equation 604 := x = y ◇ (z ◇ (w ◇ (w ◇ y)))
equation 605 := x = y ◇ (z ◇ (w ◇ (w ◇ z)))
equation 606 := x = y ◇ (z ◇ (w ◇ (w ◇ w)))
equation 607 := x = y ◇ (z ◇ (w ◇ (w ◇ u)))
equation 608 := x = y ◇ (z ◇ (w ◇ (u ◇ x)))
equation 609 := x = y ◇ (z ◇ (w ◇ (u ◇ y)))
equation 610 := x = y ◇ (z ◇ (w ◇ (u ◇ z)))
equation 611 := x = y ◇ (z ◇ (w ◇ (u ◇ w)))
equation 612 := x = y ◇ (z ◇ (w ◇ (u ◇ u)))
equation 613 := x = y ◇ (z ◇ (w ◇ (u ◇ v)))
equation 614 := x = x ◇ (x ◇ ((x ◇ x) ◇ x))
equation 615 := x = x ◇ (x ◇ ((x ◇ x) ◇ y))
equation 616 := x = x ◇ (x ◇ ((x ◇ y) ◇ x))
equation 617 := x = x ◇ (x ◇ ((x ◇ y) ◇ y))
equation 618 := x = x ◇ (x ◇ ((x ◇ y) ◇ z))
equation 619 := x = x ◇ (x ◇ ((y ◇ x) ◇ x))
equation 620 := x = x ◇ (x ◇ ((y ◇ x) ◇ y))
equation 621 := x = x ◇ (x ◇ ((y ◇ x) ◇ z))
equation 622 := x = x ◇ (x ◇ ((y ◇ y) ◇ x))
equation 623 := x = x ◇ (x ◇ ((y ◇ y) ◇ y))
equation 624 := x = x ◇ (x ◇ ((y ◇ y) ◇ z))
equation 625 := x = x ◇ (x ◇ ((y ◇ z) ◇ x))
equation 626 := x = x ◇ (x ◇ ((y ◇ z) ◇ y))
equation 627 := x = x ◇ (x ◇ ((y ◇ z) ◇ z))
equation 628 := x = x ◇ (x ◇ ((y ◇ z) ◇ w))
equation 629 := x = x ◇ (y ◇ ((x ◇ x) ◇ x))
equation 630 := x = x ◇ (y ◇ ((x ◇ x) ◇ y))
equation 631 := x = x ◇ (y ◇ ((x ◇ x) ◇ z))
equation 632 := x = x ◇ (y ◇ ((x ◇ y) ◇ x))
equation 633 := x = x ◇ (y ◇ ((x ◇ y) ◇ y))
equation 634 := x = x ◇ (y ◇ ((x ◇ y) ◇ z))
equation 635 := x = x ◇ (y ◇ ((x ◇ z) ◇ x))
equation 636 := x = x ◇ (y ◇ ((x ◇ z) ◇ y))
equation 637 := x = x ◇ (y ◇ ((x ◇ z) ◇ z))
equation 638 := x = x ◇ (y ◇ ((x ◇ z) ◇ w))
equation 639 := x = x ◇ (y ◇ ((y ◇ x) ◇ x))
equation 640 := x = x ◇ (y ◇ ((y ◇ x) ◇ y))
equation 641 := x = x ◇ (y ◇ ((y ◇ x) ◇ z))
equation 642 := x = x ◇ (y ◇ ((y ◇ y) ◇ x))
equation 643 := x = x ◇ (y ◇ ((y ◇ y) ◇ y))
equation 644 := x = x ◇ (y ◇ ((y ◇ y) ◇ z))
equation 645 := x = x ◇ (y ◇ ((y ◇ z) ◇ x))
equation 646 := x = x ◇ (y ◇ ((y ◇ z) ◇ y))
equation 647 := x = x ◇ (y ◇ ((y ◇ z) ◇ z))
equation 648 := x = x ◇ (y ◇ ((y ◇ z) ◇ w))
equation 649 := x = x ◇ (y ◇ ((z ◇ x) ◇ x))
equation 650 := x = x ◇ (y ◇ ((z ◇ x) ◇ y))
equation 651 := x = x ◇ (y ◇ ((z ◇ x) ◇ z))
equation 652 := x = x ◇ (y ◇ ((z ◇ x) ◇ w))
equation 653 := x = x ◇ (y ◇ ((z ◇ y) ◇ x))
equation 654 := x = x ◇ (y ◇ ((z ◇ y) ◇ y))
equation 655 := x = x ◇ (y ◇ ((z ◇ y) ◇ z))
equation 656 := x = x ◇ (y ◇ ((z ◇ y) ◇ w))
equation 657 := x = x ◇ (y ◇ ((z ◇ z) ◇ x))
equation 658 := x = x ◇ (y ◇ ((z ◇ z) ◇ y))
equation 659 := x = x ◇ (y ◇ ((z ◇ z) ◇ z))
equation 660 := x = x ◇ (y ◇ ((z ◇ z) ◇ w))
equation 661 := x = x ◇ (y ◇ ((z ◇ w) ◇ x))
equation 662 := x = x ◇ (y ◇ ((z ◇ w) ◇ y))
equation 663 := x = x ◇ (y ◇ ((z ◇ w) ◇ z))
equation 664 := x = x ◇ (y ◇ ((z ◇ w) ◇ w))
equation 665 := x = x ◇ (y ◇ ((z ◇ w) ◇ u))
equation 666 := x = y ◇ (x ◇ ((x ◇ x) ◇ x))
equation 667 := x = y ◇ (x ◇ ((x ◇ x) ◇ y))
equation 668 := x = y ◇ (x ◇ ((x ◇ x) ◇ z))
equation 669 := x = y ◇ (x ◇ ((x ◇ y) ◇ x))
equation 670 := x = y ◇ (x ◇ ((x ◇ y) ◇ y))
equation 671 := x = y ◇ (x ◇ ((x ◇ y) ◇ z))
equation 672 := x = y ◇ (x ◇ ((x ◇ z) ◇ x))
equation 673 := x = y ◇ (x ◇ ((x ◇ z) ◇ y))
equation 674 := x = y ◇ (x ◇ ((x ◇ z) ◇ z))
equation 675 := x = y ◇ (x ◇ ((x ◇ z) ◇ w))
equation 676 := x = y ◇ (x ◇ ((y ◇ x) ◇ x))
equation 677 := x = y ◇ (x ◇ ((y ◇ x) ◇ y))
equation 678 := x = y ◇ (x ◇ ((y ◇ x) ◇ z))
equation 679 := x = y ◇ (x ◇ ((y ◇ y) ◇ x))
equation 680 := x = y ◇ (x ◇ ((y ◇ y) ◇ y))
equation 681 := x = y ◇ (x ◇ ((y ◇ y) ◇ z))
equation 682 := x = y ◇ (x ◇ ((y ◇ z) ◇ x))
equation 683 := x = y ◇ (x ◇ ((y ◇ z) ◇ y))
equation 684 := x = y ◇ (x ◇ ((y ◇ z) ◇ z))
equation 685 := x = y ◇ (x ◇ ((y ◇ z) ◇ w))
equation 686 := x = y ◇ (x ◇ ((z ◇ x) ◇ x))
equation 687 := x = y ◇ (x ◇ ((z ◇ x) ◇ y))
equation 688 := x = y ◇ (x ◇ ((z ◇ x) ◇ z))
equation 689 := x = y ◇ (x ◇ ((z ◇ x) ◇ w))
equation 690 := x = y ◇ (x ◇ ((z ◇ y) ◇ x))
equation 691 := x = y ◇ (x ◇ ((z ◇ y) ◇ y))
equation 692 := x = y ◇ (x ◇ ((z ◇ y) ◇ z))
equation 693 := x = y ◇ (x ◇ ((z ◇ y) ◇ w))
equation 694 := x = y ◇ (x ◇ ((z ◇ z) ◇ x))
equation 695 := x = y ◇ (x ◇ ((z ◇ z) ◇ y))
equation 696 := x = y ◇ (x ◇ ((z ◇ z) ◇ z))
equation 697 := x = y ◇ (x ◇ ((z ◇ z) ◇ w))
equation 698 := x = y ◇ (x ◇ ((z ◇ w) ◇ x))
equation 699 := x = y ◇ (x ◇ ((z ◇ w) ◇ y))
equation 700 := x = y ◇ (x ◇ ((z ◇ w) ◇ z))
equation 701 := x = y ◇ (x ◇ ((z ◇ w) ◇ w))
equation 702 := x = y ◇ (x ◇ ((z ◇ w) ◇ u))
equation 703 := x = y ◇ (y ◇ ((x ◇ x) ◇ x))
equation 704 := x = y ◇ (y ◇ ((x ◇ x) ◇ y))
equation 705 := x = y ◇ (y ◇ ((x ◇ x) ◇ z))
equation 706 := x = y ◇ (y ◇ ((x ◇ y) ◇ x))
equation 707 := x = y ◇ (y ◇ ((x ◇ y) ◇ y))
equation 708 := x = y ◇ (y ◇ ((x ◇ y) ◇ z))
equation 709 := x = y ◇ (y ◇ ((x ◇ z) ◇ x))
equation 710 := x = y ◇ (y ◇ ((x ◇ z) ◇ y))
equation 711 := x = y ◇ (y ◇ ((x ◇ z) ◇ z))
equation 712 := x = y ◇ (y ◇ ((x ◇ z) ◇ w))
equation 713 := x = y ◇ (y ◇ ((y ◇ x) ◇ x))
equation 714 := x = y ◇ (y ◇ ((y ◇ x) ◇ y))
equation 715 := x = y ◇ (y ◇ ((y ◇ x) ◇ z))
equation 716 := x = y ◇ (y ◇ ((y ◇ y) ◇ x))
equation 717 := x = y ◇ (y ◇ ((y ◇ y) ◇ y))
equation 718 := x = y ◇ (y ◇ ((y ◇ y) ◇ z))
equation 719 := x = y ◇ (y ◇ ((y ◇ z) ◇ x))
equation 720 := x = y ◇ (y ◇ ((y ◇ z) ◇ y))
equation 721 := x = y ◇ (y ◇ ((y ◇ z) ◇ z))
equation 722 := x = y ◇ (y ◇ ((y ◇ z) ◇ w))
equation 723 := x = y ◇ (y ◇ ((z ◇ x) ◇ x))
equation 724 := x = y ◇ (y ◇ ((z ◇ x) ◇ y))
equation 725 := x = y ◇ (y ◇ ((z ◇ x) ◇ z))
equation 726 := x = y ◇ (y ◇ ((z ◇ x) ◇ w))
equation 727 := x = y ◇ (y ◇ ((z ◇ y) ◇ x))
equation 728 := x = y ◇ (y ◇ ((z ◇ y) ◇ y))
equation 729 := x = y ◇ (y ◇ ((z ◇ y) ◇ z))
equation 730 := x = y ◇ (y ◇ ((z ◇ y) ◇ w))
equation 731 := x = y ◇ (y ◇ ((z ◇ z) ◇ x))
equation 732 := x = y ◇ (y ◇ ((z ◇ z) ◇ y))
equation 733 := x = y ◇ (y ◇ ((z ◇ z) ◇ z))
equation 734 := x = y ◇ (y ◇ ((z ◇ z) ◇ w))
equation 735 := x = y ◇ (y ◇ ((z ◇ w) ◇ x))
equation 736 := x = y ◇ (y ◇ ((z ◇ w) ◇ y))
equation 737 := x = y ◇ (y ◇ ((z ◇ w) ◇ z))
equation 738 := x = y ◇ (y ◇ ((z ◇ w) ◇ w))
equation 739 := x = y ◇ (y ◇ ((z ◇ w) ◇ u))
equation 740 := x = y ◇ (z ◇ ((x ◇ x) ◇ x))
equation 741 := x = y ◇ (z ◇ ((x ◇ x) ◇ y))
equation 742 := x = y ◇ (z ◇ ((x ◇ x) ◇ z))
equation 743 := x = y ◇ (z ◇ ((x ◇ x) ◇ w))
equation 744 := x = y ◇ (z ◇ ((x ◇ y) ◇ x))
equation 745 := x = y ◇ (z ◇ ((x ◇ y) ◇ y))
equation 746 := x = y ◇ (z ◇ ((x ◇ y) ◇ z))
equation 747 := x = y ◇ (z ◇ ((x ◇ y) ◇ w))
equation 748 := x = y ◇ (z ◇ ((x ◇ z) ◇ x))
equation 749 := x = y ◇ (z ◇ ((x ◇ z) ◇ y))
equation 750 := x = y ◇ (z ◇ ((x ◇ z) ◇ z))
equation 751 := x = y ◇ (z ◇ ((x ◇ z) ◇ w))
equation 752 := x = y ◇ (z ◇ ((x ◇ w) ◇ x))
equation 753 := x = y ◇ (z ◇ ((x ◇ w) ◇ y))
equation 754 := x = y ◇ (z ◇ ((x ◇ w) ◇ z))
equation 755 := x = y ◇ (z ◇ ((x ◇ w) ◇ w))
equation 756 := x = y ◇ (z ◇ ((x ◇ w) ◇ u))
equation 757 := x = y ◇ (z ◇ ((y ◇ x) ◇ x))
equation 758 := x = y ◇ (z ◇ ((y ◇ x) ◇ y))
equation 759 := x = y ◇ (z ◇ ((y ◇ x) ◇ z))
equation 760 := x = y ◇ (z ◇ ((y ◇ x) ◇ w))
equation 761 := x = y ◇ (z ◇ ((y ◇ y) ◇ x))
equation 762 := x = y ◇ (z ◇ ((y ◇ y) ◇ y))
equation 763 := x = y ◇ (z ◇ ((y ◇ y) ◇ z))
equation 764 := x = y ◇ (z ◇ ((y ◇ y) ◇ w))
equation 765 := x = y ◇ (z ◇ ((y ◇ z) ◇ x))
equation 766 := x = y ◇ (z ◇ ((y ◇ z) ◇ y))
equation 767 := x = y ◇ (z ◇ ((y ◇ z) ◇ z))
equation 768 := x = y ◇ (z ◇ ((y ◇ z) ◇ w))
equation 769 := x = y ◇ (z ◇ ((y ◇ w) ◇ x))
equation 770 := x = y ◇ (z ◇ ((y ◇ w) ◇ y))
equation 771 := x = y ◇ (z ◇ ((y ◇ w) ◇ z))
equation 772 := x = y ◇ (z ◇ ((y ◇ w) ◇ w))
equation 773 := x = y ◇ (z ◇ ((y ◇ w) ◇ u))
equation 774 := x = y ◇ (z ◇ ((z ◇ x) ◇ x))
equation 775 := x = y ◇ (z ◇ ((z ◇ x) ◇ y))
equation 776 := x = y ◇ (z ◇ ((z ◇ x) ◇ z))
equation 777 := x = y ◇ (z ◇ ((z ◇ x) ◇ w))
equation 778 := x = y ◇ (z ◇ ((z ◇ y) ◇ x))
equation 779 := x = y ◇ (z ◇ ((z ◇ y) ◇ y))
equation 780 := x = y ◇ (z ◇ ((z ◇ y) ◇ z))
equation 781 := x = y ◇ (z ◇ ((z ◇ y) ◇ w))
equation 782 := x = y ◇ (z ◇ ((z ◇ z) ◇ x))
equation 783 := x = y ◇ (z ◇ ((z ◇ z) ◇ y))
equation 784 := x = y ◇ (z ◇ ((z ◇ z) ◇ z))
equation 785 := x = y ◇ (z ◇ ((z ◇ z) ◇ w))
equation 786 := x = y ◇ (z ◇ ((z ◇ w) ◇ x))
equation 787 := x = y ◇ (z ◇ ((z ◇ w) ◇ y))
equation 788 := x = y ◇ (z ◇ ((z ◇ w) ◇ z))
equation 789 := x = y ◇ (z ◇ ((z ◇ w) ◇ w))
equation 790 := x = y ◇ (z ◇ ((z ◇ w) ◇ u))
equation 791 := x = y ◇ (z ◇ ((w ◇ x) ◇ x))
equation 792 := x = y ◇ (z ◇ ((w ◇ x) ◇ y))
equation 793 := x = y ◇ (z ◇ ((w ◇ x) ◇ z))
equation 794 := x = y ◇ (z ◇ ((w ◇ x) ◇ w))
equation 795 := x = y ◇ (z ◇ ((w ◇ x) ◇ u))
equation 796 := x = y ◇ (z ◇ ((w ◇ y) ◇ x))
equation 797 := x = y ◇ (z ◇ ((w ◇ y) ◇ y))
equation 798 := x = y ◇ (z ◇ ((w ◇ y) ◇ z))
equation 799 := x = y ◇ (z ◇ ((w ◇ y) ◇ w))
equation 800 := x = y ◇ (z ◇ ((w ◇ y) ◇ u))
equation 801 := x = y ◇ (z ◇ ((w ◇ z) ◇ x))
equation 802 := x = y ◇ (z ◇ ((w ◇ z) ◇ y))
equation 803 := x = y ◇ (z ◇ ((w ◇ z) ◇ z))
equation 804 := x = y ◇ (z ◇ ((w ◇ z) ◇ w))
equation 805 := x = y ◇ (z ◇ ((w ◇ z) ◇ u))
equation 806 := x = y ◇ (z ◇ ((w ◇ w) ◇ x))
equation 807 := x = y ◇ (z ◇ ((w ◇ w) ◇ y))
equation 808 := x = y ◇ (z ◇ ((w ◇ w) ◇ z))
equation 809 := x = y ◇ (z ◇ ((w ◇ w) ◇ w))
equation 810 := x = y ◇ (z ◇ ((w ◇ w) ◇ u))
equation 811 := x = y ◇ (z ◇ ((w ◇ u) ◇ x))
equation 812 := x = y ◇ (z ◇ ((w ◇ u) ◇ y))
equation 813 := x = y ◇ (z ◇ ((w ◇ u) ◇ z))
equation 814 := x = y ◇ (z ◇ ((w ◇ u) ◇ w))
equation 815 := x = y ◇ (z ◇ ((w ◇ u) ◇ u))
equation 816 := x = y ◇ (z ◇ ((w ◇ u) ◇ v))
equation 817 := x = x ◇ ((x ◇ x) ◇ (x ◇ x))
equation 818 := x = x ◇ ((x ◇ x) ◇ (x ◇ y))
equation 819 := x = x ◇ ((x ◇ x) ◇ (y ◇ x))
equation 820 := x = x ◇ ((x ◇ x) ◇ (y ◇ y))
equation 821 := x = x ◇ ((x ◇ x) ◇ (y ◇ z))
equation 822 := x = x ◇ ((x ◇ y) ◇ (x ◇ x))
equation 823 := x = x ◇ ((x ◇ y) ◇ (x ◇ y))
equation 824 := x = x ◇ ((x ◇ y) ◇ (x ◇ z))
equation 825 := x = x ◇ ((x ◇ y) ◇ (y ◇ x))
equation 826 := x = x ◇ ((x ◇ y) ◇ (y ◇ y))
equation 827 := x = x ◇ ((x ◇ y) ◇ (y ◇ z))
equation 828 := x = x ◇ ((x ◇ y) ◇ (z ◇ x))
equation 829 := x = x ◇ ((x ◇ y) ◇ (z ◇ y))
equation 830 := x = x ◇ ((x ◇ y) ◇ (z ◇ z))
equation 831 := x = x ◇ ((x ◇ y) ◇ (z ◇ w))
equation 832 := x = x ◇ ((y ◇ x) ◇ (x ◇ x))
equation 833 := x = x ◇ ((y ◇ x) ◇ (x ◇ y))
equation 834 := x = x ◇ ((y ◇ x) ◇ (x ◇ z))
equation 835 := x = x ◇ ((y ◇ x) ◇ (y ◇ x))
equation 836 := x = x ◇ ((y ◇ x) ◇ (y ◇ y))
equation 837 := x = x ◇ ((y ◇ x) ◇ (y ◇ z))
equation 838 := x = x ◇ ((y ◇ x) ◇ (z ◇ x))
equation 839 := x = x ◇ ((y ◇ x) ◇ (z ◇ y))
equation 840 := x = x ◇ ((y ◇ x) ◇ (z ◇ z))
equation 841 := x = x ◇ ((y ◇ x) ◇ (z ◇ w))
equation 842 := x = x ◇ ((y ◇ y) ◇ (x ◇ x))
equation 843 := x = x ◇ ((y ◇ y) ◇ (x ◇ y))
equation 844 := x = x ◇ ((y ◇ y) ◇ (x ◇ z))
equation 845 := x = x ◇ ((y ◇ y) ◇ (y ◇ x))
equation 846 := x = x ◇ ((y ◇ y) ◇ (y ◇ y))
equation 847 := x = x ◇ ((y ◇ y) ◇ (y ◇ z))
equation 848 := x = x ◇ ((y ◇ y) ◇ (z ◇ x))
equation 849 := x = x ◇ ((y ◇ y) ◇ (z ◇ y))
equation 850 := x = x ◇ ((y ◇ y) ◇ (z ◇ z))
equation 851 := x = x ◇ ((y ◇ y) ◇ (z ◇ w))
equation 852 := x = x ◇ ((y ◇ z) ◇ (x ◇ x))
equation 853 := x = x ◇ ((y ◇ z) ◇ (x ◇ y))
equation 854 := x = x ◇ ((y ◇ z) ◇ (x ◇ z))
equation 855 := x = x ◇ ((y ◇ z) ◇ (x ◇ w))
equation 856 := x = x ◇ ((y ◇ z) ◇ (y ◇ x))
equation 857 := x = x ◇ ((y ◇ z) ◇ (y ◇ y))
equation 858 := x = x ◇ ((y ◇ z) ◇ (y ◇ z))
equation 859 := x = x ◇ ((y ◇ z) ◇ (y ◇ w))
equation 860 := x = x ◇ ((y ◇ z) ◇ (z ◇ x))
equation 861 := x = x ◇ ((y ◇ z) ◇ (z ◇ y))
equation 862 := x = x ◇ ((y ◇ z) ◇ (z ◇ z))
equation 863 := x = x ◇ ((y ◇ z) ◇ (z ◇ w))
equation 864 := x = x ◇ ((y ◇ z) ◇ (w ◇ x))
equation 865 := x = x ◇ ((y ◇ z) ◇ (w ◇ y))
equation 866 := x = x ◇ ((y ◇ z) ◇ (w ◇ z))
equation 867 := x = x ◇ ((y ◇ z) ◇ (w ◇ w))
equation 868 := x = x ◇ ((y ◇ z) ◇ (w ◇ u))
equation 869 := x = y ◇ ((x ◇ x) ◇ (x ◇ x))
equation 870 := x = y ◇ ((x ◇ x) ◇ (x ◇ y))
equation 871 := x = y ◇ ((x ◇ x) ◇ (x ◇ z))
equation 872 := x = y ◇ ((x ◇ x) ◇ (y ◇ x))
equation 873 := x = y ◇ ((x ◇ x) ◇ (y ◇ y))
equation 874 := x = y ◇ ((x ◇ x) ◇ (y ◇ z))
equation 875 := x = y ◇ ((x ◇ x) ◇ (z ◇ x))
equation 876 := x = y ◇ ((x ◇ x) ◇ (z ◇ y))
equation 877 := x = y ◇ ((x ◇ x) ◇ (z ◇ z))
equation 878 := x = y ◇ ((x ◇ x) ◇ (z ◇ w))
equation 879 := x = y ◇ ((x ◇ y) ◇ (x ◇ x))
equation 880 := x = y ◇ ((x ◇ y) ◇ (x ◇ y))
equation 881 := x = y ◇ ((x ◇ y) ◇ (x ◇ z))
equation 882 := x = y ◇ ((x ◇ y) ◇ (y ◇ x))
equation 883 := x = y ◇ ((x ◇ y) ◇ (y ◇ y))
equation 884 := x = y ◇ ((x ◇ y) ◇ (y ◇ z))
equation 885 := x = y ◇ ((x ◇ y) ◇ (z ◇ x))
equation 886 := x = y ◇ ((x ◇ y) ◇ (z ◇ y))
equation 887 := x = y ◇ ((x ◇ y) ◇ (z ◇ z))
equation 888 := x = y ◇ ((x ◇ y) ◇ (z ◇ w))
equation 889 := x = y ◇ ((x ◇ z) ◇ (x ◇ x))
equation 890 := x = y ◇ ((x ◇ z) ◇ (x ◇ y))
equation 891 := x = y ◇ ((x ◇ z) ◇ (x ◇ z))
equation 892 := x = y ◇ ((x ◇ z) ◇ (x ◇ w))
equation 893 := x = y ◇ ((x ◇ z) ◇ (y ◇ x))
equation 894 := x = y ◇ ((x ◇ z) ◇ (y ◇ y))
equation 895 := x = y ◇ ((x ◇ z) ◇ (y ◇ z))
equation 896 := x = y ◇ ((x ◇ z) ◇ (y ◇ w))
equation 897 := x = y ◇ ((x ◇ z) ◇ (z ◇ x))
equation 898 := x = y ◇ ((x ◇ z) ◇ (z ◇ y))
equation 899 := x = y ◇ ((x ◇ z) ◇ (z ◇ z))
equation 900 := x = y ◇ ((x ◇ z) ◇ (z ◇ w))
equation 901 := x = y ◇ ((x ◇ z) ◇ (w ◇ x))
equation 902 := x = y ◇ ((x ◇ z) ◇ (w ◇ y))
equation 903 := x = y ◇ ((x ◇ z) ◇ (w ◇ z))
equation 904 := x = y ◇ ((x ◇ z) ◇ (w ◇ w))
equation 905 := x = y ◇ ((x ◇ z) ◇ (w ◇ u))
equation 906 := x = y ◇ ((y ◇ x) ◇ (x ◇ x))
equation 907 := x = y ◇ ((y ◇ x) ◇ (x ◇ y))
equation 908 := x = y ◇ ((y ◇ x) ◇ (x ◇ z))
equation 909 := x = y ◇ ((y ◇ x) ◇ (y ◇ x))
equation 910 := x = y ◇ ((y ◇ x) ◇ (y ◇ y))
equation 911 := x = y ◇ ((y ◇ x) ◇ (y ◇ z))
equation 912 := x = y ◇ ((y ◇ x) ◇ (z ◇ x))
equation 913 := x = y ◇ ((y ◇ x) ◇ (z ◇ y))
equation 914 := x = y ◇ ((y ◇ x) ◇ (z ◇ z))
equation 915 := x = y ◇ ((y ◇ x) ◇ (z ◇ w))
equation 916 := x = y ◇ ((y ◇ y) ◇ (x ◇ x))
equation 917 := x = y ◇ ((y ◇ y) ◇ (x ◇ y))
equation 918 := x = y ◇ ((y ◇ y) ◇ (x ◇ z))
equation 919 := x = y ◇ ((y ◇ y) ◇ (y ◇ x))
equation 920 := x = y ◇ ((y ◇ y) ◇ (y ◇ y))
equation 921 := x = y ◇ ((y ◇ y) ◇ (y ◇ z))
equation 922 := x = y ◇ ((y ◇ y) ◇ (z ◇ x))
equation 923 := x = y ◇ ((y ◇ y) ◇ (z ◇ y))
equation 924 := x = y ◇ ((y ◇ y) ◇ (z ◇ z))
equation 925 := x = y ◇ ((y ◇ y) ◇ (z ◇ w))
equation 926 := x = y ◇ ((y ◇ z) ◇ (x ◇ x))
equation 927 := x = y ◇ ((y ◇ z) ◇ (x ◇ y))
equation 928 := x = y ◇ ((y ◇ z) ◇ (x ◇ z))
equation 929 := x = y ◇ ((y ◇ z) ◇ (x ◇ w))
equation 930 := x = y ◇ ((y ◇ z) ◇ (y ◇ x))
equation 931 := x = y ◇ ((y ◇ z) ◇ (y ◇ y))
equation 932 := x = y ◇ ((y ◇ z) ◇ (y ◇ z))
equation 933 := x = y ◇ ((y ◇ z) ◇ (y ◇ w))
equation 934 := x = y ◇ ((y ◇ z) ◇ (z ◇ x))
equation 935 := x = y ◇ ((y ◇ z) ◇ (z ◇ y))
equation 936 := x = y ◇ ((y ◇ z) ◇ (z ◇ z))
equation 937 := x = y ◇ ((y ◇ z) ◇ (z ◇ w))
equation 938 := x = y ◇ ((y ◇ z) ◇ (w ◇ x))
equation 939 := x = y ◇ ((y ◇ z) ◇ (w ◇ y))
equation 940 := x = y ◇ ((y ◇ z) ◇ (w ◇ z))
equation 941 := x = y ◇ ((y ◇ z) ◇ (w ◇ w))
equation 942 := x = y ◇ ((y ◇ z) ◇ (w ◇ u))
equation 943 := x = y ◇ ((z ◇ x) ◇ (x ◇ x))
equation 944 := x = y ◇ ((z ◇ x) ◇ (x ◇ y))
equation 945 := x = y ◇ ((z ◇ x) ◇ (x ◇ z))
equation 946 := x = y ◇ ((z ◇ x) ◇ (x ◇ w))
equation 947 := x = y ◇ ((z ◇ x) ◇ (y ◇ x))
equation 948 := x = y ◇ ((z ◇ x) ◇ (y ◇ y))
equation 949 := x = y ◇ ((z ◇ x) ◇ (y ◇ z))
equation 950 := x = y ◇ ((z ◇ x) ◇ (y ◇ w))
equation 951 := x = y ◇ ((z ◇ x) ◇ (z ◇ x))
equation 952 := x = y ◇ ((z ◇ x) ◇ (z ◇ y))
-- equation 953 := x = y ◇ ((z ◇ x) ◇ (z ◇ z))
equation 954 := x = y ◇ ((z ◇ x) ◇ (z ◇ w))
equation 955 := x = y ◇ ((z ◇ x) ◇ (w ◇ x))
equation 956 := x = y ◇ ((z ◇ x) ◇ (w ◇ y))
equation 957 := x = y ◇ ((z ◇ x) ◇ (w ◇ z))
equation 958 := x = y ◇ ((z ◇ x) ◇ (w ◇ w))
equation 959 := x = y ◇ ((z ◇ x) ◇ (w ◇ u))
equation 960 := x = y ◇ ((z ◇ y) ◇ (x ◇ x))
equation 961 := x = y ◇ ((z ◇ y) ◇ (x ◇ y))
equation 962 := x = y ◇ ((z ◇ y) ◇ (x ◇ z))
equation 963 := x = y ◇ ((z ◇ y) ◇ (x ◇ w))
equation 964 := x = y ◇ ((z ◇ y) ◇ (y ◇ x))
equation 965 := x = y ◇ ((z ◇ y) ◇ (y ◇ y))
equation 966 := x = y ◇ ((z ◇ y) ◇ (y ◇ z))
equation 967 := x = y ◇ ((z ◇ y) ◇ (y ◇ w))
equation 968 := x = y ◇ ((z ◇ y) ◇ (z ◇ x))
equation 969 := x = y ◇ ((z ◇ y) ◇ (z ◇ y))
equation 970 := x = y ◇ ((z ◇ y) ◇ (z ◇ z))
equation 971 := x = y ◇ ((z ◇ y) ◇ (z ◇ w))
equation 972 := x = y ◇ ((z ◇ y) ◇ (w ◇ x))
equation 973 := x = y ◇ ((z ◇ y) ◇ (w ◇ y))
equation 974 := x = y ◇ ((z ◇ y) ◇ (w ◇ z))
equation 975 := x = y ◇ ((z ◇ y) ◇ (w ◇ w))
equation 976 := x = y ◇ ((z ◇ y) ◇ (w ◇ u))
equation 977 := x = y ◇ ((z ◇ z) ◇ (x ◇ x))
equation 978 := x = y ◇ ((z ◇ z) ◇ (x ◇ y))
equation 979 := x = y ◇ ((z ◇ z) ◇ (x ◇ z))
equation 980 := x = y ◇ ((z ◇ z) ◇ (x ◇ w))
equation 981 := x = y ◇ ((z ◇ z) ◇ (y ◇ x))
equation 982 := x = y ◇ ((z ◇ z) ◇ (y ◇ y))
equation 983 := x = y ◇ ((z ◇ z) ◇ (y ◇ z))
equation 984 := x = y ◇ ((z ◇ z) ◇ (y ◇ w))
equation 985 := x = y ◇ ((z ◇ z) ◇ (z ◇ x))
equation 986 := x = y ◇ ((z ◇ z) ◇ (z ◇ y))
equation 987 := x = y ◇ ((z ◇ z) ◇ (z ◇ z))
equation 988 := x = y ◇ ((z ◇ z) ◇ (z ◇ w))
equation 989 := x = y ◇ ((z ◇ z) ◇ (w ◇ x))
equation 990 := x = y ◇ ((z ◇ z) ◇ (w ◇ y))
equation 991 := x = y ◇ ((z ◇ z) ◇ (w ◇ z))
equation 992 := x = y ◇ ((z ◇ z) ◇ (w ◇ w))
equation 993 := x = y ◇ ((z ◇ z) ◇ (w ◇ u))
equation 994 := x = y ◇ ((z ◇ w) ◇ (x ◇ x))
equation 995 := x = y ◇ ((z ◇ w) ◇ (x ◇ y))
equation 996 := x = y ◇ ((z ◇ w) ◇ (x ◇ z))
equation 997 := x = y ◇ ((z ◇ w) ◇ (x ◇ w))
equation 998 := x = y ◇ ((z ◇ w) ◇ (x ◇ u))
equation 999 := x = y ◇ ((z ◇ w) ◇ (y ◇ x))
