import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 3000-3999 -/

equation 3000 := x = ((y ◇ (z ◇ y)) ◇ z) ◇ z
equation 3001 := x = ((y ◇ (z ◇ y)) ◇ z) ◇ w
equation 3002 := x = ((y ◇ (z ◇ y)) ◇ w) ◇ x
equation 3003 := x = ((y ◇ (z ◇ y)) ◇ w) ◇ y
equation 3004 := x = ((y ◇ (z ◇ y)) ◇ w) ◇ z
equation 3005 := x = ((y ◇ (z ◇ y)) ◇ w) ◇ w
equation 3006 := x = ((y ◇ (z ◇ y)) ◇ w) ◇ u
equation 3007 := x = ((y ◇ (z ◇ z)) ◇ x) ◇ x
equation 3008 := x = ((y ◇ (z ◇ z)) ◇ x) ◇ y
equation 3009 := x = ((y ◇ (z ◇ z)) ◇ x) ◇ z
equation 3010 := x = ((y ◇ (z ◇ z)) ◇ x) ◇ w
equation 3011 := x = ((y ◇ (z ◇ z)) ◇ y) ◇ x
equation 3012 := x = ((y ◇ (z ◇ z)) ◇ y) ◇ y
equation 3013 := x = ((y ◇ (z ◇ z)) ◇ y) ◇ z
equation 3014 := x = ((y ◇ (z ◇ z)) ◇ y) ◇ w
equation 3015 := x = ((y ◇ (z ◇ z)) ◇ z) ◇ x
equation 3016 := x = ((y ◇ (z ◇ z)) ◇ z) ◇ y
equation 3017 := x = ((y ◇ (z ◇ z)) ◇ z) ◇ z
equation 3018 := x = ((y ◇ (z ◇ z)) ◇ z) ◇ w
equation 3019 := x = ((y ◇ (z ◇ z)) ◇ w) ◇ x
equation 3020 := x = ((y ◇ (z ◇ z)) ◇ w) ◇ y
equation 3021 := x = ((y ◇ (z ◇ z)) ◇ w) ◇ z
equation 3022 := x = ((y ◇ (z ◇ z)) ◇ w) ◇ w
equation 3023 := x = ((y ◇ (z ◇ z)) ◇ w) ◇ u
equation 3024 := x = ((y ◇ (z ◇ w)) ◇ x) ◇ x
equation 3025 := x = ((y ◇ (z ◇ w)) ◇ x) ◇ y
equation 3026 := x = ((y ◇ (z ◇ w)) ◇ x) ◇ z
equation 3027 := x = ((y ◇ (z ◇ w)) ◇ x) ◇ w
equation 3028 := x = ((y ◇ (z ◇ w)) ◇ x) ◇ u
equation 3029 := x = ((y ◇ (z ◇ w)) ◇ y) ◇ x
equation 3030 := x = ((y ◇ (z ◇ w)) ◇ y) ◇ y
equation 3031 := x = ((y ◇ (z ◇ w)) ◇ y) ◇ z
equation 3032 := x = ((y ◇ (z ◇ w)) ◇ y) ◇ w
equation 3033 := x = ((y ◇ (z ◇ w)) ◇ y) ◇ u
equation 3034 := x = ((y ◇ (z ◇ w)) ◇ z) ◇ x
equation 3035 := x = ((y ◇ (z ◇ w)) ◇ z) ◇ y
equation 3036 := x = ((y ◇ (z ◇ w)) ◇ z) ◇ z
equation 3037 := x = ((y ◇ (z ◇ w)) ◇ z) ◇ w
equation 3038 := x = ((y ◇ (z ◇ w)) ◇ z) ◇ u
equation 3039 := x = ((y ◇ (z ◇ w)) ◇ w) ◇ x
equation 3040 := x = ((y ◇ (z ◇ w)) ◇ w) ◇ y
equation 3041 := x = ((y ◇ (z ◇ w)) ◇ w) ◇ z
equation 3042 := x = ((y ◇ (z ◇ w)) ◇ w) ◇ w
equation 3043 := x = ((y ◇ (z ◇ w)) ◇ w) ◇ u
equation 3044 := x = ((y ◇ (z ◇ w)) ◇ u) ◇ x
equation 3045 := x = ((y ◇ (z ◇ w)) ◇ u) ◇ y
equation 3046 := x = ((y ◇ (z ◇ w)) ◇ u) ◇ z
equation 3047 := x = ((y ◇ (z ◇ w)) ◇ u) ◇ w
equation 3048 := x = ((y ◇ (z ◇ w)) ◇ u) ◇ u
equation 3049 := x = ((y ◇ (z ◇ w)) ◇ u) ◇ v
equation 3050 := x = (((x ◇ x) ◇ x) ◇ x) ◇ x
equation 3051 := x = (((x ◇ x) ◇ x) ◇ x) ◇ y
equation 3052 := x = (((x ◇ x) ◇ x) ◇ y) ◇ x
equation 3053 := x = (((x ◇ x) ◇ x) ◇ y) ◇ y
equation 3054 := x = (((x ◇ x) ◇ x) ◇ y) ◇ z
equation 3055 := x = (((x ◇ x) ◇ y) ◇ x) ◇ x
equation 3056 := x = (((x ◇ x) ◇ y) ◇ x) ◇ y
equation 3057 := x = (((x ◇ x) ◇ y) ◇ x) ◇ z
equation 3058 := x = (((x ◇ x) ◇ y) ◇ y) ◇ x
equation 3059 := x = (((x ◇ x) ◇ y) ◇ y) ◇ y
equation 3060 := x = (((x ◇ x) ◇ y) ◇ y) ◇ z
equation 3061 := x = (((x ◇ x) ◇ y) ◇ z) ◇ x
equation 3062 := x = (((x ◇ x) ◇ y) ◇ z) ◇ y
equation 3063 := x = (((x ◇ x) ◇ y) ◇ z) ◇ z
equation 3064 := x = (((x ◇ x) ◇ y) ◇ z) ◇ w
equation 3065 := x = (((x ◇ y) ◇ x) ◇ x) ◇ x
equation 3066 := x = (((x ◇ y) ◇ x) ◇ x) ◇ y
equation 3067 := x = (((x ◇ y) ◇ x) ◇ x) ◇ z
equation 3068 := x = (((x ◇ y) ◇ x) ◇ y) ◇ x
equation 3069 := x = (((x ◇ y) ◇ x) ◇ y) ◇ y
equation 3070 := x = (((x ◇ y) ◇ x) ◇ y) ◇ z
equation 3071 := x = (((x ◇ y) ◇ x) ◇ z) ◇ x
equation 3072 := x = (((x ◇ y) ◇ x) ◇ z) ◇ y
equation 3073 := x = (((x ◇ y) ◇ x) ◇ z) ◇ z
equation 3074 := x = (((x ◇ y) ◇ x) ◇ z) ◇ w
equation 3075 := x = (((x ◇ y) ◇ y) ◇ x) ◇ x
equation 3076 := x = (((x ◇ y) ◇ y) ◇ x) ◇ y
equation 3077 := x = (((x ◇ y) ◇ y) ◇ x) ◇ z
equation 3078 := x = (((x ◇ y) ◇ y) ◇ y) ◇ x
equation 3079 := x = (((x ◇ y) ◇ y) ◇ y) ◇ y
equation 3080 := x = (((x ◇ y) ◇ y) ◇ y) ◇ z
equation 3081 := x = (((x ◇ y) ◇ y) ◇ z) ◇ x
equation 3082 := x = (((x ◇ y) ◇ y) ◇ z) ◇ y
equation 3083 := x = (((x ◇ y) ◇ y) ◇ z) ◇ z
equation 3084 := x = (((x ◇ y) ◇ y) ◇ z) ◇ w
equation 3085 := x = (((x ◇ y) ◇ z) ◇ x) ◇ x
equation 3086 := x = (((x ◇ y) ◇ z) ◇ x) ◇ y
equation 3087 := x = (((x ◇ y) ◇ z) ◇ x) ◇ z
equation 3088 := x = (((x ◇ y) ◇ z) ◇ x) ◇ w
equation 3089 := x = (((x ◇ y) ◇ z) ◇ y) ◇ x
equation 3090 := x = (((x ◇ y) ◇ z) ◇ y) ◇ y
equation 3091 := x = (((x ◇ y) ◇ z) ◇ y) ◇ z
equation 3092 := x = (((x ◇ y) ◇ z) ◇ y) ◇ w
equation 3093 := x = (((x ◇ y) ◇ z) ◇ z) ◇ x
equation 3094 := x = (((x ◇ y) ◇ z) ◇ z) ◇ y
equation 3095 := x = (((x ◇ y) ◇ z) ◇ z) ◇ z
equation 3096 := x = (((x ◇ y) ◇ z) ◇ z) ◇ w
equation 3097 := x = (((x ◇ y) ◇ z) ◇ w) ◇ x
equation 3098 := x = (((x ◇ y) ◇ z) ◇ w) ◇ y
equation 3099 := x = (((x ◇ y) ◇ z) ◇ w) ◇ z
equation 3100 := x = (((x ◇ y) ◇ z) ◇ w) ◇ w
equation 3101 := x = (((x ◇ y) ◇ z) ◇ w) ◇ u
equation 3102 := x = (((y ◇ x) ◇ x) ◇ x) ◇ x
equation 3103 := x = (((y ◇ x) ◇ x) ◇ x) ◇ y
equation 3104 := x = (((y ◇ x) ◇ x) ◇ x) ◇ z
equation 3105 := x = (((y ◇ x) ◇ x) ◇ y) ◇ x
equation 3106 := x = (((y ◇ x) ◇ x) ◇ y) ◇ y
equation 3107 := x = (((y ◇ x) ◇ x) ◇ y) ◇ z
equation 3108 := x = (((y ◇ x) ◇ x) ◇ z) ◇ x
equation 3109 := x = (((y ◇ x) ◇ x) ◇ z) ◇ y
equation 3110 := x = (((y ◇ x) ◇ x) ◇ z) ◇ z
equation 3111 := x = (((y ◇ x) ◇ x) ◇ z) ◇ w
equation 3112 := x = (((y ◇ x) ◇ y) ◇ x) ◇ x
equation 3113 := x = (((y ◇ x) ◇ y) ◇ x) ◇ y
equation 3114 := x = (((y ◇ x) ◇ y) ◇ x) ◇ z
equation 3115 := x = (((y ◇ x) ◇ y) ◇ y) ◇ x
equation 3116 := x = (((y ◇ x) ◇ y) ◇ y) ◇ y
equation 3117 := x = (((y ◇ x) ◇ y) ◇ y) ◇ z
equation 3118 := x = (((y ◇ x) ◇ y) ◇ z) ◇ x
equation 3119 := x = (((y ◇ x) ◇ y) ◇ z) ◇ y
equation 3120 := x = (((y ◇ x) ◇ y) ◇ z) ◇ z
equation 3121 := x = (((y ◇ x) ◇ y) ◇ z) ◇ w
equation 3122 := x = (((y ◇ x) ◇ z) ◇ x) ◇ x
equation 3123 := x = (((y ◇ x) ◇ z) ◇ x) ◇ y
equation 3124 := x = (((y ◇ x) ◇ z) ◇ x) ◇ z
equation 3125 := x = (((y ◇ x) ◇ z) ◇ x) ◇ w
equation 3126 := x = (((y ◇ x) ◇ z) ◇ y) ◇ x
equation 3127 := x = (((y ◇ x) ◇ z) ◇ y) ◇ y
equation 3128 := x = (((y ◇ x) ◇ z) ◇ y) ◇ z
equation 3129 := x = (((y ◇ x) ◇ z) ◇ y) ◇ w
equation 3130 := x = (((y ◇ x) ◇ z) ◇ z) ◇ x
equation 3131 := x = (((y ◇ x) ◇ z) ◇ z) ◇ y
equation 3132 := x = (((y ◇ x) ◇ z) ◇ z) ◇ z
equation 3133 := x = (((y ◇ x) ◇ z) ◇ z) ◇ w
equation 3134 := x = (((y ◇ x) ◇ z) ◇ w) ◇ x
equation 3135 := x = (((y ◇ x) ◇ z) ◇ w) ◇ y
equation 3136 := x = (((y ◇ x) ◇ z) ◇ w) ◇ z
equation 3137 := x = (((y ◇ x) ◇ z) ◇ w) ◇ w
equation 3138 := x = (((y ◇ x) ◇ z) ◇ w) ◇ u
equation 3139 := x = (((y ◇ y) ◇ x) ◇ x) ◇ x
equation 3140 := x = (((y ◇ y) ◇ x) ◇ x) ◇ y
equation 3141 := x = (((y ◇ y) ◇ x) ◇ x) ◇ z
equation 3142 := x = (((y ◇ y) ◇ x) ◇ y) ◇ x
equation 3143 := x = (((y ◇ y) ◇ x) ◇ y) ◇ y
equation 3144 := x = (((y ◇ y) ◇ x) ◇ y) ◇ z
equation 3145 := x = (((y ◇ y) ◇ x) ◇ z) ◇ x
equation 3146 := x = (((y ◇ y) ◇ x) ◇ z) ◇ y
equation 3147 := x = (((y ◇ y) ◇ x) ◇ z) ◇ z
equation 3148 := x = (((y ◇ y) ◇ x) ◇ z) ◇ w
equation 3149 := x = (((y ◇ y) ◇ y) ◇ x) ◇ x
equation 3150 := x = (((y ◇ y) ◇ y) ◇ x) ◇ y
equation 3151 := x = (((y ◇ y) ◇ y) ◇ x) ◇ z
equation 3152 := x = (((y ◇ y) ◇ y) ◇ y) ◇ x
equation 3153 := x = (((y ◇ y) ◇ y) ◇ y) ◇ y
equation 3154 := x = (((y ◇ y) ◇ y) ◇ y) ◇ z
equation 3155 := x = (((y ◇ y) ◇ y) ◇ z) ◇ x
equation 3156 := x = (((y ◇ y) ◇ y) ◇ z) ◇ y
equation 3157 := x = (((y ◇ y) ◇ y) ◇ z) ◇ z
equation 3158 := x = (((y ◇ y) ◇ y) ◇ z) ◇ w
equation 3159 := x = (((y ◇ y) ◇ z) ◇ x) ◇ x
equation 3160 := x = (((y ◇ y) ◇ z) ◇ x) ◇ y
equation 3161 := x = (((y ◇ y) ◇ z) ◇ x) ◇ z
equation 3162 := x = (((y ◇ y) ◇ z) ◇ x) ◇ w
equation 3163 := x = (((y ◇ y) ◇ z) ◇ y) ◇ x
equation 3164 := x = (((y ◇ y) ◇ z) ◇ y) ◇ y
equation 3165 := x = (((y ◇ y) ◇ z) ◇ y) ◇ z
equation 3166 := x = (((y ◇ y) ◇ z) ◇ y) ◇ w
-- equation 3167 := x = (((y ◇ y) ◇ z) ◇ z) ◇ x
equation 3168 := x = (((y ◇ y) ◇ z) ◇ z) ◇ y
equation 3169 := x = (((y ◇ y) ◇ z) ◇ z) ◇ z
equation 3170 := x = (((y ◇ y) ◇ z) ◇ z) ◇ w
equation 3171 := x = (((y ◇ y) ◇ z) ◇ w) ◇ x
equation 3172 := x = (((y ◇ y) ◇ z) ◇ w) ◇ y
equation 3173 := x = (((y ◇ y) ◇ z) ◇ w) ◇ z
equation 3174 := x = (((y ◇ y) ◇ z) ◇ w) ◇ w
equation 3175 := x = (((y ◇ y) ◇ z) ◇ w) ◇ u
equation 3176 := x = (((y ◇ z) ◇ x) ◇ x) ◇ x
equation 3177 := x = (((y ◇ z) ◇ x) ◇ x) ◇ y
equation 3178 := x = (((y ◇ z) ◇ x) ◇ x) ◇ z
equation 3179 := x = (((y ◇ z) ◇ x) ◇ x) ◇ w
equation 3180 := x = (((y ◇ z) ◇ x) ◇ y) ◇ x
equation 3181 := x = (((y ◇ z) ◇ x) ◇ y) ◇ y
equation 3182 := x = (((y ◇ z) ◇ x) ◇ y) ◇ z
equation 3183 := x = (((y ◇ z) ◇ x) ◇ y) ◇ w
equation 3184 := x = (((y ◇ z) ◇ x) ◇ z) ◇ x
equation 3185 := x = (((y ◇ z) ◇ x) ◇ z) ◇ y
equation 3186 := x = (((y ◇ z) ◇ x) ◇ z) ◇ z
equation 3187 := x = (((y ◇ z) ◇ x) ◇ z) ◇ w
equation 3188 := x = (((y ◇ z) ◇ x) ◇ w) ◇ x
equation 3189 := x = (((y ◇ z) ◇ x) ◇ w) ◇ y
equation 3190 := x = (((y ◇ z) ◇ x) ◇ w) ◇ z
equation 3191 := x = (((y ◇ z) ◇ x) ◇ w) ◇ w
equation 3192 := x = (((y ◇ z) ◇ x) ◇ w) ◇ u
equation 3193 := x = (((y ◇ z) ◇ y) ◇ x) ◇ x
equation 3194 := x = (((y ◇ z) ◇ y) ◇ x) ◇ y
equation 3195 := x = (((y ◇ z) ◇ y) ◇ x) ◇ z
equation 3196 := x = (((y ◇ z) ◇ y) ◇ x) ◇ w
equation 3197 := x = (((y ◇ z) ◇ y) ◇ y) ◇ x
equation 3198 := x = (((y ◇ z) ◇ y) ◇ y) ◇ y
equation 3199 := x = (((y ◇ z) ◇ y) ◇ y) ◇ z
equation 3200 := x = (((y ◇ z) ◇ y) ◇ y) ◇ w
equation 3201 := x = (((y ◇ z) ◇ y) ◇ z) ◇ x
equation 3202 := x = (((y ◇ z) ◇ y) ◇ z) ◇ y
equation 3203 := x = (((y ◇ z) ◇ y) ◇ z) ◇ z
equation 3204 := x = (((y ◇ z) ◇ y) ◇ z) ◇ w
equation 3205 := x = (((y ◇ z) ◇ y) ◇ w) ◇ x
equation 3206 := x = (((y ◇ z) ◇ y) ◇ w) ◇ y
equation 3207 := x = (((y ◇ z) ◇ y) ◇ w) ◇ z
equation 3208 := x = (((y ◇ z) ◇ y) ◇ w) ◇ w
equation 3209 := x = (((y ◇ z) ◇ y) ◇ w) ◇ u
equation 3210 := x = (((y ◇ z) ◇ z) ◇ x) ◇ x
equation 3211 := x = (((y ◇ z) ◇ z) ◇ x) ◇ y
equation 3212 := x = (((y ◇ z) ◇ z) ◇ x) ◇ z
equation 3213 := x = (((y ◇ z) ◇ z) ◇ x) ◇ w
equation 3214 := x = (((y ◇ z) ◇ z) ◇ y) ◇ x
equation 3215 := x = (((y ◇ z) ◇ z) ◇ y) ◇ y
equation 3216 := x = (((y ◇ z) ◇ z) ◇ y) ◇ z
equation 3217 := x = (((y ◇ z) ◇ z) ◇ y) ◇ w
equation 3218 := x = (((y ◇ z) ◇ z) ◇ z) ◇ x
equation 3219 := x = (((y ◇ z) ◇ z) ◇ z) ◇ y
equation 3220 := x = (((y ◇ z) ◇ z) ◇ z) ◇ z
equation 3221 := x = (((y ◇ z) ◇ z) ◇ z) ◇ w
equation 3222 := x = (((y ◇ z) ◇ z) ◇ w) ◇ x
equation 3223 := x = (((y ◇ z) ◇ z) ◇ w) ◇ y
equation 3224 := x = (((y ◇ z) ◇ z) ◇ w) ◇ z
equation 3225 := x = (((y ◇ z) ◇ z) ◇ w) ◇ w
equation 3226 := x = (((y ◇ z) ◇ z) ◇ w) ◇ u
equation 3227 := x = (((y ◇ z) ◇ w) ◇ x) ◇ x
equation 3228 := x = (((y ◇ z) ◇ w) ◇ x) ◇ y
equation 3229 := x = (((y ◇ z) ◇ w) ◇ x) ◇ z
equation 3230 := x = (((y ◇ z) ◇ w) ◇ x) ◇ w
equation 3231 := x = (((y ◇ z) ◇ w) ◇ x) ◇ u
equation 3232 := x = (((y ◇ z) ◇ w) ◇ y) ◇ x
equation 3233 := x = (((y ◇ z) ◇ w) ◇ y) ◇ y
equation 3234 := x = (((y ◇ z) ◇ w) ◇ y) ◇ z
equation 3235 := x = (((y ◇ z) ◇ w) ◇ y) ◇ w
equation 3236 := x = (((y ◇ z) ◇ w) ◇ y) ◇ u
equation 3237 := x = (((y ◇ z) ◇ w) ◇ z) ◇ x
equation 3238 := x = (((y ◇ z) ◇ w) ◇ z) ◇ y
equation 3239 := x = (((y ◇ z) ◇ w) ◇ z) ◇ z
equation 3240 := x = (((y ◇ z) ◇ w) ◇ z) ◇ w
equation 3241 := x = (((y ◇ z) ◇ w) ◇ z) ◇ u
equation 3242 := x = (((y ◇ z) ◇ w) ◇ w) ◇ x
equation 3243 := x = (((y ◇ z) ◇ w) ◇ w) ◇ y
equation 3244 := x = (((y ◇ z) ◇ w) ◇ w) ◇ z
equation 3245 := x = (((y ◇ z) ◇ w) ◇ w) ◇ w
equation 3246 := x = (((y ◇ z) ◇ w) ◇ w) ◇ u
equation 3247 := x = (((y ◇ z) ◇ w) ◇ u) ◇ x
equation 3248 := x = (((y ◇ z) ◇ w) ◇ u) ◇ y
equation 3249 := x = (((y ◇ z) ◇ w) ◇ u) ◇ z
equation 3250 := x = (((y ◇ z) ◇ w) ◇ u) ◇ w
equation 3251 := x = (((y ◇ z) ◇ w) ◇ u) ◇ u
equation 3252 := x = (((y ◇ z) ◇ w) ◇ u) ◇ v
equation 3253 := x ◇ x = x ◇ (x ◇ (x ◇ x))
equation 3254 := x ◇ x = x ◇ (x ◇ (x ◇ y))
equation 3255 := x ◇ x = x ◇ (x ◇ (y ◇ x))
equation 3256 := x ◇ x = x ◇ (x ◇ (y ◇ y))
equation 3257 := x ◇ x = x ◇ (x ◇ (y ◇ z))
equation 3258 := x ◇ x = x ◇ (y ◇ (x ◇ x))
equation 3259 := x ◇ x = x ◇ (y ◇ (x ◇ y))
equation 3260 := x ◇ x = x ◇ (y ◇ (x ◇ z))
equation 3261 := x ◇ x = x ◇ (y ◇ (y ◇ x))
equation 3262 := x ◇ x = x ◇ (y ◇ (y ◇ y))
equation 3263 := x ◇ x = x ◇ (y ◇ (y ◇ z))
equation 3264 := x ◇ x = x ◇ (y ◇ (z ◇ x))
equation 3265 := x ◇ x = x ◇ (y ◇ (z ◇ y))
equation 3266 := x ◇ x = x ◇ (y ◇ (z ◇ z))
equation 3267 := x ◇ x = x ◇ (y ◇ (z ◇ w))
equation 3268 := x ◇ x = y ◇ (x ◇ (x ◇ x))
equation 3269 := x ◇ x = y ◇ (x ◇ (x ◇ y))
equation 3270 := x ◇ x = y ◇ (x ◇ (x ◇ z))
equation 3271 := x ◇ x = y ◇ (x ◇ (y ◇ x))
equation 3272 := x ◇ x = y ◇ (x ◇ (y ◇ y))
equation 3273 := x ◇ x = y ◇ (x ◇ (y ◇ z))
equation 3274 := x ◇ x = y ◇ (x ◇ (z ◇ x))
equation 3275 := x ◇ x = y ◇ (x ◇ (z ◇ y))
equation 3276 := x ◇ x = y ◇ (x ◇ (z ◇ z))
equation 3277 := x ◇ x = y ◇ (x ◇ (z ◇ w))
equation 3278 := x ◇ x = y ◇ (y ◇ (x ◇ x))
equation 3279 := x ◇ x = y ◇ (y ◇ (x ◇ y))
equation 3280 := x ◇ x = y ◇ (y ◇ (x ◇ z))
equation 3281 := x ◇ x = y ◇ (y ◇ (y ◇ x))
equation 3282 := x ◇ x = y ◇ (y ◇ (y ◇ y))
equation 3283 := x ◇ x = y ◇ (y ◇ (y ◇ z))
equation 3284 := x ◇ x = y ◇ (y ◇ (z ◇ x))
equation 3285 := x ◇ x = y ◇ (y ◇ (z ◇ y))
equation 3286 := x ◇ x = y ◇ (y ◇ (z ◇ z))
equation 3287 := x ◇ x = y ◇ (y ◇ (z ◇ w))
equation 3288 := x ◇ x = y ◇ (z ◇ (x ◇ x))
equation 3289 := x ◇ x = y ◇ (z ◇ (x ◇ y))
equation 3290 := x ◇ x = y ◇ (z ◇ (x ◇ z))
equation 3291 := x ◇ x = y ◇ (z ◇ (x ◇ w))
equation 3292 := x ◇ x = y ◇ (z ◇ (y ◇ x))
equation 3293 := x ◇ x = y ◇ (z ◇ (y ◇ y))
equation 3294 := x ◇ x = y ◇ (z ◇ (y ◇ z))
equation 3295 := x ◇ x = y ◇ (z ◇ (y ◇ w))
equation 3296 := x ◇ x = y ◇ (z ◇ (z ◇ x))
equation 3297 := x ◇ x = y ◇ (z ◇ (z ◇ y))
equation 3298 := x ◇ x = y ◇ (z ◇ (z ◇ z))
equation 3299 := x ◇ x = y ◇ (z ◇ (z ◇ w))
equation 3300 := x ◇ x = y ◇ (z ◇ (w ◇ x))
equation 3301 := x ◇ x = y ◇ (z ◇ (w ◇ y))
equation 3302 := x ◇ x = y ◇ (z ◇ (w ◇ z))
equation 3303 := x ◇ x = y ◇ (z ◇ (w ◇ w))
equation 3304 := x ◇ x = y ◇ (z ◇ (w ◇ u))
equation 3305 := x ◇ y = x ◇ (x ◇ (x ◇ x))
equation 3306 := x ◇ y = x ◇ (x ◇ (x ◇ y))
equation 3307 := x ◇ y = x ◇ (x ◇ (x ◇ z))
equation 3308 := x ◇ y = x ◇ (x ◇ (y ◇ x))
equation 3309 := x ◇ y = x ◇ (x ◇ (y ◇ y))
equation 3310 := x ◇ y = x ◇ (x ◇ (y ◇ z))
equation 3311 := x ◇ y = x ◇ (x ◇ (z ◇ x))
equation 3312 := x ◇ y = x ◇ (x ◇ (z ◇ y))
equation 3313 := x ◇ y = x ◇ (x ◇ (z ◇ z))
equation 3314 := x ◇ y = x ◇ (x ◇ (z ◇ w))
equation 3315 := x ◇ y = x ◇ (y ◇ (x ◇ x))
equation 3316 := x ◇ y = x ◇ (y ◇ (x ◇ y))
equation 3317 := x ◇ y = x ◇ (y ◇ (x ◇ z))
equation 3318 := x ◇ y = x ◇ (y ◇ (y ◇ x))
equation 3319 := x ◇ y = x ◇ (y ◇ (y ◇ y))
equation 3320 := x ◇ y = x ◇ (y ◇ (y ◇ z))
equation 3321 := x ◇ y = x ◇ (y ◇ (z ◇ x))
equation 3322 := x ◇ y = x ◇ (y ◇ (z ◇ y))
equation 3323 := x ◇ y = x ◇ (y ◇ (z ◇ z))
equation 3324 := x ◇ y = x ◇ (y ◇ (z ◇ w))
equation 3325 := x ◇ y = x ◇ (z ◇ (x ◇ x))
equation 3326 := x ◇ y = x ◇ (z ◇ (x ◇ y))
equation 3327 := x ◇ y = x ◇ (z ◇ (x ◇ z))
equation 3328 := x ◇ y = x ◇ (z ◇ (x ◇ w))
equation 3329 := x ◇ y = x ◇ (z ◇ (y ◇ x))
equation 3330 := x ◇ y = x ◇ (z ◇ (y ◇ y))
equation 3331 := x ◇ y = x ◇ (z ◇ (y ◇ z))
equation 3332 := x ◇ y = x ◇ (z ◇ (y ◇ w))
equation 3333 := x ◇ y = x ◇ (z ◇ (z ◇ x))
equation 3334 := x ◇ y = x ◇ (z ◇ (z ◇ y))
equation 3335 := x ◇ y = x ◇ (z ◇ (z ◇ z))
equation 3336 := x ◇ y = x ◇ (z ◇ (z ◇ w))
equation 3337 := x ◇ y = x ◇ (z ◇ (w ◇ x))
equation 3338 := x ◇ y = x ◇ (z ◇ (w ◇ y))
equation 3339 := x ◇ y = x ◇ (z ◇ (w ◇ z))
equation 3340 := x ◇ y = x ◇ (z ◇ (w ◇ w))
equation 3341 := x ◇ y = x ◇ (z ◇ (w ◇ u))
equation 3342 := x ◇ y = y ◇ (x ◇ (x ◇ x))
equation 3343 := x ◇ y = y ◇ (x ◇ (x ◇ y))
equation 3344 := x ◇ y = y ◇ (x ◇ (x ◇ z))
equation 3345 := x ◇ y = y ◇ (x ◇ (y ◇ x))
equation 3346 := x ◇ y = y ◇ (x ◇ (y ◇ y))
equation 3347 := x ◇ y = y ◇ (x ◇ (y ◇ z))
equation 3348 := x ◇ y = y ◇ (x ◇ (z ◇ x))
equation 3349 := x ◇ y = y ◇ (x ◇ (z ◇ y))
equation 3350 := x ◇ y = y ◇ (x ◇ (z ◇ z))
equation 3351 := x ◇ y = y ◇ (x ◇ (z ◇ w))
equation 3352 := x ◇ y = y ◇ (y ◇ (x ◇ x))
equation 3353 := x ◇ y = y ◇ (y ◇ (x ◇ y))
equation 3354 := x ◇ y = y ◇ (y ◇ (x ◇ z))
equation 3355 := x ◇ y = y ◇ (y ◇ (y ◇ x))
equation 3356 := x ◇ y = y ◇ (y ◇ (y ◇ y))
equation 3357 := x ◇ y = y ◇ (y ◇ (y ◇ z))
equation 3358 := x ◇ y = y ◇ (y ◇ (z ◇ x))
equation 3359 := x ◇ y = y ◇ (y ◇ (z ◇ y))
equation 3360 := x ◇ y = y ◇ (y ◇ (z ◇ z))
equation 3361 := x ◇ y = y ◇ (y ◇ (z ◇ w))
equation 3362 := x ◇ y = y ◇ (z ◇ (x ◇ x))
equation 3363 := x ◇ y = y ◇ (z ◇ (x ◇ y))
equation 3364 := x ◇ y = y ◇ (z ◇ (x ◇ z))
equation 3365 := x ◇ y = y ◇ (z ◇ (x ◇ w))
equation 3366 := x ◇ y = y ◇ (z ◇ (y ◇ x))
equation 3367 := x ◇ y = y ◇ (z ◇ (y ◇ y))
equation 3368 := x ◇ y = y ◇ (z ◇ (y ◇ z))
equation 3369 := x ◇ y = y ◇ (z ◇ (y ◇ w))
equation 3370 := x ◇ y = y ◇ (z ◇ (z ◇ x))
equation 3371 := x ◇ y = y ◇ (z ◇ (z ◇ y))
equation 3372 := x ◇ y = y ◇ (z ◇ (z ◇ z))
equation 3373 := x ◇ y = y ◇ (z ◇ (z ◇ w))
equation 3374 := x ◇ y = y ◇ (z ◇ (w ◇ x))
equation 3375 := x ◇ y = y ◇ (z ◇ (w ◇ y))
equation 3376 := x ◇ y = y ◇ (z ◇ (w ◇ z))
equation 3377 := x ◇ y = y ◇ (z ◇ (w ◇ w))
equation 3378 := x ◇ y = y ◇ (z ◇ (w ◇ u))
equation 3379 := x ◇ y = z ◇ (x ◇ (x ◇ x))
equation 3380 := x ◇ y = z ◇ (x ◇ (x ◇ y))
equation 3381 := x ◇ y = z ◇ (x ◇ (x ◇ z))
equation 3382 := x ◇ y = z ◇ (x ◇ (x ◇ w))
equation 3383 := x ◇ y = z ◇ (x ◇ (y ◇ x))
equation 3384 := x ◇ y = z ◇ (x ◇ (y ◇ y))
equation 3385 := x ◇ y = z ◇ (x ◇ (y ◇ z))
equation 3386 := x ◇ y = z ◇ (x ◇ (y ◇ w))
equation 3387 := x ◇ y = z ◇ (x ◇ (z ◇ x))
equation 3388 := x ◇ y = z ◇ (x ◇ (z ◇ y))
equation 3389 := x ◇ y = z ◇ (x ◇ (z ◇ z))
equation 3390 := x ◇ y = z ◇ (x ◇ (z ◇ w))
equation 3391 := x ◇ y = z ◇ (x ◇ (w ◇ x))
equation 3392 := x ◇ y = z ◇ (x ◇ (w ◇ y))
equation 3393 := x ◇ y = z ◇ (x ◇ (w ◇ z))
equation 3394 := x ◇ y = z ◇ (x ◇ (w ◇ w))
equation 3395 := x ◇ y = z ◇ (x ◇ (w ◇ u))
equation 3396 := x ◇ y = z ◇ (y ◇ (x ◇ x))
equation 3397 := x ◇ y = z ◇ (y ◇ (x ◇ y))
equation 3398 := x ◇ y = z ◇ (y ◇ (x ◇ z))
equation 3399 := x ◇ y = z ◇ (y ◇ (x ◇ w))
equation 3400 := x ◇ y = z ◇ (y ◇ (y ◇ x))
equation 3401 := x ◇ y = z ◇ (y ◇ (y ◇ y))
equation 3402 := x ◇ y = z ◇ (y ◇ (y ◇ z))
equation 3403 := x ◇ y = z ◇ (y ◇ (y ◇ w))
equation 3404 := x ◇ y = z ◇ (y ◇ (z ◇ x))
equation 3405 := x ◇ y = z ◇ (y ◇ (z ◇ y))
equation 3406 := x ◇ y = z ◇ (y ◇ (z ◇ z))
equation 3407 := x ◇ y = z ◇ (y ◇ (z ◇ w))
equation 3408 := x ◇ y = z ◇ (y ◇ (w ◇ x))
equation 3409 := x ◇ y = z ◇ (y ◇ (w ◇ y))
equation 3410 := x ◇ y = z ◇ (y ◇ (w ◇ z))
equation 3411 := x ◇ y = z ◇ (y ◇ (w ◇ w))
equation 3412 := x ◇ y = z ◇ (y ◇ (w ◇ u))
equation 3413 := x ◇ y = z ◇ (z ◇ (x ◇ x))
equation 3414 := x ◇ y = z ◇ (z ◇ (x ◇ y))
equation 3415 := x ◇ y = z ◇ (z ◇ (x ◇ z))
equation 3416 := x ◇ y = z ◇ (z ◇ (x ◇ w))
equation 3417 := x ◇ y = z ◇ (z ◇ (y ◇ x))
equation 3418 := x ◇ y = z ◇ (z ◇ (y ◇ y))
equation 3419 := x ◇ y = z ◇ (z ◇ (y ◇ z))
equation 3420 := x ◇ y = z ◇ (z ◇ (y ◇ w))
equation 3421 := x ◇ y = z ◇ (z ◇ (z ◇ x))
equation 3422 := x ◇ y = z ◇ (z ◇ (z ◇ y))
equation 3423 := x ◇ y = z ◇ (z ◇ (z ◇ z))
equation 3424 := x ◇ y = z ◇ (z ◇ (z ◇ w))
equation 3425 := x ◇ y = z ◇ (z ◇ (w ◇ x))
equation 3426 := x ◇ y = z ◇ (z ◇ (w ◇ y))
equation 3427 := x ◇ y = z ◇ (z ◇ (w ◇ z))
equation 3428 := x ◇ y = z ◇ (z ◇ (w ◇ w))
equation 3429 := x ◇ y = z ◇ (z ◇ (w ◇ u))
equation 3430 := x ◇ y = z ◇ (w ◇ (x ◇ x))
equation 3431 := x ◇ y = z ◇ (w ◇ (x ◇ y))
equation 3432 := x ◇ y = z ◇ (w ◇ (x ◇ z))
equation 3433 := x ◇ y = z ◇ (w ◇ (x ◇ w))
equation 3434 := x ◇ y = z ◇ (w ◇ (x ◇ u))
equation 3435 := x ◇ y = z ◇ (w ◇ (y ◇ x))
equation 3436 := x ◇ y = z ◇ (w ◇ (y ◇ y))
equation 3437 := x ◇ y = z ◇ (w ◇ (y ◇ z))
equation 3438 := x ◇ y = z ◇ (w ◇ (y ◇ w))
equation 3439 := x ◇ y = z ◇ (w ◇ (y ◇ u))
equation 3440 := x ◇ y = z ◇ (w ◇ (z ◇ x))
equation 3441 := x ◇ y = z ◇ (w ◇ (z ◇ y))
equation 3442 := x ◇ y = z ◇ (w ◇ (z ◇ z))
equation 3443 := x ◇ y = z ◇ (w ◇ (z ◇ w))
equation 3444 := x ◇ y = z ◇ (w ◇ (z ◇ u))
equation 3445 := x ◇ y = z ◇ (w ◇ (w ◇ x))
equation 3446 := x ◇ y = z ◇ (w ◇ (w ◇ y))
equation 3447 := x ◇ y = z ◇ (w ◇ (w ◇ z))
equation 3448 := x ◇ y = z ◇ (w ◇ (w ◇ w))
equation 3449 := x ◇ y = z ◇ (w ◇ (w ◇ u))
equation 3450 := x ◇ y = z ◇ (w ◇ (u ◇ x))
equation 3451 := x ◇ y = z ◇ (w ◇ (u ◇ y))
equation 3452 := x ◇ y = z ◇ (w ◇ (u ◇ z))
equation 3453 := x ◇ y = z ◇ (w ◇ (u ◇ w))
equation 3454 := x ◇ y = z ◇ (w ◇ (u ◇ u))
equation 3455 := x ◇ y = z ◇ (w ◇ (u ◇ v))
equation 3456 := x ◇ x = x ◇ ((x ◇ x) ◇ x)
equation 3457 := x ◇ x = x ◇ ((x ◇ x) ◇ y)
equation 3458 := x ◇ x = x ◇ ((x ◇ y) ◇ x)
equation 3459 := x ◇ x = x ◇ ((x ◇ y) ◇ y)
equation 3460 := x ◇ x = x ◇ ((x ◇ y) ◇ z)
equation 3461 := x ◇ x = x ◇ ((y ◇ x) ◇ x)
equation 3462 := x ◇ x = x ◇ ((y ◇ x) ◇ y)
equation 3463 := x ◇ x = x ◇ ((y ◇ x) ◇ z)
equation 3464 := x ◇ x = x ◇ ((y ◇ y) ◇ x)
equation 3465 := x ◇ x = x ◇ ((y ◇ y) ◇ y)
equation 3466 := x ◇ x = x ◇ ((y ◇ y) ◇ z)
equation 3467 := x ◇ x = x ◇ ((y ◇ z) ◇ x)
equation 3468 := x ◇ x = x ◇ ((y ◇ z) ◇ y)
equation 3469 := x ◇ x = x ◇ ((y ◇ z) ◇ z)
equation 3470 := x ◇ x = x ◇ ((y ◇ z) ◇ w)
equation 3471 := x ◇ x = y ◇ ((x ◇ x) ◇ x)
equation 3472 := x ◇ x = y ◇ ((x ◇ x) ◇ y)
equation 3473 := x ◇ x = y ◇ ((x ◇ x) ◇ z)
equation 3474 := x ◇ x = y ◇ ((x ◇ y) ◇ x)
equation 3475 := x ◇ x = y ◇ ((x ◇ y) ◇ y)
equation 3476 := x ◇ x = y ◇ ((x ◇ y) ◇ z)
equation 3477 := x ◇ x = y ◇ ((x ◇ z) ◇ x)
equation 3478 := x ◇ x = y ◇ ((x ◇ z) ◇ y)
equation 3479 := x ◇ x = y ◇ ((x ◇ z) ◇ z)
equation 3480 := x ◇ x = y ◇ ((x ◇ z) ◇ w)
equation 3481 := x ◇ x = y ◇ ((y ◇ x) ◇ x)
equation 3482 := x ◇ x = y ◇ ((y ◇ x) ◇ y)
equation 3483 := x ◇ x = y ◇ ((y ◇ x) ◇ z)
equation 3484 := x ◇ x = y ◇ ((y ◇ y) ◇ x)
equation 3485 := x ◇ x = y ◇ ((y ◇ y) ◇ y)
equation 3486 := x ◇ x = y ◇ ((y ◇ y) ◇ z)
equation 3487 := x ◇ x = y ◇ ((y ◇ z) ◇ x)
equation 3488 := x ◇ x = y ◇ ((y ◇ z) ◇ y)
equation 3489 := x ◇ x = y ◇ ((y ◇ z) ◇ z)
equation 3490 := x ◇ x = y ◇ ((y ◇ z) ◇ w)
equation 3491 := x ◇ x = y ◇ ((z ◇ x) ◇ x)
equation 3492 := x ◇ x = y ◇ ((z ◇ x) ◇ y)
equation 3493 := x ◇ x = y ◇ ((z ◇ x) ◇ z)
equation 3494 := x ◇ x = y ◇ ((z ◇ x) ◇ w)
equation 3495 := x ◇ x = y ◇ ((z ◇ y) ◇ x)
equation 3496 := x ◇ x = y ◇ ((z ◇ y) ◇ y)
equation 3497 := x ◇ x = y ◇ ((z ◇ y) ◇ z)
equation 3498 := x ◇ x = y ◇ ((z ◇ y) ◇ w)
equation 3499 := x ◇ x = y ◇ ((z ◇ z) ◇ x)
equation 3500 := x ◇ x = y ◇ ((z ◇ z) ◇ y)
equation 3501 := x ◇ x = y ◇ ((z ◇ z) ◇ z)
equation 3502 := x ◇ x = y ◇ ((z ◇ z) ◇ w)
equation 3503 := x ◇ x = y ◇ ((z ◇ w) ◇ x)
equation 3504 := x ◇ x = y ◇ ((z ◇ w) ◇ y)
equation 3505 := x ◇ x = y ◇ ((z ◇ w) ◇ z)
equation 3506 := x ◇ x = y ◇ ((z ◇ w) ◇ w)
equation 3507 := x ◇ x = y ◇ ((z ◇ w) ◇ u)
equation 3508 := x ◇ y = x ◇ ((x ◇ x) ◇ x)
equation 3509 := x ◇ y = x ◇ ((x ◇ x) ◇ y)
equation 3510 := x ◇ y = x ◇ ((x ◇ x) ◇ z)
equation 3511 := x ◇ y = x ◇ ((x ◇ y) ◇ x)
equation 3512 := x ◇ y = x ◇ ((x ◇ y) ◇ y)
equation 3513 := x ◇ y = x ◇ ((x ◇ y) ◇ z)
equation 3514 := x ◇ y = x ◇ ((x ◇ z) ◇ x)
equation 3515 := x ◇ y = x ◇ ((x ◇ z) ◇ y)
equation 3516 := x ◇ y = x ◇ ((x ◇ z) ◇ z)
equation 3517 := x ◇ y = x ◇ ((x ◇ z) ◇ w)
equation 3518 := x ◇ y = x ◇ ((y ◇ x) ◇ x)
equation 3519 := x ◇ y = x ◇ ((y ◇ x) ◇ y)
equation 3520 := x ◇ y = x ◇ ((y ◇ x) ◇ z)
equation 3521 := x ◇ y = x ◇ ((y ◇ y) ◇ x)
equation 3522 := x ◇ y = x ◇ ((y ◇ y) ◇ y)
equation 3523 := x ◇ y = x ◇ ((y ◇ y) ◇ z)
equation 3524 := x ◇ y = x ◇ ((y ◇ z) ◇ x)
equation 3525 := x ◇ y = x ◇ ((y ◇ z) ◇ y)
equation 3526 := x ◇ y = x ◇ ((y ◇ z) ◇ z)
equation 3527 := x ◇ y = x ◇ ((y ◇ z) ◇ w)
equation 3528 := x ◇ y = x ◇ ((z ◇ x) ◇ x)
equation 3529 := x ◇ y = x ◇ ((z ◇ x) ◇ y)
equation 3530 := x ◇ y = x ◇ ((z ◇ x) ◇ z)
equation 3531 := x ◇ y = x ◇ ((z ◇ x) ◇ w)
equation 3532 := x ◇ y = x ◇ ((z ◇ y) ◇ x)
equation 3533 := x ◇ y = x ◇ ((z ◇ y) ◇ y)
equation 3534 := x ◇ y = x ◇ ((z ◇ y) ◇ z)
equation 3535 := x ◇ y = x ◇ ((z ◇ y) ◇ w)
equation 3536 := x ◇ y = x ◇ ((z ◇ z) ◇ x)
equation 3537 := x ◇ y = x ◇ ((z ◇ z) ◇ y)
equation 3538 := x ◇ y = x ◇ ((z ◇ z) ◇ z)
equation 3539 := x ◇ y = x ◇ ((z ◇ z) ◇ w)
equation 3540 := x ◇ y = x ◇ ((z ◇ w) ◇ x)
equation 3541 := x ◇ y = x ◇ ((z ◇ w) ◇ y)
equation 3542 := x ◇ y = x ◇ ((z ◇ w) ◇ z)
equation 3543 := x ◇ y = x ◇ ((z ◇ w) ◇ w)
equation 3544 := x ◇ y = x ◇ ((z ◇ w) ◇ u)
equation 3545 := x ◇ y = y ◇ ((x ◇ x) ◇ x)
equation 3546 := x ◇ y = y ◇ ((x ◇ x) ◇ y)
equation 3547 := x ◇ y = y ◇ ((x ◇ x) ◇ z)
equation 3548 := x ◇ y = y ◇ ((x ◇ y) ◇ x)
equation 3549 := x ◇ y = y ◇ ((x ◇ y) ◇ y)
equation 3550 := x ◇ y = y ◇ ((x ◇ y) ◇ z)
equation 3551 := x ◇ y = y ◇ ((x ◇ z) ◇ x)
equation 3552 := x ◇ y = y ◇ ((x ◇ z) ◇ y)
equation 3553 := x ◇ y = y ◇ ((x ◇ z) ◇ z)
equation 3554 := x ◇ y = y ◇ ((x ◇ z) ◇ w)
equation 3555 := x ◇ y = y ◇ ((y ◇ x) ◇ x)
equation 3556 := x ◇ y = y ◇ ((y ◇ x) ◇ y)
equation 3557 := x ◇ y = y ◇ ((y ◇ x) ◇ z)
equation 3558 := x ◇ y = y ◇ ((y ◇ y) ◇ x)
equation 3559 := x ◇ y = y ◇ ((y ◇ y) ◇ y)
equation 3560 := x ◇ y = y ◇ ((y ◇ y) ◇ z)
equation 3561 := x ◇ y = y ◇ ((y ◇ z) ◇ x)
equation 3562 := x ◇ y = y ◇ ((y ◇ z) ◇ y)
equation 3563 := x ◇ y = y ◇ ((y ◇ z) ◇ z)
equation 3564 := x ◇ y = y ◇ ((y ◇ z) ◇ w)
equation 3565 := x ◇ y = y ◇ ((z ◇ x) ◇ x)
equation 3566 := x ◇ y = y ◇ ((z ◇ x) ◇ y)
equation 3567 := x ◇ y = y ◇ ((z ◇ x) ◇ z)
equation 3568 := x ◇ y = y ◇ ((z ◇ x) ◇ w)
equation 3569 := x ◇ y = y ◇ ((z ◇ y) ◇ x)
equation 3570 := x ◇ y = y ◇ ((z ◇ y) ◇ y)
equation 3571 := x ◇ y = y ◇ ((z ◇ y) ◇ z)
equation 3572 := x ◇ y = y ◇ ((z ◇ y) ◇ w)
equation 3573 := x ◇ y = y ◇ ((z ◇ z) ◇ x)
equation 3574 := x ◇ y = y ◇ ((z ◇ z) ◇ y)
equation 3575 := x ◇ y = y ◇ ((z ◇ z) ◇ z)
equation 3576 := x ◇ y = y ◇ ((z ◇ z) ◇ w)
equation 3577 := x ◇ y = y ◇ ((z ◇ w) ◇ x)
equation 3578 := x ◇ y = y ◇ ((z ◇ w) ◇ y)
equation 3579 := x ◇ y = y ◇ ((z ◇ w) ◇ z)
equation 3580 := x ◇ y = y ◇ ((z ◇ w) ◇ w)
equation 3581 := x ◇ y = y ◇ ((z ◇ w) ◇ u)
equation 3582 := x ◇ y = z ◇ ((x ◇ x) ◇ x)
equation 3583 := x ◇ y = z ◇ ((x ◇ x) ◇ y)
equation 3584 := x ◇ y = z ◇ ((x ◇ x) ◇ z)
equation 3585 := x ◇ y = z ◇ ((x ◇ x) ◇ w)
equation 3586 := x ◇ y = z ◇ ((x ◇ y) ◇ x)
equation 3587 := x ◇ y = z ◇ ((x ◇ y) ◇ y)
equation 3588 := x ◇ y = z ◇ ((x ◇ y) ◇ z)
equation 3589 := x ◇ y = z ◇ ((x ◇ y) ◇ w)
equation 3590 := x ◇ y = z ◇ ((x ◇ z) ◇ x)
equation 3591 := x ◇ y = z ◇ ((x ◇ z) ◇ y)
equation 3592 := x ◇ y = z ◇ ((x ◇ z) ◇ z)
equation 3593 := x ◇ y = z ◇ ((x ◇ z) ◇ w)
equation 3594 := x ◇ y = z ◇ ((x ◇ w) ◇ x)
equation 3595 := x ◇ y = z ◇ ((x ◇ w) ◇ y)
equation 3596 := x ◇ y = z ◇ ((x ◇ w) ◇ z)
equation 3597 := x ◇ y = z ◇ ((x ◇ w) ◇ w)
equation 3598 := x ◇ y = z ◇ ((x ◇ w) ◇ u)
equation 3599 := x ◇ y = z ◇ ((y ◇ x) ◇ x)
equation 3600 := x ◇ y = z ◇ ((y ◇ x) ◇ y)
equation 3601 := x ◇ y = z ◇ ((y ◇ x) ◇ z)
equation 3602 := x ◇ y = z ◇ ((y ◇ x) ◇ w)
equation 3603 := x ◇ y = z ◇ ((y ◇ y) ◇ x)
equation 3604 := x ◇ y = z ◇ ((y ◇ y) ◇ y)
equation 3605 := x ◇ y = z ◇ ((y ◇ y) ◇ z)
equation 3606 := x ◇ y = z ◇ ((y ◇ y) ◇ w)
equation 3607 := x ◇ y = z ◇ ((y ◇ z) ◇ x)
equation 3608 := x ◇ y = z ◇ ((y ◇ z) ◇ y)
equation 3609 := x ◇ y = z ◇ ((y ◇ z) ◇ z)
equation 3610 := x ◇ y = z ◇ ((y ◇ z) ◇ w)
equation 3611 := x ◇ y = z ◇ ((y ◇ w) ◇ x)
equation 3612 := x ◇ y = z ◇ ((y ◇ w) ◇ y)
equation 3613 := x ◇ y = z ◇ ((y ◇ w) ◇ z)
equation 3614 := x ◇ y = z ◇ ((y ◇ w) ◇ w)
equation 3615 := x ◇ y = z ◇ ((y ◇ w) ◇ u)
equation 3616 := x ◇ y = z ◇ ((z ◇ x) ◇ x)
equation 3617 := x ◇ y = z ◇ ((z ◇ x) ◇ y)
equation 3618 := x ◇ y = z ◇ ((z ◇ x) ◇ z)
equation 3619 := x ◇ y = z ◇ ((z ◇ x) ◇ w)
equation 3620 := x ◇ y = z ◇ ((z ◇ y) ◇ x)
equation 3621 := x ◇ y = z ◇ ((z ◇ y) ◇ y)
equation 3622 := x ◇ y = z ◇ ((z ◇ y) ◇ z)
equation 3623 := x ◇ y = z ◇ ((z ◇ y) ◇ w)
equation 3624 := x ◇ y = z ◇ ((z ◇ z) ◇ x)
equation 3625 := x ◇ y = z ◇ ((z ◇ z) ◇ y)
equation 3626 := x ◇ y = z ◇ ((z ◇ z) ◇ z)
equation 3627 := x ◇ y = z ◇ ((z ◇ z) ◇ w)
equation 3628 := x ◇ y = z ◇ ((z ◇ w) ◇ x)
equation 3629 := x ◇ y = z ◇ ((z ◇ w) ◇ y)
equation 3630 := x ◇ y = z ◇ ((z ◇ w) ◇ z)
equation 3631 := x ◇ y = z ◇ ((z ◇ w) ◇ w)
equation 3632 := x ◇ y = z ◇ ((z ◇ w) ◇ u)
equation 3633 := x ◇ y = z ◇ ((w ◇ x) ◇ x)
equation 3634 := x ◇ y = z ◇ ((w ◇ x) ◇ y)
equation 3635 := x ◇ y = z ◇ ((w ◇ x) ◇ z)
equation 3636 := x ◇ y = z ◇ ((w ◇ x) ◇ w)
equation 3637 := x ◇ y = z ◇ ((w ◇ x) ◇ u)
equation 3638 := x ◇ y = z ◇ ((w ◇ y) ◇ x)
equation 3639 := x ◇ y = z ◇ ((w ◇ y) ◇ y)
equation 3640 := x ◇ y = z ◇ ((w ◇ y) ◇ z)
equation 3641 := x ◇ y = z ◇ ((w ◇ y) ◇ w)
equation 3642 := x ◇ y = z ◇ ((w ◇ y) ◇ u)
equation 3643 := x ◇ y = z ◇ ((w ◇ z) ◇ x)
equation 3644 := x ◇ y = z ◇ ((w ◇ z) ◇ y)
equation 3645 := x ◇ y = z ◇ ((w ◇ z) ◇ z)
equation 3646 := x ◇ y = z ◇ ((w ◇ z) ◇ w)
equation 3647 := x ◇ y = z ◇ ((w ◇ z) ◇ u)
equation 3648 := x ◇ y = z ◇ ((w ◇ w) ◇ x)
equation 3649 := x ◇ y = z ◇ ((w ◇ w) ◇ y)
equation 3650 := x ◇ y = z ◇ ((w ◇ w) ◇ z)
equation 3651 := x ◇ y = z ◇ ((w ◇ w) ◇ w)
equation 3652 := x ◇ y = z ◇ ((w ◇ w) ◇ u)
equation 3653 := x ◇ y = z ◇ ((w ◇ u) ◇ x)
equation 3654 := x ◇ y = z ◇ ((w ◇ u) ◇ y)
equation 3655 := x ◇ y = z ◇ ((w ◇ u) ◇ z)
equation 3656 := x ◇ y = z ◇ ((w ◇ u) ◇ w)
equation 3657 := x ◇ y = z ◇ ((w ◇ u) ◇ u)
equation 3658 := x ◇ y = z ◇ ((w ◇ u) ◇ v)
equation 3659 := x ◇ x = (x ◇ x) ◇ (x ◇ x)
equation 3660 := x ◇ x = (x ◇ x) ◇ (x ◇ y)
equation 3661 := x ◇ x = (x ◇ x) ◇ (y ◇ x)
equation 3662 := x ◇ x = (x ◇ x) ◇ (y ◇ y)
equation 3663 := x ◇ x = (x ◇ x) ◇ (y ◇ z)
equation 3664 := x ◇ x = (x ◇ y) ◇ (x ◇ x)
equation 3665 := x ◇ x = (x ◇ y) ◇ (x ◇ y)
equation 3666 := x ◇ x = (x ◇ y) ◇ (x ◇ z)
equation 3667 := x ◇ x = (x ◇ y) ◇ (y ◇ x)
equation 3668 := x ◇ x = (x ◇ y) ◇ (y ◇ y)
equation 3669 := x ◇ x = (x ◇ y) ◇ (y ◇ z)
equation 3670 := x ◇ x = (x ◇ y) ◇ (z ◇ x)
equation 3671 := x ◇ x = (x ◇ y) ◇ (z ◇ y)
equation 3672 := x ◇ x = (x ◇ y) ◇ (z ◇ z)
equation 3673 := x ◇ x = (x ◇ y) ◇ (z ◇ w)
equation 3674 := x ◇ x = (y ◇ x) ◇ (x ◇ x)
equation 3675 := x ◇ x = (y ◇ x) ◇ (x ◇ y)
equation 3676 := x ◇ x = (y ◇ x) ◇ (x ◇ z)
equation 3677 := x ◇ x = (y ◇ x) ◇ (y ◇ x)
equation 3678 := x ◇ x = (y ◇ x) ◇ (y ◇ y)
equation 3679 := x ◇ x = (y ◇ x) ◇ (y ◇ z)
equation 3680 := x ◇ x = (y ◇ x) ◇ (z ◇ x)
equation 3681 := x ◇ x = (y ◇ x) ◇ (z ◇ y)
equation 3682 := x ◇ x = (y ◇ x) ◇ (z ◇ z)
equation 3683 := x ◇ x = (y ◇ x) ◇ (z ◇ w)
equation 3684 := x ◇ x = (y ◇ y) ◇ (x ◇ x)
equation 3685 := x ◇ x = (y ◇ y) ◇ (x ◇ y)
equation 3686 := x ◇ x = (y ◇ y) ◇ (x ◇ z)
equation 3687 := x ◇ x = (y ◇ y) ◇ (y ◇ x)
equation 3688 := x ◇ x = (y ◇ y) ◇ (y ◇ y)
equation 3689 := x ◇ x = (y ◇ y) ◇ (y ◇ z)
equation 3690 := x ◇ x = (y ◇ y) ◇ (z ◇ x)
equation 3691 := x ◇ x = (y ◇ y) ◇ (z ◇ y)
equation 3692 := x ◇ x = (y ◇ y) ◇ (z ◇ z)
equation 3693 := x ◇ x = (y ◇ y) ◇ (z ◇ w)
equation 3694 := x ◇ x = (y ◇ z) ◇ (x ◇ x)
equation 3695 := x ◇ x = (y ◇ z) ◇ (x ◇ y)
equation 3696 := x ◇ x = (y ◇ z) ◇ (x ◇ z)
equation 3697 := x ◇ x = (y ◇ z) ◇ (x ◇ w)
equation 3698 := x ◇ x = (y ◇ z) ◇ (y ◇ x)
equation 3699 := x ◇ x = (y ◇ z) ◇ (y ◇ y)
equation 3700 := x ◇ x = (y ◇ z) ◇ (y ◇ z)
equation 3701 := x ◇ x = (y ◇ z) ◇ (y ◇ w)
equation 3702 := x ◇ x = (y ◇ z) ◇ (z ◇ x)
equation 3703 := x ◇ x = (y ◇ z) ◇ (z ◇ y)
equation 3704 := x ◇ x = (y ◇ z) ◇ (z ◇ z)
equation 3705 := x ◇ x = (y ◇ z) ◇ (z ◇ w)
equation 3706 := x ◇ x = (y ◇ z) ◇ (w ◇ x)
equation 3707 := x ◇ x = (y ◇ z) ◇ (w ◇ y)
equation 3708 := x ◇ x = (y ◇ z) ◇ (w ◇ z)
equation 3709 := x ◇ x = (y ◇ z) ◇ (w ◇ w)
equation 3710 := x ◇ x = (y ◇ z) ◇ (w ◇ u)
equation 3711 := x ◇ y = (x ◇ x) ◇ (x ◇ x)
equation 3712 := x ◇ y = (x ◇ x) ◇ (x ◇ y)
equation 3713 := x ◇ y = (x ◇ x) ◇ (x ◇ z)
equation 3714 := x ◇ y = (x ◇ x) ◇ (y ◇ x)
equation 3715 := x ◇ y = (x ◇ x) ◇ (y ◇ y)
equation 3716 := x ◇ y = (x ◇ x) ◇ (y ◇ z)
equation 3717 := x ◇ y = (x ◇ x) ◇ (z ◇ x)
equation 3718 := x ◇ y = (x ◇ x) ◇ (z ◇ y)
equation 3719 := x ◇ y = (x ◇ x) ◇ (z ◇ z)
equation 3720 := x ◇ y = (x ◇ x) ◇ (z ◇ w)
equation 3721 := x ◇ y = (x ◇ y) ◇ (x ◇ x)
-- equation 3722 := x ◇ y = (x ◇ y) ◇ (x ◇ y)
equation 3723 := x ◇ y = (x ◇ y) ◇ (x ◇ z)
equation 3724 := x ◇ y = (x ◇ y) ◇ (y ◇ x)
equation 3725 := x ◇ y = (x ◇ y) ◇ (y ◇ y)
equation 3726 := x ◇ y = (x ◇ y) ◇ (y ◇ z)
equation 3727 := x ◇ y = (x ◇ y) ◇ (z ◇ x)
equation 3728 := x ◇ y = (x ◇ y) ◇ (z ◇ y)
equation 3729 := x ◇ y = (x ◇ y) ◇ (z ◇ z)
equation 3730 := x ◇ y = (x ◇ y) ◇ (z ◇ w)
equation 3731 := x ◇ y = (x ◇ z) ◇ (x ◇ x)
equation 3732 := x ◇ y = (x ◇ z) ◇ (x ◇ y)
equation 3733 := x ◇ y = (x ◇ z) ◇ (x ◇ z)
equation 3734 := x ◇ y = (x ◇ z) ◇ (x ◇ w)
equation 3735 := x ◇ y = (x ◇ z) ◇ (y ◇ x)
equation 3736 := x ◇ y = (x ◇ z) ◇ (y ◇ y)
equation 3737 := x ◇ y = (x ◇ z) ◇ (y ◇ z)
equation 3738 := x ◇ y = (x ◇ z) ◇ (y ◇ w)
equation 3739 := x ◇ y = (x ◇ z) ◇ (z ◇ x)
equation 3740 := x ◇ y = (x ◇ z) ◇ (z ◇ y)
equation 3741 := x ◇ y = (x ◇ z) ◇ (z ◇ z)
equation 3742 := x ◇ y = (x ◇ z) ◇ (z ◇ w)
equation 3743 := x ◇ y = (x ◇ z) ◇ (w ◇ x)
-- equation 3744 := x ◇ y = (x ◇ z) ◇ (w ◇ y)
equation 3745 := x ◇ y = (x ◇ z) ◇ (w ◇ z)
equation 3746 := x ◇ y = (x ◇ z) ◇ (w ◇ w)
equation 3747 := x ◇ y = (x ◇ z) ◇ (w ◇ u)
equation 3748 := x ◇ y = (y ◇ x) ◇ (x ◇ x)
equation 3749 := x ◇ y = (y ◇ x) ◇ (x ◇ y)
equation 3750 := x ◇ y = (y ◇ x) ◇ (x ◇ z)
equation 3751 := x ◇ y = (y ◇ x) ◇ (y ◇ x)
equation 3752 := x ◇ y = (y ◇ x) ◇ (y ◇ y)
equation 3753 := x ◇ y = (y ◇ x) ◇ (y ◇ z)
equation 3754 := x ◇ y = (y ◇ x) ◇ (z ◇ x)
equation 3755 := x ◇ y = (y ◇ x) ◇ (z ◇ y)
equation 3756 := x ◇ y = (y ◇ x) ◇ (z ◇ z)
equation 3757 := x ◇ y = (y ◇ x) ◇ (z ◇ w)
equation 3758 := x ◇ y = (y ◇ y) ◇ (x ◇ x)
equation 3759 := x ◇ y = (y ◇ y) ◇ (x ◇ y)
equation 3760 := x ◇ y = (y ◇ y) ◇ (x ◇ z)
equation 3761 := x ◇ y = (y ◇ y) ◇ (y ◇ x)
equation 3762 := x ◇ y = (y ◇ y) ◇ (y ◇ y)
equation 3763 := x ◇ y = (y ◇ y) ◇ (y ◇ z)
equation 3764 := x ◇ y = (y ◇ y) ◇ (z ◇ x)
equation 3765 := x ◇ y = (y ◇ y) ◇ (z ◇ y)
equation 3766 := x ◇ y = (y ◇ y) ◇ (z ◇ z)
equation 3767 := x ◇ y = (y ◇ y) ◇ (z ◇ w)
equation 3768 := x ◇ y = (y ◇ z) ◇ (x ◇ x)
equation 3769 := x ◇ y = (y ◇ z) ◇ (x ◇ y)
equation 3770 := x ◇ y = (y ◇ z) ◇ (x ◇ z)
equation 3771 := x ◇ y = (y ◇ z) ◇ (x ◇ w)
equation 3772 := x ◇ y = (y ◇ z) ◇ (y ◇ x)
equation 3773 := x ◇ y = (y ◇ z) ◇ (y ◇ y)
equation 3774 := x ◇ y = (y ◇ z) ◇ (y ◇ z)
equation 3775 := x ◇ y = (y ◇ z) ◇ (y ◇ w)
equation 3776 := x ◇ y = (y ◇ z) ◇ (z ◇ x)
equation 3777 := x ◇ y = (y ◇ z) ◇ (z ◇ y)
equation 3778 := x ◇ y = (y ◇ z) ◇ (z ◇ z)
equation 3779 := x ◇ y = (y ◇ z) ◇ (z ◇ w)
equation 3780 := x ◇ y = (y ◇ z) ◇ (w ◇ x)
equation 3781 := x ◇ y = (y ◇ z) ◇ (w ◇ y)
equation 3782 := x ◇ y = (y ◇ z) ◇ (w ◇ z)
equation 3783 := x ◇ y = (y ◇ z) ◇ (w ◇ w)
equation 3784 := x ◇ y = (y ◇ z) ◇ (w ◇ u)
equation 3785 := x ◇ y = (z ◇ x) ◇ (x ◇ x)
equation 3786 := x ◇ y = (z ◇ x) ◇ (x ◇ y)
equation 3787 := x ◇ y = (z ◇ x) ◇ (x ◇ z)
equation 3788 := x ◇ y = (z ◇ x) ◇ (x ◇ w)
equation 3789 := x ◇ y = (z ◇ x) ◇ (y ◇ x)
equation 3790 := x ◇ y = (z ◇ x) ◇ (y ◇ y)
equation 3791 := x ◇ y = (z ◇ x) ◇ (y ◇ z)
equation 3792 := x ◇ y = (z ◇ x) ◇ (y ◇ w)
equation 3793 := x ◇ y = (z ◇ x) ◇ (z ◇ x)
equation 3794 := x ◇ y = (z ◇ x) ◇ (z ◇ y)
equation 3795 := x ◇ y = (z ◇ x) ◇ (z ◇ z)
equation 3796 := x ◇ y = (z ◇ x) ◇ (z ◇ w)
equation 3797 := x ◇ y = (z ◇ x) ◇ (w ◇ x)
equation 3798 := x ◇ y = (z ◇ x) ◇ (w ◇ y)
equation 3799 := x ◇ y = (z ◇ x) ◇ (w ◇ z)
equation 3800 := x ◇ y = (z ◇ x) ◇ (w ◇ w)
equation 3801 := x ◇ y = (z ◇ x) ◇ (w ◇ u)
equation 3802 := x ◇ y = (z ◇ y) ◇ (x ◇ x)
equation 3803 := x ◇ y = (z ◇ y) ◇ (x ◇ y)
equation 3804 := x ◇ y = (z ◇ y) ◇ (x ◇ z)
equation 3805 := x ◇ y = (z ◇ y) ◇ (x ◇ w)
equation 3806 := x ◇ y = (z ◇ y) ◇ (y ◇ x)
equation 3807 := x ◇ y = (z ◇ y) ◇ (y ◇ y)
equation 3808 := x ◇ y = (z ◇ y) ◇ (y ◇ z)
equation 3809 := x ◇ y = (z ◇ y) ◇ (y ◇ w)
equation 3810 := x ◇ y = (z ◇ y) ◇ (z ◇ x)
equation 3811 := x ◇ y = (z ◇ y) ◇ (z ◇ y)
equation 3812 := x ◇ y = (z ◇ y) ◇ (z ◇ z)
equation 3813 := x ◇ y = (z ◇ y) ◇ (z ◇ w)
equation 3814 := x ◇ y = (z ◇ y) ◇ (w ◇ x)
equation 3815 := x ◇ y = (z ◇ y) ◇ (w ◇ y)
equation 3816 := x ◇ y = (z ◇ y) ◇ (w ◇ z)
equation 3817 := x ◇ y = (z ◇ y) ◇ (w ◇ w)
equation 3818 := x ◇ y = (z ◇ y) ◇ (w ◇ u)
equation 3819 := x ◇ y = (z ◇ z) ◇ (x ◇ x)
equation 3820 := x ◇ y = (z ◇ z) ◇ (x ◇ y)
equation 3821 := x ◇ y = (z ◇ z) ◇ (x ◇ z)
equation 3822 := x ◇ y = (z ◇ z) ◇ (x ◇ w)
equation 3823 := x ◇ y = (z ◇ z) ◇ (y ◇ x)
equation 3824 := x ◇ y = (z ◇ z) ◇ (y ◇ y)
equation 3825 := x ◇ y = (z ◇ z) ◇ (y ◇ z)
equation 3826 := x ◇ y = (z ◇ z) ◇ (y ◇ w)
equation 3827 := x ◇ y = (z ◇ z) ◇ (z ◇ x)
equation 3828 := x ◇ y = (z ◇ z) ◇ (z ◇ y)
equation 3829 := x ◇ y = (z ◇ z) ◇ (z ◇ z)
equation 3830 := x ◇ y = (z ◇ z) ◇ (z ◇ w)
equation 3831 := x ◇ y = (z ◇ z) ◇ (w ◇ x)
equation 3832 := x ◇ y = (z ◇ z) ◇ (w ◇ y)
equation 3833 := x ◇ y = (z ◇ z) ◇ (w ◇ z)
equation 3834 := x ◇ y = (z ◇ z) ◇ (w ◇ w)
equation 3835 := x ◇ y = (z ◇ z) ◇ (w ◇ u)
equation 3836 := x ◇ y = (z ◇ w) ◇ (x ◇ x)
equation 3837 := x ◇ y = (z ◇ w) ◇ (x ◇ y)
equation 3838 := x ◇ y = (z ◇ w) ◇ (x ◇ z)
equation 3839 := x ◇ y = (z ◇ w) ◇ (x ◇ w)
equation 3840 := x ◇ y = (z ◇ w) ◇ (x ◇ u)
equation 3841 := x ◇ y = (z ◇ w) ◇ (y ◇ x)
equation 3842 := x ◇ y = (z ◇ w) ◇ (y ◇ y)
equation 3843 := x ◇ y = (z ◇ w) ◇ (y ◇ z)
equation 3844 := x ◇ y = (z ◇ w) ◇ (y ◇ w)
equation 3845 := x ◇ y = (z ◇ w) ◇ (y ◇ u)
equation 3846 := x ◇ y = (z ◇ w) ◇ (z ◇ x)
equation 3847 := x ◇ y = (z ◇ w) ◇ (z ◇ y)
equation 3848 := x ◇ y = (z ◇ w) ◇ (z ◇ z)
equation 3849 := x ◇ y = (z ◇ w) ◇ (z ◇ w)
equation 3850 := x ◇ y = (z ◇ w) ◇ (z ◇ u)
equation 3851 := x ◇ y = (z ◇ w) ◇ (w ◇ x)
equation 3852 := x ◇ y = (z ◇ w) ◇ (w ◇ y)
equation 3853 := x ◇ y = (z ◇ w) ◇ (w ◇ z)
equation 3854 := x ◇ y = (z ◇ w) ◇ (w ◇ w)
equation 3855 := x ◇ y = (z ◇ w) ◇ (w ◇ u)
equation 3856 := x ◇ y = (z ◇ w) ◇ (u ◇ x)
equation 3857 := x ◇ y = (z ◇ w) ◇ (u ◇ y)
equation 3858 := x ◇ y = (z ◇ w) ◇ (u ◇ z)
equation 3859 := x ◇ y = (z ◇ w) ◇ (u ◇ w)
equation 3860 := x ◇ y = (z ◇ w) ◇ (u ◇ u)
equation 3861 := x ◇ y = (z ◇ w) ◇ (u ◇ v)
equation 3862 := x ◇ x = (x ◇ (x ◇ x)) ◇ x
equation 3863 := x ◇ x = (x ◇ (x ◇ x)) ◇ y
equation 3864 := x ◇ x = (x ◇ (x ◇ y)) ◇ x
equation 3865 := x ◇ x = (x ◇ (x ◇ y)) ◇ y
equation 3866 := x ◇ x = (x ◇ (x ◇ y)) ◇ z
equation 3867 := x ◇ x = (x ◇ (y ◇ x)) ◇ x
equation 3868 := x ◇ x = (x ◇ (y ◇ x)) ◇ y
equation 3869 := x ◇ x = (x ◇ (y ◇ x)) ◇ z
equation 3870 := x ◇ x = (x ◇ (y ◇ y)) ◇ x
equation 3871 := x ◇ x = (x ◇ (y ◇ y)) ◇ y
equation 3872 := x ◇ x = (x ◇ (y ◇ y)) ◇ z
equation 3873 := x ◇ x = (x ◇ (y ◇ z)) ◇ x
equation 3874 := x ◇ x = (x ◇ (y ◇ z)) ◇ y
equation 3875 := x ◇ x = (x ◇ (y ◇ z)) ◇ z
equation 3876 := x ◇ x = (x ◇ (y ◇ z)) ◇ w
equation 3877 := x ◇ x = (y ◇ (x ◇ x)) ◇ x
equation 3878 := x ◇ x = (y ◇ (x ◇ x)) ◇ y
equation 3879 := x ◇ x = (y ◇ (x ◇ x)) ◇ z
equation 3880 := x ◇ x = (y ◇ (x ◇ y)) ◇ x
equation 3881 := x ◇ x = (y ◇ (x ◇ y)) ◇ y
equation 3882 := x ◇ x = (y ◇ (x ◇ y)) ◇ z
equation 3883 := x ◇ x = (y ◇ (x ◇ z)) ◇ x
equation 3884 := x ◇ x = (y ◇ (x ◇ z)) ◇ y
equation 3885 := x ◇ x = (y ◇ (x ◇ z)) ◇ z
equation 3886 := x ◇ x = (y ◇ (x ◇ z)) ◇ w
equation 3887 := x ◇ x = (y ◇ (y ◇ x)) ◇ x
equation 3888 := x ◇ x = (y ◇ (y ◇ x)) ◇ y
equation 3889 := x ◇ x = (y ◇ (y ◇ x)) ◇ z
equation 3890 := x ◇ x = (y ◇ (y ◇ y)) ◇ x
equation 3891 := x ◇ x = (y ◇ (y ◇ y)) ◇ y
equation 3892 := x ◇ x = (y ◇ (y ◇ y)) ◇ z
equation 3893 := x ◇ x = (y ◇ (y ◇ z)) ◇ x
equation 3894 := x ◇ x = (y ◇ (y ◇ z)) ◇ y
equation 3895 := x ◇ x = (y ◇ (y ◇ z)) ◇ z
equation 3896 := x ◇ x = (y ◇ (y ◇ z)) ◇ w
equation 3897 := x ◇ x = (y ◇ (z ◇ x)) ◇ x
equation 3898 := x ◇ x = (y ◇ (z ◇ x)) ◇ y
equation 3899 := x ◇ x = (y ◇ (z ◇ x)) ◇ z
equation 3900 := x ◇ x = (y ◇ (z ◇ x)) ◇ w
equation 3901 := x ◇ x = (y ◇ (z ◇ y)) ◇ x
equation 3902 := x ◇ x = (y ◇ (z ◇ y)) ◇ y
equation 3903 := x ◇ x = (y ◇ (z ◇ y)) ◇ z
equation 3904 := x ◇ x = (y ◇ (z ◇ y)) ◇ w
equation 3905 := x ◇ x = (y ◇ (z ◇ z)) ◇ x
equation 3906 := x ◇ x = (y ◇ (z ◇ z)) ◇ y
equation 3907 := x ◇ x = (y ◇ (z ◇ z)) ◇ z
equation 3908 := x ◇ x = (y ◇ (z ◇ z)) ◇ w
equation 3909 := x ◇ x = (y ◇ (z ◇ w)) ◇ x
equation 3910 := x ◇ x = (y ◇ (z ◇ w)) ◇ y
equation 3911 := x ◇ x = (y ◇ (z ◇ w)) ◇ z
equation 3912 := x ◇ x = (y ◇ (z ◇ w)) ◇ w
equation 3913 := x ◇ x = (y ◇ (z ◇ w)) ◇ u
equation 3914 := x ◇ y = (x ◇ (x ◇ x)) ◇ x
equation 3915 := x ◇ y = (x ◇ (x ◇ x)) ◇ y
equation 3916 := x ◇ y = (x ◇ (x ◇ x)) ◇ z
equation 3917 := x ◇ y = (x ◇ (x ◇ y)) ◇ x
equation 3918 := x ◇ y = (x ◇ (x ◇ y)) ◇ y
equation 3919 := x ◇ y = (x ◇ (x ◇ y)) ◇ z
equation 3920 := x ◇ y = (x ◇ (x ◇ z)) ◇ x
equation 3921 := x ◇ y = (x ◇ (x ◇ z)) ◇ y
equation 3922 := x ◇ y = (x ◇ (x ◇ z)) ◇ z
equation 3923 := x ◇ y = (x ◇ (x ◇ z)) ◇ w
equation 3924 := x ◇ y = (x ◇ (y ◇ x)) ◇ x
equation 3925 := x ◇ y = (x ◇ (y ◇ x)) ◇ y
equation 3926 := x ◇ y = (x ◇ (y ◇ x)) ◇ z
equation 3927 := x ◇ y = (x ◇ (y ◇ y)) ◇ x
equation 3928 := x ◇ y = (x ◇ (y ◇ y)) ◇ y
equation 3929 := x ◇ y = (x ◇ (y ◇ y)) ◇ z
equation 3930 := x ◇ y = (x ◇ (y ◇ z)) ◇ x
equation 3931 := x ◇ y = (x ◇ (y ◇ z)) ◇ y
equation 3932 := x ◇ y = (x ◇ (y ◇ z)) ◇ z
equation 3933 := x ◇ y = (x ◇ (y ◇ z)) ◇ w
equation 3934 := x ◇ y = (x ◇ (z ◇ x)) ◇ x
equation 3935 := x ◇ y = (x ◇ (z ◇ x)) ◇ y
equation 3936 := x ◇ y = (x ◇ (z ◇ x)) ◇ z
equation 3937 := x ◇ y = (x ◇ (z ◇ x)) ◇ w
equation 3938 := x ◇ y = (x ◇ (z ◇ y)) ◇ x
equation 3939 := x ◇ y = (x ◇ (z ◇ y)) ◇ y
equation 3940 := x ◇ y = (x ◇ (z ◇ y)) ◇ z
equation 3941 := x ◇ y = (x ◇ (z ◇ y)) ◇ w
equation 3942 := x ◇ y = (x ◇ (z ◇ z)) ◇ x
equation 3943 := x ◇ y = (x ◇ (z ◇ z)) ◇ y
equation 3944 := x ◇ y = (x ◇ (z ◇ z)) ◇ z
equation 3945 := x ◇ y = (x ◇ (z ◇ z)) ◇ w
equation 3946 := x ◇ y = (x ◇ (z ◇ w)) ◇ x
equation 3947 := x ◇ y = (x ◇ (z ◇ w)) ◇ y
equation 3948 := x ◇ y = (x ◇ (z ◇ w)) ◇ z
equation 3949 := x ◇ y = (x ◇ (z ◇ w)) ◇ w
equation 3950 := x ◇ y = (x ◇ (z ◇ w)) ◇ u
equation 3951 := x ◇ y = (y ◇ (x ◇ x)) ◇ x
equation 3952 := x ◇ y = (y ◇ (x ◇ x)) ◇ y
equation 3953 := x ◇ y = (y ◇ (x ◇ x)) ◇ z
equation 3954 := x ◇ y = (y ◇ (x ◇ y)) ◇ x
equation 3955 := x ◇ y = (y ◇ (x ◇ y)) ◇ y
equation 3956 := x ◇ y = (y ◇ (x ◇ y)) ◇ z
equation 3957 := x ◇ y = (y ◇ (x ◇ z)) ◇ x
equation 3958 := x ◇ y = (y ◇ (x ◇ z)) ◇ y
equation 3959 := x ◇ y = (y ◇ (x ◇ z)) ◇ z
equation 3960 := x ◇ y = (y ◇ (x ◇ z)) ◇ w
equation 3961 := x ◇ y = (y ◇ (y ◇ x)) ◇ x
equation 3962 := x ◇ y = (y ◇ (y ◇ x)) ◇ y
equation 3963 := x ◇ y = (y ◇ (y ◇ x)) ◇ z
equation 3964 := x ◇ y = (y ◇ (y ◇ y)) ◇ x
equation 3965 := x ◇ y = (y ◇ (y ◇ y)) ◇ y
equation 3966 := x ◇ y = (y ◇ (y ◇ y)) ◇ z
equation 3967 := x ◇ y = (y ◇ (y ◇ z)) ◇ x
equation 3968 := x ◇ y = (y ◇ (y ◇ z)) ◇ y
equation 3969 := x ◇ y = (y ◇ (y ◇ z)) ◇ z
equation 3970 := x ◇ y = (y ◇ (y ◇ z)) ◇ w
equation 3971 := x ◇ y = (y ◇ (z ◇ x)) ◇ x
equation 3972 := x ◇ y = (y ◇ (z ◇ x)) ◇ y
equation 3973 := x ◇ y = (y ◇ (z ◇ x)) ◇ z
equation 3974 := x ◇ y = (y ◇ (z ◇ x)) ◇ w
equation 3975 := x ◇ y = (y ◇ (z ◇ y)) ◇ x
equation 3976 := x ◇ y = (y ◇ (z ◇ y)) ◇ y
equation 3977 := x ◇ y = (y ◇ (z ◇ y)) ◇ z
equation 3978 := x ◇ y = (y ◇ (z ◇ y)) ◇ w
equation 3979 := x ◇ y = (y ◇ (z ◇ z)) ◇ x
equation 3980 := x ◇ y = (y ◇ (z ◇ z)) ◇ y
equation 3981 := x ◇ y = (y ◇ (z ◇ z)) ◇ z
equation 3982 := x ◇ y = (y ◇ (z ◇ z)) ◇ w
equation 3983 := x ◇ y = (y ◇ (z ◇ w)) ◇ x
equation 3984 := x ◇ y = (y ◇ (z ◇ w)) ◇ y
equation 3985 := x ◇ y = (y ◇ (z ◇ w)) ◇ z
equation 3986 := x ◇ y = (y ◇ (z ◇ w)) ◇ w
equation 3987 := x ◇ y = (y ◇ (z ◇ w)) ◇ u
equation 3988 := x ◇ y = (z ◇ (x ◇ x)) ◇ x
equation 3989 := x ◇ y = (z ◇ (x ◇ x)) ◇ y
equation 3990 := x ◇ y = (z ◇ (x ◇ x)) ◇ z
equation 3991 := x ◇ y = (z ◇ (x ◇ x)) ◇ w
equation 3992 := x ◇ y = (z ◇ (x ◇ y)) ◇ x
equation 3993 := x ◇ y = (z ◇ (x ◇ y)) ◇ y
equation 3994 := x ◇ y = (z ◇ (x ◇ y)) ◇ z
equation 3995 := x ◇ y = (z ◇ (x ◇ y)) ◇ w
equation 3996 := x ◇ y = (z ◇ (x ◇ z)) ◇ x
equation 3997 := x ◇ y = (z ◇ (x ◇ z)) ◇ y
equation 3998 := x ◇ y = (z ◇ (x ◇ z)) ◇ z
equation 3999 := x ◇ y = (z ◇ (x ◇ z)) ◇ w
