import equational_theories.Magma
import equational_theories.Equations.Command

/-! Equations list, numbers 2000-2999 -/

equation 2000 := x = (y ◇ (z ◇ z)) ◇ (z ◇ x)
equation 2001 := x = (y ◇ (z ◇ z)) ◇ (z ◇ y)
equation 2002 := x = (y ◇ (z ◇ z)) ◇ (z ◇ z)
equation 2003 := x = (y ◇ (z ◇ z)) ◇ (z ◇ w)
equation 2004 := x = (y ◇ (z ◇ z)) ◇ (w ◇ x)
equation 2005 := x = (y ◇ (z ◇ z)) ◇ (w ◇ y)
equation 2006 := x = (y ◇ (z ◇ z)) ◇ (w ◇ z)
equation 2007 := x = (y ◇ (z ◇ z)) ◇ (w ◇ w)
equation 2008 := x = (y ◇ (z ◇ z)) ◇ (w ◇ u)
equation 2009 := x = (y ◇ (z ◇ w)) ◇ (x ◇ x)
equation 2010 := x = (y ◇ (z ◇ w)) ◇ (x ◇ y)
equation 2011 := x = (y ◇ (z ◇ w)) ◇ (x ◇ z)
equation 2012 := x = (y ◇ (z ◇ w)) ◇ (x ◇ w)
equation 2013 := x = (y ◇ (z ◇ w)) ◇ (x ◇ u)
equation 2014 := x = (y ◇ (z ◇ w)) ◇ (y ◇ x)
equation 2015 := x = (y ◇ (z ◇ w)) ◇ (y ◇ y)
equation 2016 := x = (y ◇ (z ◇ w)) ◇ (y ◇ z)
equation 2017 := x = (y ◇ (z ◇ w)) ◇ (y ◇ w)
equation 2018 := x = (y ◇ (z ◇ w)) ◇ (y ◇ u)
equation 2019 := x = (y ◇ (z ◇ w)) ◇ (z ◇ x)
equation 2020 := x = (y ◇ (z ◇ w)) ◇ (z ◇ y)
equation 2021 := x = (y ◇ (z ◇ w)) ◇ (z ◇ z)
equation 2022 := x = (y ◇ (z ◇ w)) ◇ (z ◇ w)
equation 2023 := x = (y ◇ (z ◇ w)) ◇ (z ◇ u)
equation 2024 := x = (y ◇ (z ◇ w)) ◇ (w ◇ x)
equation 2025 := x = (y ◇ (z ◇ w)) ◇ (w ◇ y)
equation 2026 := x = (y ◇ (z ◇ w)) ◇ (w ◇ z)
equation 2027 := x = (y ◇ (z ◇ w)) ◇ (w ◇ w)
equation 2028 := x = (y ◇ (z ◇ w)) ◇ (w ◇ u)
equation 2029 := x = (y ◇ (z ◇ w)) ◇ (u ◇ x)
equation 2030 := x = (y ◇ (z ◇ w)) ◇ (u ◇ y)
equation 2031 := x = (y ◇ (z ◇ w)) ◇ (u ◇ z)
equation 2032 := x = (y ◇ (z ◇ w)) ◇ (u ◇ w)
equation 2033 := x = (y ◇ (z ◇ w)) ◇ (u ◇ u)
equation 2034 := x = (y ◇ (z ◇ w)) ◇ (u ◇ v)
equation 2035 := x = ((x ◇ x) ◇ x) ◇ (x ◇ x)
equation 2036 := x = ((x ◇ x) ◇ x) ◇ (x ◇ y)
equation 2037 := x = ((x ◇ x) ◇ x) ◇ (y ◇ x)
equation 2038 := x = ((x ◇ x) ◇ x) ◇ (y ◇ y)
equation 2039 := x = ((x ◇ x) ◇ x) ◇ (y ◇ z)
equation 2040 := x = ((x ◇ x) ◇ y) ◇ (x ◇ x)
equation 2041 := x = ((x ◇ x) ◇ y) ◇ (x ◇ y)
equation 2042 := x = ((x ◇ x) ◇ y) ◇ (x ◇ z)
equation 2043 := x = ((x ◇ x) ◇ y) ◇ (y ◇ x)
equation 2044 := x = ((x ◇ x) ◇ y) ◇ (y ◇ y)
equation 2045 := x = ((x ◇ x) ◇ y) ◇ (y ◇ z)
equation 2046 := x = ((x ◇ x) ◇ y) ◇ (z ◇ x)
equation 2047 := x = ((x ◇ x) ◇ y) ◇ (z ◇ y)
equation 2048 := x = ((x ◇ x) ◇ y) ◇ (z ◇ z)
equation 2049 := x = ((x ◇ x) ◇ y) ◇ (z ◇ w)
equation 2050 := x = ((x ◇ y) ◇ x) ◇ (x ◇ x)
equation 2051 := x = ((x ◇ y) ◇ x) ◇ (x ◇ y)
equation 2052 := x = ((x ◇ y) ◇ x) ◇ (x ◇ z)
equation 2053 := x = ((x ◇ y) ◇ x) ◇ (y ◇ x)
equation 2054 := x = ((x ◇ y) ◇ x) ◇ (y ◇ y)
equation 2055 := x = ((x ◇ y) ◇ x) ◇ (y ◇ z)
equation 2056 := x = ((x ◇ y) ◇ x) ◇ (z ◇ x)
equation 2057 := x = ((x ◇ y) ◇ x) ◇ (z ◇ y)
equation 2058 := x = ((x ◇ y) ◇ x) ◇ (z ◇ z)
equation 2059 := x = ((x ◇ y) ◇ x) ◇ (z ◇ w)
equation 2060 := x = ((x ◇ y) ◇ y) ◇ (x ◇ x)
equation 2061 := x = ((x ◇ y) ◇ y) ◇ (x ◇ y)
equation 2062 := x = ((x ◇ y) ◇ y) ◇ (x ◇ z)
equation 2063 := x = ((x ◇ y) ◇ y) ◇ (y ◇ x)
equation 2064 := x = ((x ◇ y) ◇ y) ◇ (y ◇ y)
equation 2065 := x = ((x ◇ y) ◇ y) ◇ (y ◇ z)
equation 2066 := x = ((x ◇ y) ◇ y) ◇ (z ◇ x)
equation 2067 := x = ((x ◇ y) ◇ y) ◇ (z ◇ y)
equation 2068 := x = ((x ◇ y) ◇ y) ◇ (z ◇ z)
equation 2069 := x = ((x ◇ y) ◇ y) ◇ (z ◇ w)
equation 2070 := x = ((x ◇ y) ◇ z) ◇ (x ◇ x)
equation 2071 := x = ((x ◇ y) ◇ z) ◇ (x ◇ y)
equation 2072 := x = ((x ◇ y) ◇ z) ◇ (x ◇ z)
equation 2073 := x = ((x ◇ y) ◇ z) ◇ (x ◇ w)
equation 2074 := x = ((x ◇ y) ◇ z) ◇ (y ◇ x)
equation 2075 := x = ((x ◇ y) ◇ z) ◇ (y ◇ y)
equation 2076 := x = ((x ◇ y) ◇ z) ◇ (y ◇ z)
equation 2077 := x = ((x ◇ y) ◇ z) ◇ (y ◇ w)
equation 2078 := x = ((x ◇ y) ◇ z) ◇ (z ◇ x)
equation 2079 := x = ((x ◇ y) ◇ z) ◇ (z ◇ y)
equation 2080 := x = ((x ◇ y) ◇ z) ◇ (z ◇ z)
equation 2081 := x = ((x ◇ y) ◇ z) ◇ (z ◇ w)
equation 2082 := x = ((x ◇ y) ◇ z) ◇ (w ◇ x)
equation 2083 := x = ((x ◇ y) ◇ z) ◇ (w ◇ y)
equation 2084 := x = ((x ◇ y) ◇ z) ◇ (w ◇ z)
equation 2085 := x = ((x ◇ y) ◇ z) ◇ (w ◇ w)
equation 2086 := x = ((x ◇ y) ◇ z) ◇ (w ◇ u)
equation 2087 := x = ((y ◇ x) ◇ x) ◇ (x ◇ x)
equation 2088 := x = ((y ◇ x) ◇ x) ◇ (x ◇ y)
equation 2089 := x = ((y ◇ x) ◇ x) ◇ (x ◇ z)
equation 2090 := x = ((y ◇ x) ◇ x) ◇ (y ◇ x)
equation 2091 := x = ((y ◇ x) ◇ x) ◇ (y ◇ y)
equation 2092 := x = ((y ◇ x) ◇ x) ◇ (y ◇ z)
equation 2093 := x = ((y ◇ x) ◇ x) ◇ (z ◇ x)
equation 2094 := x = ((y ◇ x) ◇ x) ◇ (z ◇ y)
equation 2095 := x = ((y ◇ x) ◇ x) ◇ (z ◇ z)
equation 2096 := x = ((y ◇ x) ◇ x) ◇ (z ◇ w)
equation 2097 := x = ((y ◇ x) ◇ y) ◇ (x ◇ x)
equation 2098 := x = ((y ◇ x) ◇ y) ◇ (x ◇ y)
equation 2099 := x = ((y ◇ x) ◇ y) ◇ (x ◇ z)
equation 2100 := x = ((y ◇ x) ◇ y) ◇ (y ◇ x)
equation 2101 := x = ((y ◇ x) ◇ y) ◇ (y ◇ y)
equation 2102 := x = ((y ◇ x) ◇ y) ◇ (y ◇ z)
equation 2103 := x = ((y ◇ x) ◇ y) ◇ (z ◇ x)
equation 2104 := x = ((y ◇ x) ◇ y) ◇ (z ◇ y)
equation 2105 := x = ((y ◇ x) ◇ y) ◇ (z ◇ z)
equation 2106 := x = ((y ◇ x) ◇ y) ◇ (z ◇ w)
equation 2107 := x = ((y ◇ x) ◇ z) ◇ (x ◇ x)
equation 2108 := x = ((y ◇ x) ◇ z) ◇ (x ◇ y)
equation 2109 := x = ((y ◇ x) ◇ z) ◇ (x ◇ z)
equation 2110 := x = ((y ◇ x) ◇ z) ◇ (x ◇ w)
equation 2111 := x = ((y ◇ x) ◇ z) ◇ (y ◇ x)
equation 2112 := x = ((y ◇ x) ◇ z) ◇ (y ◇ y)
equation 2113 := x = ((y ◇ x) ◇ z) ◇ (y ◇ z)
equation 2114 := x = ((y ◇ x) ◇ z) ◇ (y ◇ w)
equation 2115 := x = ((y ◇ x) ◇ z) ◇ (z ◇ x)
equation 2116 := x = ((y ◇ x) ◇ z) ◇ (z ◇ y)
equation 2117 := x = ((y ◇ x) ◇ z) ◇ (z ◇ z)
equation 2118 := x = ((y ◇ x) ◇ z) ◇ (z ◇ w)
equation 2119 := x = ((y ◇ x) ◇ z) ◇ (w ◇ x)
equation 2120 := x = ((y ◇ x) ◇ z) ◇ (w ◇ y)
equation 2121 := x = ((y ◇ x) ◇ z) ◇ (w ◇ z)
equation 2122 := x = ((y ◇ x) ◇ z) ◇ (w ◇ w)
equation 2123 := x = ((y ◇ x) ◇ z) ◇ (w ◇ u)
equation 2124 := x = ((y ◇ y) ◇ x) ◇ (x ◇ x)
equation 2125 := x = ((y ◇ y) ◇ x) ◇ (x ◇ y)
equation 2126 := x = ((y ◇ y) ◇ x) ◇ (x ◇ z)
equation 2127 := x = ((y ◇ y) ◇ x) ◇ (y ◇ x)
equation 2128 := x = ((y ◇ y) ◇ x) ◇ (y ◇ y)
equation 2129 := x = ((y ◇ y) ◇ x) ◇ (y ◇ z)
equation 2130 := x = ((y ◇ y) ◇ x) ◇ (z ◇ x)
equation 2131 := x = ((y ◇ y) ◇ x) ◇ (z ◇ y)
equation 2132 := x = ((y ◇ y) ◇ x) ◇ (z ◇ z)
equation 2133 := x = ((y ◇ y) ◇ x) ◇ (z ◇ w)
equation 2134 := x = ((y ◇ y) ◇ y) ◇ (x ◇ x)
equation 2135 := x = ((y ◇ y) ◇ y) ◇ (x ◇ y)
equation 2136 := x = ((y ◇ y) ◇ y) ◇ (x ◇ z)
equation 2137 := x = ((y ◇ y) ◇ y) ◇ (y ◇ x)
equation 2138 := x = ((y ◇ y) ◇ y) ◇ (y ◇ y)
equation 2139 := x = ((y ◇ y) ◇ y) ◇ (y ◇ z)
equation 2140 := x = ((y ◇ y) ◇ y) ◇ (z ◇ x)
equation 2141 := x = ((y ◇ y) ◇ y) ◇ (z ◇ y)
equation 2142 := x = ((y ◇ y) ◇ y) ◇ (z ◇ z)
equation 2143 := x = ((y ◇ y) ◇ y) ◇ (z ◇ w)
equation 2144 := x = ((y ◇ y) ◇ z) ◇ (x ◇ x)
equation 2145 := x = ((y ◇ y) ◇ z) ◇ (x ◇ y)
equation 2146 := x = ((y ◇ y) ◇ z) ◇ (x ◇ z)
equation 2147 := x = ((y ◇ y) ◇ z) ◇ (x ◇ w)
equation 2148 := x = ((y ◇ y) ◇ z) ◇ (y ◇ x)
equation 2149 := x = ((y ◇ y) ◇ z) ◇ (y ◇ y)
equation 2150 := x = ((y ◇ y) ◇ z) ◇ (y ◇ z)
equation 2151 := x = ((y ◇ y) ◇ z) ◇ (y ◇ w)
equation 2152 := x = ((y ◇ y) ◇ z) ◇ (z ◇ x)
equation 2153 := x = ((y ◇ y) ◇ z) ◇ (z ◇ y)
equation 2154 := x = ((y ◇ y) ◇ z) ◇ (z ◇ z)
equation 2155 := x = ((y ◇ y) ◇ z) ◇ (z ◇ w)
equation 2156 := x = ((y ◇ y) ◇ z) ◇ (w ◇ x)
equation 2157 := x = ((y ◇ y) ◇ z) ◇ (w ◇ y)
equation 2158 := x = ((y ◇ y) ◇ z) ◇ (w ◇ z)
equation 2159 := x = ((y ◇ y) ◇ z) ◇ (w ◇ w)
equation 2160 := x = ((y ◇ y) ◇ z) ◇ (w ◇ u)
equation 2161 := x = ((y ◇ z) ◇ x) ◇ (x ◇ x)
-- equation 2162 := x = ((y ◇ z) ◇ x) ◇ (x ◇ y)
equation 2163 := x = ((y ◇ z) ◇ x) ◇ (x ◇ z)
equation 2164 := x = ((y ◇ z) ◇ x) ◇ (x ◇ w)
equation 2165 := x = ((y ◇ z) ◇ x) ◇ (y ◇ x)
equation 2166 := x = ((y ◇ z) ◇ x) ◇ (y ◇ y)
equation 2167 := x = ((y ◇ z) ◇ x) ◇ (y ◇ z)
equation 2168 := x = ((y ◇ z) ◇ x) ◇ (y ◇ w)
equation 2169 := x = ((y ◇ z) ◇ x) ◇ (z ◇ x)
equation 2170 := x = ((y ◇ z) ◇ x) ◇ (z ◇ y)
equation 2171 := x = ((y ◇ z) ◇ x) ◇ (z ◇ z)
equation 2172 := x = ((y ◇ z) ◇ x) ◇ (z ◇ w)
equation 2173 := x = ((y ◇ z) ◇ x) ◇ (w ◇ x)
equation 2174 := x = ((y ◇ z) ◇ x) ◇ (w ◇ y)
equation 2175 := x = ((y ◇ z) ◇ x) ◇ (w ◇ z)
equation 2176 := x = ((y ◇ z) ◇ x) ◇ (w ◇ w)
equation 2177 := x = ((y ◇ z) ◇ x) ◇ (w ◇ u)
equation 2178 := x = ((y ◇ z) ◇ y) ◇ (x ◇ x)
equation 2179 := x = ((y ◇ z) ◇ y) ◇ (x ◇ y)
equation 2180 := x = ((y ◇ z) ◇ y) ◇ (x ◇ z)
equation 2181 := x = ((y ◇ z) ◇ y) ◇ (x ◇ w)
equation 2182 := x = ((y ◇ z) ◇ y) ◇ (y ◇ x)
equation 2183 := x = ((y ◇ z) ◇ y) ◇ (y ◇ y)
equation 2184 := x = ((y ◇ z) ◇ y) ◇ (y ◇ z)
equation 2185 := x = ((y ◇ z) ◇ y) ◇ (y ◇ w)
equation 2186 := x = ((y ◇ z) ◇ y) ◇ (z ◇ x)
equation 2187 := x = ((y ◇ z) ◇ y) ◇ (z ◇ y)
equation 2188 := x = ((y ◇ z) ◇ y) ◇ (z ◇ z)
equation 2189 := x = ((y ◇ z) ◇ y) ◇ (z ◇ w)
equation 2190 := x = ((y ◇ z) ◇ y) ◇ (w ◇ x)
equation 2191 := x = ((y ◇ z) ◇ y) ◇ (w ◇ y)
equation 2192 := x = ((y ◇ z) ◇ y) ◇ (w ◇ z)
equation 2193 := x = ((y ◇ z) ◇ y) ◇ (w ◇ w)
equation 2194 := x = ((y ◇ z) ◇ y) ◇ (w ◇ u)
equation 2195 := x = ((y ◇ z) ◇ z) ◇ (x ◇ x)
equation 2196 := x = ((y ◇ z) ◇ z) ◇ (x ◇ y)
equation 2197 := x = ((y ◇ z) ◇ z) ◇ (x ◇ z)
equation 2198 := x = ((y ◇ z) ◇ z) ◇ (x ◇ w)
equation 2199 := x = ((y ◇ z) ◇ z) ◇ (y ◇ x)
equation 2200 := x = ((y ◇ z) ◇ z) ◇ (y ◇ y)
equation 2201 := x = ((y ◇ z) ◇ z) ◇ (y ◇ z)
equation 2202 := x = ((y ◇ z) ◇ z) ◇ (y ◇ w)
equation 2203 := x = ((y ◇ z) ◇ z) ◇ (z ◇ x)
equation 2204 := x = ((y ◇ z) ◇ z) ◇ (z ◇ y)
equation 2205 := x = ((y ◇ z) ◇ z) ◇ (z ◇ z)
equation 2206 := x = ((y ◇ z) ◇ z) ◇ (z ◇ w)
equation 2207 := x = ((y ◇ z) ◇ z) ◇ (w ◇ x)
equation 2208 := x = ((y ◇ z) ◇ z) ◇ (w ◇ y)
equation 2209 := x = ((y ◇ z) ◇ z) ◇ (w ◇ z)
equation 2210 := x = ((y ◇ z) ◇ z) ◇ (w ◇ w)
equation 2211 := x = ((y ◇ z) ◇ z) ◇ (w ◇ u)
equation 2212 := x = ((y ◇ z) ◇ w) ◇ (x ◇ x)
equation 2213 := x = ((y ◇ z) ◇ w) ◇ (x ◇ y)
equation 2214 := x = ((y ◇ z) ◇ w) ◇ (x ◇ z)
equation 2215 := x = ((y ◇ z) ◇ w) ◇ (x ◇ w)
equation 2216 := x = ((y ◇ z) ◇ w) ◇ (x ◇ u)
equation 2217 := x = ((y ◇ z) ◇ w) ◇ (y ◇ x)
equation 2218 := x = ((y ◇ z) ◇ w) ◇ (y ◇ y)
equation 2219 := x = ((y ◇ z) ◇ w) ◇ (y ◇ z)
equation 2220 := x = ((y ◇ z) ◇ w) ◇ (y ◇ w)
equation 2221 := x = ((y ◇ z) ◇ w) ◇ (y ◇ u)
equation 2222 := x = ((y ◇ z) ◇ w) ◇ (z ◇ x)
equation 2223 := x = ((y ◇ z) ◇ w) ◇ (z ◇ y)
equation 2224 := x = ((y ◇ z) ◇ w) ◇ (z ◇ z)
equation 2225 := x = ((y ◇ z) ◇ w) ◇ (z ◇ w)
equation 2226 := x = ((y ◇ z) ◇ w) ◇ (z ◇ u)
equation 2227 := x = ((y ◇ z) ◇ w) ◇ (w ◇ x)
equation 2228 := x = ((y ◇ z) ◇ w) ◇ (w ◇ y)
equation 2229 := x = ((y ◇ z) ◇ w) ◇ (w ◇ z)
equation 2230 := x = ((y ◇ z) ◇ w) ◇ (w ◇ w)
equation 2231 := x = ((y ◇ z) ◇ w) ◇ (w ◇ u)
equation 2232 := x = ((y ◇ z) ◇ w) ◇ (u ◇ x)
equation 2233 := x = ((y ◇ z) ◇ w) ◇ (u ◇ y)
equation 2234 := x = ((y ◇ z) ◇ w) ◇ (u ◇ z)
equation 2235 := x = ((y ◇ z) ◇ w) ◇ (u ◇ w)
equation 2236 := x = ((y ◇ z) ◇ w) ◇ (u ◇ u)
equation 2237 := x = ((y ◇ z) ◇ w) ◇ (u ◇ v)
equation 2238 := x = (x ◇ (x ◇ (x ◇ x))) ◇ x
equation 2239 := x = (x ◇ (x ◇ (x ◇ x))) ◇ y
equation 2240 := x = (x ◇ (x ◇ (x ◇ y))) ◇ x
equation 2241 := x = (x ◇ (x ◇ (x ◇ y))) ◇ y
equation 2242 := x = (x ◇ (x ◇ (x ◇ y))) ◇ z
equation 2243 := x = (x ◇ (x ◇ (y ◇ x))) ◇ x
equation 2244 := x = (x ◇ (x ◇ (y ◇ x))) ◇ y
equation 2245 := x = (x ◇ (x ◇ (y ◇ x))) ◇ z
equation 2246 := x = (x ◇ (x ◇ (y ◇ y))) ◇ x
equation 2247 := x = (x ◇ (x ◇ (y ◇ y))) ◇ y
equation 2248 := x = (x ◇ (x ◇ (y ◇ y))) ◇ z
equation 2249 := x = (x ◇ (x ◇ (y ◇ z))) ◇ x
equation 2250 := x = (x ◇ (x ◇ (y ◇ z))) ◇ y
equation 2251 := x = (x ◇ (x ◇ (y ◇ z))) ◇ z
equation 2252 := x = (x ◇ (x ◇ (y ◇ z))) ◇ w
equation 2253 := x = (x ◇ (y ◇ (x ◇ x))) ◇ x
equation 2254 := x = (x ◇ (y ◇ (x ◇ x))) ◇ y
equation 2255 := x = (x ◇ (y ◇ (x ◇ x))) ◇ z
equation 2256 := x = (x ◇ (y ◇ (x ◇ y))) ◇ x
equation 2257 := x = (x ◇ (y ◇ (x ◇ y))) ◇ y
equation 2258 := x = (x ◇ (y ◇ (x ◇ y))) ◇ z
equation 2259 := x = (x ◇ (y ◇ (x ◇ z))) ◇ x
equation 2260 := x = (x ◇ (y ◇ (x ◇ z))) ◇ y
equation 2261 := x = (x ◇ (y ◇ (x ◇ z))) ◇ z
equation 2262 := x = (x ◇ (y ◇ (x ◇ z))) ◇ w
equation 2263 := x = (x ◇ (y ◇ (y ◇ x))) ◇ x
equation 2264 := x = (x ◇ (y ◇ (y ◇ x))) ◇ y
equation 2265 := x = (x ◇ (y ◇ (y ◇ x))) ◇ z
equation 2266 := x = (x ◇ (y ◇ (y ◇ y))) ◇ x
equation 2267 := x = (x ◇ (y ◇ (y ◇ y))) ◇ y
equation 2268 := x = (x ◇ (y ◇ (y ◇ y))) ◇ z
equation 2269 := x = (x ◇ (y ◇ (y ◇ z))) ◇ x
equation 2270 := x = (x ◇ (y ◇ (y ◇ z))) ◇ y
equation 2271 := x = (x ◇ (y ◇ (y ◇ z))) ◇ z
equation 2272 := x = (x ◇ (y ◇ (y ◇ z))) ◇ w
equation 2273 := x = (x ◇ (y ◇ (z ◇ x))) ◇ x
equation 2274 := x = (x ◇ (y ◇ (z ◇ x))) ◇ y
equation 2275 := x = (x ◇ (y ◇ (z ◇ x))) ◇ z
equation 2276 := x = (x ◇ (y ◇ (z ◇ x))) ◇ w
equation 2277 := x = (x ◇ (y ◇ (z ◇ y))) ◇ x
equation 2278 := x = (x ◇ (y ◇ (z ◇ y))) ◇ y
equation 2279 := x = (x ◇ (y ◇ (z ◇ y))) ◇ z
equation 2280 := x = (x ◇ (y ◇ (z ◇ y))) ◇ w
equation 2281 := x = (x ◇ (y ◇ (z ◇ z))) ◇ x
equation 2282 := x = (x ◇ (y ◇ (z ◇ z))) ◇ y
equation 2283 := x = (x ◇ (y ◇ (z ◇ z))) ◇ z
equation 2284 := x = (x ◇ (y ◇ (z ◇ z))) ◇ w
equation 2285 := x = (x ◇ (y ◇ (z ◇ w))) ◇ x
equation 2286 := x = (x ◇ (y ◇ (z ◇ w))) ◇ y
equation 2287 := x = (x ◇ (y ◇ (z ◇ w))) ◇ z
equation 2288 := x = (x ◇ (y ◇ (z ◇ w))) ◇ w
equation 2289 := x = (x ◇ (y ◇ (z ◇ w))) ◇ u
equation 2290 := x = (y ◇ (x ◇ (x ◇ x))) ◇ x
equation 2291 := x = (y ◇ (x ◇ (x ◇ x))) ◇ y
equation 2292 := x = (y ◇ (x ◇ (x ◇ x))) ◇ z
equation 2293 := x = (y ◇ (x ◇ (x ◇ y))) ◇ x
equation 2294 := x = (y ◇ (x ◇ (x ◇ y))) ◇ y
equation 2295 := x = (y ◇ (x ◇ (x ◇ y))) ◇ z
equation 2296 := x = (y ◇ (x ◇ (x ◇ z))) ◇ x
equation 2297 := x = (y ◇ (x ◇ (x ◇ z))) ◇ y
equation 2298 := x = (y ◇ (x ◇ (x ◇ z))) ◇ z
equation 2299 := x = (y ◇ (x ◇ (x ◇ z))) ◇ w
equation 2300 := x = (y ◇ (x ◇ (y ◇ x))) ◇ x
equation 2301 := x = (y ◇ (x ◇ (y ◇ x))) ◇ y
equation 2302 := x = (y ◇ (x ◇ (y ◇ x))) ◇ z
equation 2303 := x = (y ◇ (x ◇ (y ◇ y))) ◇ x
equation 2304 := x = (y ◇ (x ◇ (y ◇ y))) ◇ y
equation 2305 := x = (y ◇ (x ◇ (y ◇ y))) ◇ z
equation 2306 := x = (y ◇ (x ◇ (y ◇ z))) ◇ x
equation 2307 := x = (y ◇ (x ◇ (y ◇ z))) ◇ y
equation 2308 := x = (y ◇ (x ◇ (y ◇ z))) ◇ z
equation 2309 := x = (y ◇ (x ◇ (y ◇ z))) ◇ w
equation 2310 := x = (y ◇ (x ◇ (z ◇ x))) ◇ x
equation 2311 := x = (y ◇ (x ◇ (z ◇ x))) ◇ y
equation 2312 := x = (y ◇ (x ◇ (z ◇ x))) ◇ z
equation 2313 := x = (y ◇ (x ◇ (z ◇ x))) ◇ w
equation 2314 := x = (y ◇ (x ◇ (z ◇ y))) ◇ x
equation 2315 := x = (y ◇ (x ◇ (z ◇ y))) ◇ y
equation 2316 := x = (y ◇ (x ◇ (z ◇ y))) ◇ z
equation 2317 := x = (y ◇ (x ◇ (z ◇ y))) ◇ w
equation 2318 := x = (y ◇ (x ◇ (z ◇ z))) ◇ x
equation 2319 := x = (y ◇ (x ◇ (z ◇ z))) ◇ y
equation 2320 := x = (y ◇ (x ◇ (z ◇ z))) ◇ z
equation 2321 := x = (y ◇ (x ◇ (z ◇ z))) ◇ w
equation 2322 := x = (y ◇ (x ◇ (z ◇ w))) ◇ x
equation 2323 := x = (y ◇ (x ◇ (z ◇ w))) ◇ y
equation 2324 := x = (y ◇ (x ◇ (z ◇ w))) ◇ z
equation 2325 := x = (y ◇ (x ◇ (z ◇ w))) ◇ w
equation 2326 := x = (y ◇ (x ◇ (z ◇ w))) ◇ u
equation 2327 := x = (y ◇ (y ◇ (x ◇ x))) ◇ x
equation 2328 := x = (y ◇ (y ◇ (x ◇ x))) ◇ y
equation 2329 := x = (y ◇ (y ◇ (x ◇ x))) ◇ z
equation 2330 := x = (y ◇ (y ◇ (x ◇ y))) ◇ x
equation 2331 := x = (y ◇ (y ◇ (x ◇ y))) ◇ y
equation 2332 := x = (y ◇ (y ◇ (x ◇ y))) ◇ z
equation 2333 := x = (y ◇ (y ◇ (x ◇ z))) ◇ x
equation 2334 := x = (y ◇ (y ◇ (x ◇ z))) ◇ y
equation 2335 := x = (y ◇ (y ◇ (x ◇ z))) ◇ z
equation 2336 := x = (y ◇ (y ◇ (x ◇ z))) ◇ w
equation 2337 := x = (y ◇ (y ◇ (y ◇ x))) ◇ x
equation 2338 := x = (y ◇ (y ◇ (y ◇ x))) ◇ y
equation 2339 := x = (y ◇ (y ◇ (y ◇ x))) ◇ z
equation 2340 := x = (y ◇ (y ◇ (y ◇ y))) ◇ x
equation 2341 := x = (y ◇ (y ◇ (y ◇ y))) ◇ y
equation 2342 := x = (y ◇ (y ◇ (y ◇ y))) ◇ z
equation 2343 := x = (y ◇ (y ◇ (y ◇ z))) ◇ x
equation 2344 := x = (y ◇ (y ◇ (y ◇ z))) ◇ y
equation 2345 := x = (y ◇ (y ◇ (y ◇ z))) ◇ z
equation 2346 := x = (y ◇ (y ◇ (y ◇ z))) ◇ w
equation 2347 := x = (y ◇ (y ◇ (z ◇ x))) ◇ x
equation 2348 := x = (y ◇ (y ◇ (z ◇ x))) ◇ y
equation 2349 := x = (y ◇ (y ◇ (z ◇ x))) ◇ z
equation 2350 := x = (y ◇ (y ◇ (z ◇ x))) ◇ w
equation 2351 := x = (y ◇ (y ◇ (z ◇ y))) ◇ x
equation 2352 := x = (y ◇ (y ◇ (z ◇ y))) ◇ y
equation 2353 := x = (y ◇ (y ◇ (z ◇ y))) ◇ z
equation 2354 := x = (y ◇ (y ◇ (z ◇ y))) ◇ w
equation 2355 := x = (y ◇ (y ◇ (z ◇ z))) ◇ x
equation 2356 := x = (y ◇ (y ◇ (z ◇ z))) ◇ y
equation 2357 := x = (y ◇ (y ◇ (z ◇ z))) ◇ z
equation 2358 := x = (y ◇ (y ◇ (z ◇ z))) ◇ w
equation 2359 := x = (y ◇ (y ◇ (z ◇ w))) ◇ x
equation 2360 := x = (y ◇ (y ◇ (z ◇ w))) ◇ y
equation 2361 := x = (y ◇ (y ◇ (z ◇ w))) ◇ z
equation 2362 := x = (y ◇ (y ◇ (z ◇ w))) ◇ w
equation 2363 := x = (y ◇ (y ◇ (z ◇ w))) ◇ u
equation 2364 := x = (y ◇ (z ◇ (x ◇ x))) ◇ x
equation 2365 := x = (y ◇ (z ◇ (x ◇ x))) ◇ y
equation 2366 := x = (y ◇ (z ◇ (x ◇ x))) ◇ z
equation 2367 := x = (y ◇ (z ◇ (x ◇ x))) ◇ w
equation 2368 := x = (y ◇ (z ◇ (x ◇ y))) ◇ x
equation 2369 := x = (y ◇ (z ◇ (x ◇ y))) ◇ y
equation 2370 := x = (y ◇ (z ◇ (x ◇ y))) ◇ z
equation 2371 := x = (y ◇ (z ◇ (x ◇ y))) ◇ w
equation 2372 := x = (y ◇ (z ◇ (x ◇ z))) ◇ x
equation 2373 := x = (y ◇ (z ◇ (x ◇ z))) ◇ y
equation 2374 := x = (y ◇ (z ◇ (x ◇ z))) ◇ z
equation 2375 := x = (y ◇ (z ◇ (x ◇ z))) ◇ w
equation 2376 := x = (y ◇ (z ◇ (x ◇ w))) ◇ x
equation 2377 := x = (y ◇ (z ◇ (x ◇ w))) ◇ y
equation 2378 := x = (y ◇ (z ◇ (x ◇ w))) ◇ z
equation 2379 := x = (y ◇ (z ◇ (x ◇ w))) ◇ w
equation 2380 := x = (y ◇ (z ◇ (x ◇ w))) ◇ u
equation 2381 := x = (y ◇ (z ◇ (y ◇ x))) ◇ x
equation 2382 := x = (y ◇ (z ◇ (y ◇ x))) ◇ y
equation 2383 := x = (y ◇ (z ◇ (y ◇ x))) ◇ z
equation 2384 := x = (y ◇ (z ◇ (y ◇ x))) ◇ w
equation 2385 := x = (y ◇ (z ◇ (y ◇ y))) ◇ x
equation 2386 := x = (y ◇ (z ◇ (y ◇ y))) ◇ y
equation 2387 := x = (y ◇ (z ◇ (y ◇ y))) ◇ z
equation 2388 := x = (y ◇ (z ◇ (y ◇ y))) ◇ w
equation 2389 := x = (y ◇ (z ◇ (y ◇ z))) ◇ x
equation 2390 := x = (y ◇ (z ◇ (y ◇ z))) ◇ y
equation 2391 := x = (y ◇ (z ◇ (y ◇ z))) ◇ z
equation 2392 := x = (y ◇ (z ◇ (y ◇ z))) ◇ w
equation 2393 := x = (y ◇ (z ◇ (y ◇ w))) ◇ x
equation 2394 := x = (y ◇ (z ◇ (y ◇ w))) ◇ y
equation 2395 := x = (y ◇ (z ◇ (y ◇ w))) ◇ z
equation 2396 := x = (y ◇ (z ◇ (y ◇ w))) ◇ w
equation 2397 := x = (y ◇ (z ◇ (y ◇ w))) ◇ u
equation 2398 := x = (y ◇ (z ◇ (z ◇ x))) ◇ x
equation 2399 := x = (y ◇ (z ◇ (z ◇ x))) ◇ y
equation 2400 := x = (y ◇ (z ◇ (z ◇ x))) ◇ z
equation 2401 := x = (y ◇ (z ◇ (z ◇ x))) ◇ w
equation 2402 := x = (y ◇ (z ◇ (z ◇ y))) ◇ x
equation 2403 := x = (y ◇ (z ◇ (z ◇ y))) ◇ y
equation 2404 := x = (y ◇ (z ◇ (z ◇ y))) ◇ z
equation 2405 := x = (y ◇ (z ◇ (z ◇ y))) ◇ w
equation 2406 := x = (y ◇ (z ◇ (z ◇ z))) ◇ x
equation 2407 := x = (y ◇ (z ◇ (z ◇ z))) ◇ y
equation 2408 := x = (y ◇ (z ◇ (z ◇ z))) ◇ z
equation 2409 := x = (y ◇ (z ◇ (z ◇ z))) ◇ w
equation 2410 := x = (y ◇ (z ◇ (z ◇ w))) ◇ x
equation 2411 := x = (y ◇ (z ◇ (z ◇ w))) ◇ y
equation 2412 := x = (y ◇ (z ◇ (z ◇ w))) ◇ z
equation 2413 := x = (y ◇ (z ◇ (z ◇ w))) ◇ w
equation 2414 := x = (y ◇ (z ◇ (z ◇ w))) ◇ u
equation 2415 := x = (y ◇ (z ◇ (w ◇ x))) ◇ x
equation 2416 := x = (y ◇ (z ◇ (w ◇ x))) ◇ y
equation 2417 := x = (y ◇ (z ◇ (w ◇ x))) ◇ z
equation 2418 := x = (y ◇ (z ◇ (w ◇ x))) ◇ w
equation 2419 := x = (y ◇ (z ◇ (w ◇ x))) ◇ u
equation 2420 := x = (y ◇ (z ◇ (w ◇ y))) ◇ x
equation 2421 := x = (y ◇ (z ◇ (w ◇ y))) ◇ y
equation 2422 := x = (y ◇ (z ◇ (w ◇ y))) ◇ z
equation 2423 := x = (y ◇ (z ◇ (w ◇ y))) ◇ w
equation 2424 := x = (y ◇ (z ◇ (w ◇ y))) ◇ u
equation 2425 := x = (y ◇ (z ◇ (w ◇ z))) ◇ x
equation 2426 := x = (y ◇ (z ◇ (w ◇ z))) ◇ y
equation 2427 := x = (y ◇ (z ◇ (w ◇ z))) ◇ z
equation 2428 := x = (y ◇ (z ◇ (w ◇ z))) ◇ w
equation 2429 := x = (y ◇ (z ◇ (w ◇ z))) ◇ u
equation 2430 := x = (y ◇ (z ◇ (w ◇ w))) ◇ x
equation 2431 := x = (y ◇ (z ◇ (w ◇ w))) ◇ y
equation 2432 := x = (y ◇ (z ◇ (w ◇ w))) ◇ z
equation 2433 := x = (y ◇ (z ◇ (w ◇ w))) ◇ w
equation 2434 := x = (y ◇ (z ◇ (w ◇ w))) ◇ u
equation 2435 := x = (y ◇ (z ◇ (w ◇ u))) ◇ x
equation 2436 := x = (y ◇ (z ◇ (w ◇ u))) ◇ y
equation 2437 := x = (y ◇ (z ◇ (w ◇ u))) ◇ z
equation 2438 := x = (y ◇ (z ◇ (w ◇ u))) ◇ w
equation 2439 := x = (y ◇ (z ◇ (w ◇ u))) ◇ u
equation 2440 := x = (y ◇ (z ◇ (w ◇ u))) ◇ v
equation 2441 := x = (x ◇ ((x ◇ x) ◇ x)) ◇ x
equation 2442 := x = (x ◇ ((x ◇ x) ◇ x)) ◇ y
equation 2443 := x = (x ◇ ((x ◇ x) ◇ y)) ◇ x
equation 2444 := x = (x ◇ ((x ◇ x) ◇ y)) ◇ y
equation 2445 := x = (x ◇ ((x ◇ x) ◇ y)) ◇ z
equation 2446 := x = (x ◇ ((x ◇ y) ◇ x)) ◇ x
equation 2447 := x = (x ◇ ((x ◇ y) ◇ x)) ◇ y
equation 2448 := x = (x ◇ ((x ◇ y) ◇ x)) ◇ z
equation 2449 := x = (x ◇ ((x ◇ y) ◇ y)) ◇ x
equation 2450 := x = (x ◇ ((x ◇ y) ◇ y)) ◇ y
equation 2451 := x = (x ◇ ((x ◇ y) ◇ y)) ◇ z
equation 2452 := x = (x ◇ ((x ◇ y) ◇ z)) ◇ x
equation 2453 := x = (x ◇ ((x ◇ y) ◇ z)) ◇ y
equation 2454 := x = (x ◇ ((x ◇ y) ◇ z)) ◇ z
equation 2455 := x = (x ◇ ((x ◇ y) ◇ z)) ◇ w
equation 2456 := x = (x ◇ ((y ◇ x) ◇ x)) ◇ x
equation 2457 := x = (x ◇ ((y ◇ x) ◇ x)) ◇ y
equation 2458 := x = (x ◇ ((y ◇ x) ◇ x)) ◇ z
equation 2459 := x = (x ◇ ((y ◇ x) ◇ y)) ◇ x
equation 2460 := x = (x ◇ ((y ◇ x) ◇ y)) ◇ y
equation 2461 := x = (x ◇ ((y ◇ x) ◇ y)) ◇ z
equation 2462 := x = (x ◇ ((y ◇ x) ◇ z)) ◇ x
equation 2463 := x = (x ◇ ((y ◇ x) ◇ z)) ◇ y
equation 2464 := x = (x ◇ ((y ◇ x) ◇ z)) ◇ z
equation 2465 := x = (x ◇ ((y ◇ x) ◇ z)) ◇ w
equation 2466 := x = (x ◇ ((y ◇ y) ◇ x)) ◇ x
equation 2467 := x = (x ◇ ((y ◇ y) ◇ x)) ◇ y
equation 2468 := x = (x ◇ ((y ◇ y) ◇ x)) ◇ z
equation 2469 := x = (x ◇ ((y ◇ y) ◇ y)) ◇ x
equation 2470 := x = (x ◇ ((y ◇ y) ◇ y)) ◇ y
equation 2471 := x = (x ◇ ((y ◇ y) ◇ y)) ◇ z
equation 2472 := x = (x ◇ ((y ◇ y) ◇ z)) ◇ x
equation 2473 := x = (x ◇ ((y ◇ y) ◇ z)) ◇ y
equation 2474 := x = (x ◇ ((y ◇ y) ◇ z)) ◇ z
equation 2475 := x = (x ◇ ((y ◇ y) ◇ z)) ◇ w
equation 2476 := x = (x ◇ ((y ◇ z) ◇ x)) ◇ x
equation 2477 := x = (x ◇ ((y ◇ z) ◇ x)) ◇ y
equation 2478 := x = (x ◇ ((y ◇ z) ◇ x)) ◇ z
equation 2479 := x = (x ◇ ((y ◇ z) ◇ x)) ◇ w
equation 2480 := x = (x ◇ ((y ◇ z) ◇ y)) ◇ x
equation 2481 := x = (x ◇ ((y ◇ z) ◇ y)) ◇ y
equation 2482 := x = (x ◇ ((y ◇ z) ◇ y)) ◇ z
equation 2483 := x = (x ◇ ((y ◇ z) ◇ y)) ◇ w
equation 2484 := x = (x ◇ ((y ◇ z) ◇ z)) ◇ x
equation 2485 := x = (x ◇ ((y ◇ z) ◇ z)) ◇ y
equation 2486 := x = (x ◇ ((y ◇ z) ◇ z)) ◇ z
equation 2487 := x = (x ◇ ((y ◇ z) ◇ z)) ◇ w
equation 2488 := x = (x ◇ ((y ◇ z) ◇ w)) ◇ x
equation 2489 := x = (x ◇ ((y ◇ z) ◇ w)) ◇ y
equation 2490 := x = (x ◇ ((y ◇ z) ◇ w)) ◇ z
equation 2491 := x = (x ◇ ((y ◇ z) ◇ w)) ◇ w
equation 2492 := x = (x ◇ ((y ◇ z) ◇ w)) ◇ u
equation 2493 := x = (y ◇ ((x ◇ x) ◇ x)) ◇ x
equation 2494 := x = (y ◇ ((x ◇ x) ◇ x)) ◇ y
equation 2495 := x = (y ◇ ((x ◇ x) ◇ x)) ◇ z
equation 2496 := x = (y ◇ ((x ◇ x) ◇ y)) ◇ x
equation 2497 := x = (y ◇ ((x ◇ x) ◇ y)) ◇ y
equation 2498 := x = (y ◇ ((x ◇ x) ◇ y)) ◇ z
equation 2499 := x = (y ◇ ((x ◇ x) ◇ z)) ◇ x
equation 2500 := x = (y ◇ ((x ◇ x) ◇ z)) ◇ y
equation 2501 := x = (y ◇ ((x ◇ x) ◇ z)) ◇ z
equation 2502 := x = (y ◇ ((x ◇ x) ◇ z)) ◇ w
equation 2503 := x = (y ◇ ((x ◇ y) ◇ x)) ◇ x
equation 2504 := x = (y ◇ ((x ◇ y) ◇ x)) ◇ y
equation 2505 := x = (y ◇ ((x ◇ y) ◇ x)) ◇ z
equation 2506 := x = (y ◇ ((x ◇ y) ◇ y)) ◇ x
equation 2507 := x = (y ◇ ((x ◇ y) ◇ y)) ◇ y
equation 2508 := x = (y ◇ ((x ◇ y) ◇ y)) ◇ z
equation 2509 := x = (y ◇ ((x ◇ y) ◇ z)) ◇ x
equation 2510 := x = (y ◇ ((x ◇ y) ◇ z)) ◇ y
equation 2511 := x = (y ◇ ((x ◇ y) ◇ z)) ◇ z
equation 2512 := x = (y ◇ ((x ◇ y) ◇ z)) ◇ w
equation 2513 := x = (y ◇ ((x ◇ z) ◇ x)) ◇ x
equation 2514 := x = (y ◇ ((x ◇ z) ◇ x)) ◇ y
equation 2515 := x = (y ◇ ((x ◇ z) ◇ x)) ◇ z
equation 2516 := x = (y ◇ ((x ◇ z) ◇ x)) ◇ w
equation 2517 := x = (y ◇ ((x ◇ z) ◇ y)) ◇ x
equation 2518 := x = (y ◇ ((x ◇ z) ◇ y)) ◇ y
equation 2519 := x = (y ◇ ((x ◇ z) ◇ y)) ◇ z
equation 2520 := x = (y ◇ ((x ◇ z) ◇ y)) ◇ w
equation 2521 := x = (y ◇ ((x ◇ z) ◇ z)) ◇ x
equation 2522 := x = (y ◇ ((x ◇ z) ◇ z)) ◇ y
equation 2523 := x = (y ◇ ((x ◇ z) ◇ z)) ◇ z
equation 2524 := x = (y ◇ ((x ◇ z) ◇ z)) ◇ w
equation 2525 := x = (y ◇ ((x ◇ z) ◇ w)) ◇ x
equation 2526 := x = (y ◇ ((x ◇ z) ◇ w)) ◇ y
equation 2527 := x = (y ◇ ((x ◇ z) ◇ w)) ◇ z
equation 2528 := x = (y ◇ ((x ◇ z) ◇ w)) ◇ w
equation 2529 := x = (y ◇ ((x ◇ z) ◇ w)) ◇ u
equation 2530 := x = (y ◇ ((y ◇ x) ◇ x)) ◇ x
equation 2531 := x = (y ◇ ((y ◇ x) ◇ x)) ◇ y
equation 2532 := x = (y ◇ ((y ◇ x) ◇ x)) ◇ z
equation 2533 := x = (y ◇ ((y ◇ x) ◇ y)) ◇ x
equation 2534 := x = (y ◇ ((y ◇ x) ◇ y)) ◇ y
equation 2535 := x = (y ◇ ((y ◇ x) ◇ y)) ◇ z
equation 2536 := x = (y ◇ ((y ◇ x) ◇ z)) ◇ x
equation 2537 := x = (y ◇ ((y ◇ x) ◇ z)) ◇ y
equation 2538 := x = (y ◇ ((y ◇ x) ◇ z)) ◇ z
equation 2539 := x = (y ◇ ((y ◇ x) ◇ z)) ◇ w
equation 2540 := x = (y ◇ ((y ◇ y) ◇ x)) ◇ x
equation 2541 := x = (y ◇ ((y ◇ y) ◇ x)) ◇ y
equation 2542 := x = (y ◇ ((y ◇ y) ◇ x)) ◇ z
equation 2543 := x = (y ◇ ((y ◇ y) ◇ y)) ◇ x
equation 2544 := x = (y ◇ ((y ◇ y) ◇ y)) ◇ y
equation 2545 := x = (y ◇ ((y ◇ y) ◇ y)) ◇ z
equation 2546 := x = (y ◇ ((y ◇ y) ◇ z)) ◇ x
equation 2547 := x = (y ◇ ((y ◇ y) ◇ z)) ◇ y
equation 2548 := x = (y ◇ ((y ◇ y) ◇ z)) ◇ z
equation 2549 := x = (y ◇ ((y ◇ y) ◇ z)) ◇ w
equation 2550 := x = (y ◇ ((y ◇ z) ◇ x)) ◇ x
equation 2551 := x = (y ◇ ((y ◇ z) ◇ x)) ◇ y
equation 2552 := x = (y ◇ ((y ◇ z) ◇ x)) ◇ z
equation 2553 := x = (y ◇ ((y ◇ z) ◇ x)) ◇ w
equation 2554 := x = (y ◇ ((y ◇ z) ◇ y)) ◇ x
equation 2555 := x = (y ◇ ((y ◇ z) ◇ y)) ◇ y
equation 2556 := x = (y ◇ ((y ◇ z) ◇ y)) ◇ z
equation 2557 := x = (y ◇ ((y ◇ z) ◇ y)) ◇ w
equation 2558 := x = (y ◇ ((y ◇ z) ◇ z)) ◇ x
equation 2559 := x = (y ◇ ((y ◇ z) ◇ z)) ◇ y
equation 2560 := x = (y ◇ ((y ◇ z) ◇ z)) ◇ z
equation 2561 := x = (y ◇ ((y ◇ z) ◇ z)) ◇ w
equation 2562 := x = (y ◇ ((y ◇ z) ◇ w)) ◇ x
equation 2563 := x = (y ◇ ((y ◇ z) ◇ w)) ◇ y
equation 2564 := x = (y ◇ ((y ◇ z) ◇ w)) ◇ z
equation 2565 := x = (y ◇ ((y ◇ z) ◇ w)) ◇ w
equation 2566 := x = (y ◇ ((y ◇ z) ◇ w)) ◇ u
equation 2567 := x = (y ◇ ((z ◇ x) ◇ x)) ◇ x
equation 2568 := x = (y ◇ ((z ◇ x) ◇ x)) ◇ y
equation 2569 := x = (y ◇ ((z ◇ x) ◇ x)) ◇ z
equation 2570 := x = (y ◇ ((z ◇ x) ◇ x)) ◇ w
equation 2571 := x = (y ◇ ((z ◇ x) ◇ y)) ◇ x
equation 2572 := x = (y ◇ ((z ◇ x) ◇ y)) ◇ y
equation 2573 := x = (y ◇ ((z ◇ x) ◇ y)) ◇ z
equation 2574 := x = (y ◇ ((z ◇ x) ◇ y)) ◇ w
equation 2575 := x = (y ◇ ((z ◇ x) ◇ z)) ◇ x
equation 2576 := x = (y ◇ ((z ◇ x) ◇ z)) ◇ y
equation 2577 := x = (y ◇ ((z ◇ x) ◇ z)) ◇ z
equation 2578 := x = (y ◇ ((z ◇ x) ◇ z)) ◇ w
equation 2579 := x = (y ◇ ((z ◇ x) ◇ w)) ◇ x
equation 2580 := x = (y ◇ ((z ◇ x) ◇ w)) ◇ y
equation 2581 := x = (y ◇ ((z ◇ x) ◇ w)) ◇ z
equation 2582 := x = (y ◇ ((z ◇ x) ◇ w)) ◇ w
equation 2583 := x = (y ◇ ((z ◇ x) ◇ w)) ◇ u
equation 2584 := x = (y ◇ ((z ◇ y) ◇ x)) ◇ x
equation 2585 := x = (y ◇ ((z ◇ y) ◇ x)) ◇ y
equation 2586 := x = (y ◇ ((z ◇ y) ◇ x)) ◇ z
equation 2587 := x = (y ◇ ((z ◇ y) ◇ x)) ◇ w
equation 2588 := x = (y ◇ ((z ◇ y) ◇ y)) ◇ x
equation 2589 := x = (y ◇ ((z ◇ y) ◇ y)) ◇ y
equation 2590 := x = (y ◇ ((z ◇ y) ◇ y)) ◇ z
equation 2591 := x = (y ◇ ((z ◇ y) ◇ y)) ◇ w
equation 2592 := x = (y ◇ ((z ◇ y) ◇ z)) ◇ x
equation 2593 := x = (y ◇ ((z ◇ y) ◇ z)) ◇ y
equation 2594 := x = (y ◇ ((z ◇ y) ◇ z)) ◇ z
equation 2595 := x = (y ◇ ((z ◇ y) ◇ z)) ◇ w
equation 2596 := x = (y ◇ ((z ◇ y) ◇ w)) ◇ x
equation 2597 := x = (y ◇ ((z ◇ y) ◇ w)) ◇ y
equation 2598 := x = (y ◇ ((z ◇ y) ◇ w)) ◇ z
equation 2599 := x = (y ◇ ((z ◇ y) ◇ w)) ◇ w
equation 2600 := x = (y ◇ ((z ◇ y) ◇ w)) ◇ u
equation 2601 := x = (y ◇ ((z ◇ z) ◇ x)) ◇ x
equation 2602 := x = (y ◇ ((z ◇ z) ◇ x)) ◇ y
equation 2603 := x = (y ◇ ((z ◇ z) ◇ x)) ◇ z
equation 2604 := x = (y ◇ ((z ◇ z) ◇ x)) ◇ w
equation 2605 := x = (y ◇ ((z ◇ z) ◇ y)) ◇ x
equation 2606 := x = (y ◇ ((z ◇ z) ◇ y)) ◇ y
equation 2607 := x = (y ◇ ((z ◇ z) ◇ y)) ◇ z
equation 2608 := x = (y ◇ ((z ◇ z) ◇ y)) ◇ w
equation 2609 := x = (y ◇ ((z ◇ z) ◇ z)) ◇ x
equation 2610 := x = (y ◇ ((z ◇ z) ◇ z)) ◇ y
equation 2611 := x = (y ◇ ((z ◇ z) ◇ z)) ◇ z
equation 2612 := x = (y ◇ ((z ◇ z) ◇ z)) ◇ w
equation 2613 := x = (y ◇ ((z ◇ z) ◇ w)) ◇ x
equation 2614 := x = (y ◇ ((z ◇ z) ◇ w)) ◇ y
equation 2615 := x = (y ◇ ((z ◇ z) ◇ w)) ◇ z
equation 2616 := x = (y ◇ ((z ◇ z) ◇ w)) ◇ w
equation 2617 := x = (y ◇ ((z ◇ z) ◇ w)) ◇ u
equation 2618 := x = (y ◇ ((z ◇ w) ◇ x)) ◇ x
equation 2619 := x = (y ◇ ((z ◇ w) ◇ x)) ◇ y
equation 2620 := x = (y ◇ ((z ◇ w) ◇ x)) ◇ z
equation 2621 := x = (y ◇ ((z ◇ w) ◇ x)) ◇ w
equation 2622 := x = (y ◇ ((z ◇ w) ◇ x)) ◇ u
equation 2623 := x = (y ◇ ((z ◇ w) ◇ y)) ◇ x
equation 2624 := x = (y ◇ ((z ◇ w) ◇ y)) ◇ y
equation 2625 := x = (y ◇ ((z ◇ w) ◇ y)) ◇ z
equation 2626 := x = (y ◇ ((z ◇ w) ◇ y)) ◇ w
equation 2627 := x = (y ◇ ((z ◇ w) ◇ y)) ◇ u
equation 2628 := x = (y ◇ ((z ◇ w) ◇ z)) ◇ x
equation 2629 := x = (y ◇ ((z ◇ w) ◇ z)) ◇ y
equation 2630 := x = (y ◇ ((z ◇ w) ◇ z)) ◇ z
equation 2631 := x = (y ◇ ((z ◇ w) ◇ z)) ◇ w
equation 2632 := x = (y ◇ ((z ◇ w) ◇ z)) ◇ u
equation 2633 := x = (y ◇ ((z ◇ w) ◇ w)) ◇ x
equation 2634 := x = (y ◇ ((z ◇ w) ◇ w)) ◇ y
equation 2635 := x = (y ◇ ((z ◇ w) ◇ w)) ◇ z
equation 2636 := x = (y ◇ ((z ◇ w) ◇ w)) ◇ w
equation 2637 := x = (y ◇ ((z ◇ w) ◇ w)) ◇ u
equation 2638 := x = (y ◇ ((z ◇ w) ◇ u)) ◇ x
equation 2639 := x = (y ◇ ((z ◇ w) ◇ u)) ◇ y
equation 2640 := x = (y ◇ ((z ◇ w) ◇ u)) ◇ z
equation 2641 := x = (y ◇ ((z ◇ w) ◇ u)) ◇ w
equation 2642 := x = (y ◇ ((z ◇ w) ◇ u)) ◇ u
equation 2643 := x = (y ◇ ((z ◇ w) ◇ u)) ◇ v
equation 2644 := x = ((x ◇ x) ◇ (x ◇ x)) ◇ x
equation 2645 := x = ((x ◇ x) ◇ (x ◇ x)) ◇ y
equation 2646 := x = ((x ◇ x) ◇ (x ◇ y)) ◇ x
equation 2647 := x = ((x ◇ x) ◇ (x ◇ y)) ◇ y
equation 2648 := x = ((x ◇ x) ◇ (x ◇ y)) ◇ z
equation 2649 := x = ((x ◇ x) ◇ (y ◇ x)) ◇ x
equation 2650 := x = ((x ◇ x) ◇ (y ◇ x)) ◇ y
equation 2651 := x = ((x ◇ x) ◇ (y ◇ x)) ◇ z
equation 2652 := x = ((x ◇ x) ◇ (y ◇ y)) ◇ x
equation 2653 := x = ((x ◇ x) ◇ (y ◇ y)) ◇ y
equation 2654 := x = ((x ◇ x) ◇ (y ◇ y)) ◇ z
equation 2655 := x = ((x ◇ x) ◇ (y ◇ z)) ◇ x
equation 2656 := x = ((x ◇ x) ◇ (y ◇ z)) ◇ y
equation 2657 := x = ((x ◇ x) ◇ (y ◇ z)) ◇ z
equation 2658 := x = ((x ◇ x) ◇ (y ◇ z)) ◇ w
equation 2659 := x = ((x ◇ y) ◇ (x ◇ x)) ◇ x
equation 2660 := x = ((x ◇ y) ◇ (x ◇ x)) ◇ y
equation 2661 := x = ((x ◇ y) ◇ (x ◇ x)) ◇ z
-- equation 2662 := x = ((x ◇ y) ◇ (x ◇ y)) ◇ x
equation 2663 := x = ((x ◇ y) ◇ (x ◇ y)) ◇ y
equation 2664 := x = ((x ◇ y) ◇ (x ◇ y)) ◇ z
equation 2665 := x = ((x ◇ y) ◇ (x ◇ z)) ◇ x
equation 2666 := x = ((x ◇ y) ◇ (x ◇ z)) ◇ y
equation 2667 := x = ((x ◇ y) ◇ (x ◇ z)) ◇ z
equation 2668 := x = ((x ◇ y) ◇ (x ◇ z)) ◇ w
equation 2669 := x = ((x ◇ y) ◇ (y ◇ x)) ◇ x
equation 2670 := x = ((x ◇ y) ◇ (y ◇ x)) ◇ y
equation 2671 := x = ((x ◇ y) ◇ (y ◇ x)) ◇ z
equation 2672 := x = ((x ◇ y) ◇ (y ◇ y)) ◇ x
equation 2673 := x = ((x ◇ y) ◇ (y ◇ y)) ◇ y
equation 2674 := x = ((x ◇ y) ◇ (y ◇ y)) ◇ z
equation 2675 := x = ((x ◇ y) ◇ (y ◇ z)) ◇ x
equation 2676 := x = ((x ◇ y) ◇ (y ◇ z)) ◇ y
equation 2677 := x = ((x ◇ y) ◇ (y ◇ z)) ◇ z
equation 2678 := x = ((x ◇ y) ◇ (y ◇ z)) ◇ w
equation 2679 := x = ((x ◇ y) ◇ (z ◇ x)) ◇ x
equation 2680 := x = ((x ◇ y) ◇ (z ◇ x)) ◇ y
equation 2681 := x = ((x ◇ y) ◇ (z ◇ x)) ◇ z
equation 2682 := x = ((x ◇ y) ◇ (z ◇ x)) ◇ w
equation 2683 := x = ((x ◇ y) ◇ (z ◇ y)) ◇ x
equation 2684 := x = ((x ◇ y) ◇ (z ◇ y)) ◇ y
equation 2685 := x = ((x ◇ y) ◇ (z ◇ y)) ◇ z
equation 2686 := x = ((x ◇ y) ◇ (z ◇ y)) ◇ w
equation 2687 := x = ((x ◇ y) ◇ (z ◇ z)) ◇ x
equation 2688 := x = ((x ◇ y) ◇ (z ◇ z)) ◇ y
equation 2689 := x = ((x ◇ y) ◇ (z ◇ z)) ◇ z
equation 2690 := x = ((x ◇ y) ◇ (z ◇ z)) ◇ w
equation 2691 := x = ((x ◇ y) ◇ (z ◇ w)) ◇ x
equation 2692 := x = ((x ◇ y) ◇ (z ◇ w)) ◇ y
equation 2693 := x = ((x ◇ y) ◇ (z ◇ w)) ◇ z
equation 2694 := x = ((x ◇ y) ◇ (z ◇ w)) ◇ w
equation 2695 := x = ((x ◇ y) ◇ (z ◇ w)) ◇ u
equation 2696 := x = ((y ◇ x) ◇ (x ◇ x)) ◇ x
equation 2697 := x = ((y ◇ x) ◇ (x ◇ x)) ◇ y
equation 2698 := x = ((y ◇ x) ◇ (x ◇ x)) ◇ z
equation 2699 := x = ((y ◇ x) ◇ (x ◇ y)) ◇ x
equation 2700 := x = ((y ◇ x) ◇ (x ◇ y)) ◇ y
equation 2701 := x = ((y ◇ x) ◇ (x ◇ y)) ◇ z
equation 2702 := x = ((y ◇ x) ◇ (x ◇ z)) ◇ x
equation 2703 := x = ((y ◇ x) ◇ (x ◇ z)) ◇ y
equation 2704 := x = ((y ◇ x) ◇ (x ◇ z)) ◇ z
equation 2705 := x = ((y ◇ x) ◇ (x ◇ z)) ◇ w
equation 2706 := x = ((y ◇ x) ◇ (y ◇ x)) ◇ x
equation 2707 := x = ((y ◇ x) ◇ (y ◇ x)) ◇ y
equation 2708 := x = ((y ◇ x) ◇ (y ◇ x)) ◇ z
equation 2709 := x = ((y ◇ x) ◇ (y ◇ y)) ◇ x
equation 2710 := x = ((y ◇ x) ◇ (y ◇ y)) ◇ y
equation 2711 := x = ((y ◇ x) ◇ (y ◇ y)) ◇ z
equation 2712 := x = ((y ◇ x) ◇ (y ◇ z)) ◇ x
equation 2713 := x = ((y ◇ x) ◇ (y ◇ z)) ◇ y
equation 2714 := x = ((y ◇ x) ◇ (y ◇ z)) ◇ z
equation 2715 := x = ((y ◇ x) ◇ (y ◇ z)) ◇ w
equation 2716 := x = ((y ◇ x) ◇ (z ◇ x)) ◇ x
equation 2717 := x = ((y ◇ x) ◇ (z ◇ x)) ◇ y
equation 2718 := x = ((y ◇ x) ◇ (z ◇ x)) ◇ z
equation 2719 := x = ((y ◇ x) ◇ (z ◇ x)) ◇ w
equation 2720 := x = ((y ◇ x) ◇ (z ◇ y)) ◇ x
equation 2721 := x = ((y ◇ x) ◇ (z ◇ y)) ◇ y
equation 2722 := x = ((y ◇ x) ◇ (z ◇ y)) ◇ z
equation 2723 := x = ((y ◇ x) ◇ (z ◇ y)) ◇ w
equation 2724 := x = ((y ◇ x) ◇ (z ◇ z)) ◇ x
equation 2725 := x = ((y ◇ x) ◇ (z ◇ z)) ◇ y
equation 2726 := x = ((y ◇ x) ◇ (z ◇ z)) ◇ z
equation 2727 := x = ((y ◇ x) ◇ (z ◇ z)) ◇ w
equation 2728 := x = ((y ◇ x) ◇ (z ◇ w)) ◇ x
equation 2729 := x = ((y ◇ x) ◇ (z ◇ w)) ◇ y
equation 2730 := x = ((y ◇ x) ◇ (z ◇ w)) ◇ z
equation 2731 := x = ((y ◇ x) ◇ (z ◇ w)) ◇ w
equation 2732 := x = ((y ◇ x) ◇ (z ◇ w)) ◇ u
equation 2733 := x = ((y ◇ y) ◇ (x ◇ x)) ◇ x
equation 2734 := x = ((y ◇ y) ◇ (x ◇ x)) ◇ y
equation 2735 := x = ((y ◇ y) ◇ (x ◇ x)) ◇ z
equation 2736 := x = ((y ◇ y) ◇ (x ◇ y)) ◇ x
equation 2737 := x = ((y ◇ y) ◇ (x ◇ y)) ◇ y
equation 2738 := x = ((y ◇ y) ◇ (x ◇ y)) ◇ z
equation 2739 := x = ((y ◇ y) ◇ (x ◇ z)) ◇ x
equation 2740 := x = ((y ◇ y) ◇ (x ◇ z)) ◇ y
equation 2741 := x = ((y ◇ y) ◇ (x ◇ z)) ◇ z
equation 2742 := x = ((y ◇ y) ◇ (x ◇ z)) ◇ w
equation 2743 := x = ((y ◇ y) ◇ (y ◇ x)) ◇ x
equation 2744 := x = ((y ◇ y) ◇ (y ◇ x)) ◇ y
equation 2745 := x = ((y ◇ y) ◇ (y ◇ x)) ◇ z
equation 2746 := x = ((y ◇ y) ◇ (y ◇ y)) ◇ x
equation 2747 := x = ((y ◇ y) ◇ (y ◇ y)) ◇ y
equation 2748 := x = ((y ◇ y) ◇ (y ◇ y)) ◇ z
equation 2749 := x = ((y ◇ y) ◇ (y ◇ z)) ◇ x
equation 2750 := x = ((y ◇ y) ◇ (y ◇ z)) ◇ y
equation 2751 := x = ((y ◇ y) ◇ (y ◇ z)) ◇ z
equation 2752 := x = ((y ◇ y) ◇ (y ◇ z)) ◇ w
equation 2753 := x = ((y ◇ y) ◇ (z ◇ x)) ◇ x
equation 2754 := x = ((y ◇ y) ◇ (z ◇ x)) ◇ y
equation 2755 := x = ((y ◇ y) ◇ (z ◇ x)) ◇ z
equation 2756 := x = ((y ◇ y) ◇ (z ◇ x)) ◇ w
equation 2757 := x = ((y ◇ y) ◇ (z ◇ y)) ◇ x
equation 2758 := x = ((y ◇ y) ◇ (z ◇ y)) ◇ y
equation 2759 := x = ((y ◇ y) ◇ (z ◇ y)) ◇ z
equation 2760 := x = ((y ◇ y) ◇ (z ◇ y)) ◇ w
equation 2761 := x = ((y ◇ y) ◇ (z ◇ z)) ◇ x
equation 2762 := x = ((y ◇ y) ◇ (z ◇ z)) ◇ y
equation 2763 := x = ((y ◇ y) ◇ (z ◇ z)) ◇ z
equation 2764 := x = ((y ◇ y) ◇ (z ◇ z)) ◇ w
equation 2765 := x = ((y ◇ y) ◇ (z ◇ w)) ◇ x
equation 2766 := x = ((y ◇ y) ◇ (z ◇ w)) ◇ y
equation 2767 := x = ((y ◇ y) ◇ (z ◇ w)) ◇ z
equation 2768 := x = ((y ◇ y) ◇ (z ◇ w)) ◇ w
equation 2769 := x = ((y ◇ y) ◇ (z ◇ w)) ◇ u
equation 2770 := x = ((y ◇ z) ◇ (x ◇ x)) ◇ x
equation 2771 := x = ((y ◇ z) ◇ (x ◇ x)) ◇ y
equation 2772 := x = ((y ◇ z) ◇ (x ◇ x)) ◇ z
equation 2773 := x = ((y ◇ z) ◇ (x ◇ x)) ◇ w
equation 2774 := x = ((y ◇ z) ◇ (x ◇ y)) ◇ x
equation 2775 := x = ((y ◇ z) ◇ (x ◇ y)) ◇ y
equation 2776 := x = ((y ◇ z) ◇ (x ◇ y)) ◇ z
equation 2777 := x = ((y ◇ z) ◇ (x ◇ y)) ◇ w
equation 2778 := x = ((y ◇ z) ◇ (x ◇ z)) ◇ x
equation 2779 := x = ((y ◇ z) ◇ (x ◇ z)) ◇ y
equation 2780 := x = ((y ◇ z) ◇ (x ◇ z)) ◇ z
equation 2781 := x = ((y ◇ z) ◇ (x ◇ z)) ◇ w
equation 2782 := x = ((y ◇ z) ◇ (x ◇ w)) ◇ x
equation 2783 := x = ((y ◇ z) ◇ (x ◇ w)) ◇ y
equation 2784 := x = ((y ◇ z) ◇ (x ◇ w)) ◇ z
equation 2785 := x = ((y ◇ z) ◇ (x ◇ w)) ◇ w
equation 2786 := x = ((y ◇ z) ◇ (x ◇ w)) ◇ u
equation 2787 := x = ((y ◇ z) ◇ (y ◇ x)) ◇ x
equation 2788 := x = ((y ◇ z) ◇ (y ◇ x)) ◇ y
equation 2789 := x = ((y ◇ z) ◇ (y ◇ x)) ◇ z
equation 2790 := x = ((y ◇ z) ◇ (y ◇ x)) ◇ w
equation 2791 := x = ((y ◇ z) ◇ (y ◇ y)) ◇ x
equation 2792 := x = ((y ◇ z) ◇ (y ◇ y)) ◇ y
equation 2793 := x = ((y ◇ z) ◇ (y ◇ y)) ◇ z
equation 2794 := x = ((y ◇ z) ◇ (y ◇ y)) ◇ w
equation 2795 := x = ((y ◇ z) ◇ (y ◇ z)) ◇ x
equation 2796 := x = ((y ◇ z) ◇ (y ◇ z)) ◇ y
equation 2797 := x = ((y ◇ z) ◇ (y ◇ z)) ◇ z
equation 2798 := x = ((y ◇ z) ◇ (y ◇ z)) ◇ w
equation 2799 := x = ((y ◇ z) ◇ (y ◇ w)) ◇ x
equation 2800 := x = ((y ◇ z) ◇ (y ◇ w)) ◇ y
equation 2801 := x = ((y ◇ z) ◇ (y ◇ w)) ◇ z
equation 2802 := x = ((y ◇ z) ◇ (y ◇ w)) ◇ w
equation 2803 := x = ((y ◇ z) ◇ (y ◇ w)) ◇ u
equation 2804 := x = ((y ◇ z) ◇ (z ◇ x)) ◇ x
equation 2805 := x = ((y ◇ z) ◇ (z ◇ x)) ◇ y
equation 2806 := x = ((y ◇ z) ◇ (z ◇ x)) ◇ z
equation 2807 := x = ((y ◇ z) ◇ (z ◇ x)) ◇ w
equation 2808 := x = ((y ◇ z) ◇ (z ◇ y)) ◇ x
equation 2809 := x = ((y ◇ z) ◇ (z ◇ y)) ◇ y
equation 2810 := x = ((y ◇ z) ◇ (z ◇ y)) ◇ z
equation 2811 := x = ((y ◇ z) ◇ (z ◇ y)) ◇ w
equation 2812 := x = ((y ◇ z) ◇ (z ◇ z)) ◇ x
equation 2813 := x = ((y ◇ z) ◇ (z ◇ z)) ◇ y
equation 2814 := x = ((y ◇ z) ◇ (z ◇ z)) ◇ z
equation 2815 := x = ((y ◇ z) ◇ (z ◇ z)) ◇ w
equation 2816 := x = ((y ◇ z) ◇ (z ◇ w)) ◇ x
equation 2817 := x = ((y ◇ z) ◇ (z ◇ w)) ◇ y
equation 2818 := x = ((y ◇ z) ◇ (z ◇ w)) ◇ z
equation 2819 := x = ((y ◇ z) ◇ (z ◇ w)) ◇ w
equation 2820 := x = ((y ◇ z) ◇ (z ◇ w)) ◇ u
equation 2821 := x = ((y ◇ z) ◇ (w ◇ x)) ◇ x
equation 2822 := x = ((y ◇ z) ◇ (w ◇ x)) ◇ y
equation 2823 := x = ((y ◇ z) ◇ (w ◇ x)) ◇ z
equation 2824 := x = ((y ◇ z) ◇ (w ◇ x)) ◇ w
equation 2825 := x = ((y ◇ z) ◇ (w ◇ x)) ◇ u
equation 2826 := x = ((y ◇ z) ◇ (w ◇ y)) ◇ x
equation 2827 := x = ((y ◇ z) ◇ (w ◇ y)) ◇ y
equation 2828 := x = ((y ◇ z) ◇ (w ◇ y)) ◇ z
equation 2829 := x = ((y ◇ z) ◇ (w ◇ y)) ◇ w
equation 2830 := x = ((y ◇ z) ◇ (w ◇ y)) ◇ u
equation 2831 := x = ((y ◇ z) ◇ (w ◇ z)) ◇ x
equation 2832 := x = ((y ◇ z) ◇ (w ◇ z)) ◇ y
equation 2833 := x = ((y ◇ z) ◇ (w ◇ z)) ◇ z
equation 2834 := x = ((y ◇ z) ◇ (w ◇ z)) ◇ w
equation 2835 := x = ((y ◇ z) ◇ (w ◇ z)) ◇ u
equation 2836 := x = ((y ◇ z) ◇ (w ◇ w)) ◇ x
equation 2837 := x = ((y ◇ z) ◇ (w ◇ w)) ◇ y
equation 2838 := x = ((y ◇ z) ◇ (w ◇ w)) ◇ z
equation 2839 := x = ((y ◇ z) ◇ (w ◇ w)) ◇ w
equation 2840 := x = ((y ◇ z) ◇ (w ◇ w)) ◇ u
equation 2841 := x = ((y ◇ z) ◇ (w ◇ u)) ◇ x
equation 2842 := x = ((y ◇ z) ◇ (w ◇ u)) ◇ y
equation 2843 := x = ((y ◇ z) ◇ (w ◇ u)) ◇ z
equation 2844 := x = ((y ◇ z) ◇ (w ◇ u)) ◇ w
equation 2845 := x = ((y ◇ z) ◇ (w ◇ u)) ◇ u
equation 2846 := x = ((y ◇ z) ◇ (w ◇ u)) ◇ v
equation 2847 := x = ((x ◇ (x ◇ x)) ◇ x) ◇ x
equation 2848 := x = ((x ◇ (x ◇ x)) ◇ x) ◇ y
equation 2849 := x = ((x ◇ (x ◇ x)) ◇ y) ◇ x
equation 2850 := x = ((x ◇ (x ◇ x)) ◇ y) ◇ y
equation 2851 := x = ((x ◇ (x ◇ x)) ◇ y) ◇ z
equation 2852 := x = ((x ◇ (x ◇ y)) ◇ x) ◇ x
equation 2853 := x = ((x ◇ (x ◇ y)) ◇ x) ◇ y
equation 2854 := x = ((x ◇ (x ◇ y)) ◇ x) ◇ z
equation 2855 := x = ((x ◇ (x ◇ y)) ◇ y) ◇ x
equation 2856 := x = ((x ◇ (x ◇ y)) ◇ y) ◇ y
equation 2857 := x = ((x ◇ (x ◇ y)) ◇ y) ◇ z
equation 2858 := x = ((x ◇ (x ◇ y)) ◇ z) ◇ x
equation 2859 := x = ((x ◇ (x ◇ y)) ◇ z) ◇ y
equation 2860 := x = ((x ◇ (x ◇ y)) ◇ z) ◇ z
equation 2861 := x = ((x ◇ (x ◇ y)) ◇ z) ◇ w
equation 2862 := x = ((x ◇ (y ◇ x)) ◇ x) ◇ x
equation 2863 := x = ((x ◇ (y ◇ x)) ◇ x) ◇ y
equation 2864 := x = ((x ◇ (y ◇ x)) ◇ x) ◇ z
equation 2865 := x = ((x ◇ (y ◇ x)) ◇ y) ◇ x
equation 2866 := x = ((x ◇ (y ◇ x)) ◇ y) ◇ y
equation 2867 := x = ((x ◇ (y ◇ x)) ◇ y) ◇ z
equation 2868 := x = ((x ◇ (y ◇ x)) ◇ z) ◇ x
equation 2869 := x = ((x ◇ (y ◇ x)) ◇ z) ◇ y
equation 2870 := x = ((x ◇ (y ◇ x)) ◇ z) ◇ z
equation 2871 := x = ((x ◇ (y ◇ x)) ◇ z) ◇ w
equation 2872 := x = ((x ◇ (y ◇ y)) ◇ x) ◇ x
equation 2873 := x = ((x ◇ (y ◇ y)) ◇ x) ◇ y
equation 2874 := x = ((x ◇ (y ◇ y)) ◇ x) ◇ z
equation 2875 := x = ((x ◇ (y ◇ y)) ◇ y) ◇ x
equation 2876 := x = ((x ◇ (y ◇ y)) ◇ y) ◇ y
equation 2877 := x = ((x ◇ (y ◇ y)) ◇ y) ◇ z
equation 2878 := x = ((x ◇ (y ◇ y)) ◇ z) ◇ x
equation 2879 := x = ((x ◇ (y ◇ y)) ◇ z) ◇ y
equation 2880 := x = ((x ◇ (y ◇ y)) ◇ z) ◇ z
equation 2881 := x = ((x ◇ (y ◇ y)) ◇ z) ◇ w
equation 2882 := x = ((x ◇ (y ◇ z)) ◇ x) ◇ x
equation 2883 := x = ((x ◇ (y ◇ z)) ◇ x) ◇ y
equation 2884 := x = ((x ◇ (y ◇ z)) ◇ x) ◇ z
equation 2885 := x = ((x ◇ (y ◇ z)) ◇ x) ◇ w
equation 2886 := x = ((x ◇ (y ◇ z)) ◇ y) ◇ x
equation 2887 := x = ((x ◇ (y ◇ z)) ◇ y) ◇ y
equation 2888 := x = ((x ◇ (y ◇ z)) ◇ y) ◇ z
equation 2889 := x = ((x ◇ (y ◇ z)) ◇ y) ◇ w
equation 2890 := x = ((x ◇ (y ◇ z)) ◇ z) ◇ x
equation 2891 := x = ((x ◇ (y ◇ z)) ◇ z) ◇ y
equation 2892 := x = ((x ◇ (y ◇ z)) ◇ z) ◇ z
equation 2893 := x = ((x ◇ (y ◇ z)) ◇ z) ◇ w
equation 2894 := x = ((x ◇ (y ◇ z)) ◇ w) ◇ x
equation 2895 := x = ((x ◇ (y ◇ z)) ◇ w) ◇ y
equation 2896 := x = ((x ◇ (y ◇ z)) ◇ w) ◇ z
equation 2897 := x = ((x ◇ (y ◇ z)) ◇ w) ◇ w
equation 2898 := x = ((x ◇ (y ◇ z)) ◇ w) ◇ u
equation 2899 := x = ((y ◇ (x ◇ x)) ◇ x) ◇ x
equation 2900 := x = ((y ◇ (x ◇ x)) ◇ x) ◇ y
equation 2901 := x = ((y ◇ (x ◇ x)) ◇ x) ◇ z
equation 2902 := x = ((y ◇ (x ◇ x)) ◇ y) ◇ x
equation 2903 := x = ((y ◇ (x ◇ x)) ◇ y) ◇ y
equation 2904 := x = ((y ◇ (x ◇ x)) ◇ y) ◇ z
equation 2905 := x = ((y ◇ (x ◇ x)) ◇ z) ◇ x
equation 2906 := x = ((y ◇ (x ◇ x)) ◇ z) ◇ y
equation 2907 := x = ((y ◇ (x ◇ x)) ◇ z) ◇ z
equation 2908 := x = ((y ◇ (x ◇ x)) ◇ z) ◇ w
equation 2909 := x = ((y ◇ (x ◇ y)) ◇ x) ◇ x
equation 2910 := x = ((y ◇ (x ◇ y)) ◇ x) ◇ y
equation 2911 := x = ((y ◇ (x ◇ y)) ◇ x) ◇ z
equation 2912 := x = ((y ◇ (x ◇ y)) ◇ y) ◇ x
equation 2913 := x = ((y ◇ (x ◇ y)) ◇ y) ◇ y
equation 2914 := x = ((y ◇ (x ◇ y)) ◇ y) ◇ z
equation 2915 := x = ((y ◇ (x ◇ y)) ◇ z) ◇ x
equation 2916 := x = ((y ◇ (x ◇ y)) ◇ z) ◇ y
equation 2917 := x = ((y ◇ (x ◇ y)) ◇ z) ◇ z
equation 2918 := x = ((y ◇ (x ◇ y)) ◇ z) ◇ w
equation 2919 := x = ((y ◇ (x ◇ z)) ◇ x) ◇ x
equation 2920 := x = ((y ◇ (x ◇ z)) ◇ x) ◇ y
equation 2921 := x = ((y ◇ (x ◇ z)) ◇ x) ◇ z
equation 2922 := x = ((y ◇ (x ◇ z)) ◇ x) ◇ w
equation 2923 := x = ((y ◇ (x ◇ z)) ◇ y) ◇ x
equation 2924 := x = ((y ◇ (x ◇ z)) ◇ y) ◇ y
equation 2925 := x = ((y ◇ (x ◇ z)) ◇ y) ◇ z
equation 2926 := x = ((y ◇ (x ◇ z)) ◇ y) ◇ w
equation 2927 := x = ((y ◇ (x ◇ z)) ◇ z) ◇ x
equation 2928 := x = ((y ◇ (x ◇ z)) ◇ z) ◇ y
equation 2929 := x = ((y ◇ (x ◇ z)) ◇ z) ◇ z
equation 2930 := x = ((y ◇ (x ◇ z)) ◇ z) ◇ w
equation 2931 := x = ((y ◇ (x ◇ z)) ◇ w) ◇ x
equation 2932 := x = ((y ◇ (x ◇ z)) ◇ w) ◇ y
equation 2933 := x = ((y ◇ (x ◇ z)) ◇ w) ◇ z
equation 2934 := x = ((y ◇ (x ◇ z)) ◇ w) ◇ w
equation 2935 := x = ((y ◇ (x ◇ z)) ◇ w) ◇ u
equation 2936 := x = ((y ◇ (y ◇ x)) ◇ x) ◇ x
equation 2937 := x = ((y ◇ (y ◇ x)) ◇ x) ◇ y
equation 2938 := x = ((y ◇ (y ◇ x)) ◇ x) ◇ z
equation 2939 := x = ((y ◇ (y ◇ x)) ◇ y) ◇ x
equation 2940 := x = ((y ◇ (y ◇ x)) ◇ y) ◇ y
equation 2941 := x = ((y ◇ (y ◇ x)) ◇ y) ◇ z
equation 2942 := x = ((y ◇ (y ◇ x)) ◇ z) ◇ x
equation 2943 := x = ((y ◇ (y ◇ x)) ◇ z) ◇ y
equation 2944 := x = ((y ◇ (y ◇ x)) ◇ z) ◇ z
equation 2945 := x = ((y ◇ (y ◇ x)) ◇ z) ◇ w
equation 2946 := x = ((y ◇ (y ◇ y)) ◇ x) ◇ x
equation 2947 := x = ((y ◇ (y ◇ y)) ◇ x) ◇ y
equation 2948 := x = ((y ◇ (y ◇ y)) ◇ x) ◇ z
equation 2949 := x = ((y ◇ (y ◇ y)) ◇ y) ◇ x
equation 2950 := x = ((y ◇ (y ◇ y)) ◇ y) ◇ y
equation 2951 := x = ((y ◇ (y ◇ y)) ◇ y) ◇ z
equation 2952 := x = ((y ◇ (y ◇ y)) ◇ z) ◇ x
equation 2953 := x = ((y ◇ (y ◇ y)) ◇ z) ◇ y
equation 2954 := x = ((y ◇ (y ◇ y)) ◇ z) ◇ z
equation 2955 := x = ((y ◇ (y ◇ y)) ◇ z) ◇ w
equation 2956 := x = ((y ◇ (y ◇ z)) ◇ x) ◇ x
equation 2957 := x = ((y ◇ (y ◇ z)) ◇ x) ◇ y
equation 2958 := x = ((y ◇ (y ◇ z)) ◇ x) ◇ z
equation 2959 := x = ((y ◇ (y ◇ z)) ◇ x) ◇ w
equation 2960 := x = ((y ◇ (y ◇ z)) ◇ y) ◇ x
equation 2961 := x = ((y ◇ (y ◇ z)) ◇ y) ◇ y
equation 2962 := x = ((y ◇ (y ◇ z)) ◇ y) ◇ z
equation 2963 := x = ((y ◇ (y ◇ z)) ◇ y) ◇ w
equation 2964 := x = ((y ◇ (y ◇ z)) ◇ z) ◇ x
equation 2965 := x = ((y ◇ (y ◇ z)) ◇ z) ◇ y
equation 2966 := x = ((y ◇ (y ◇ z)) ◇ z) ◇ z
equation 2967 := x = ((y ◇ (y ◇ z)) ◇ z) ◇ w
equation 2968 := x = ((y ◇ (y ◇ z)) ◇ w) ◇ x
equation 2969 := x = ((y ◇ (y ◇ z)) ◇ w) ◇ y
equation 2970 := x = ((y ◇ (y ◇ z)) ◇ w) ◇ z
equation 2971 := x = ((y ◇ (y ◇ z)) ◇ w) ◇ w
equation 2972 := x = ((y ◇ (y ◇ z)) ◇ w) ◇ u
equation 2973 := x = ((y ◇ (z ◇ x)) ◇ x) ◇ x
equation 2974 := x = ((y ◇ (z ◇ x)) ◇ x) ◇ y
equation 2975 := x = ((y ◇ (z ◇ x)) ◇ x) ◇ z
equation 2976 := x = ((y ◇ (z ◇ x)) ◇ x) ◇ w
equation 2977 := x = ((y ◇ (z ◇ x)) ◇ y) ◇ x
equation 2978 := x = ((y ◇ (z ◇ x)) ◇ y) ◇ y
equation 2979 := x = ((y ◇ (z ◇ x)) ◇ y) ◇ z
equation 2980 := x = ((y ◇ (z ◇ x)) ◇ y) ◇ w
equation 2981 := x = ((y ◇ (z ◇ x)) ◇ z) ◇ x
equation 2982 := x = ((y ◇ (z ◇ x)) ◇ z) ◇ y
equation 2983 := x = ((y ◇ (z ◇ x)) ◇ z) ◇ z
equation 2984 := x = ((y ◇ (z ◇ x)) ◇ z) ◇ w
equation 2985 := x = ((y ◇ (z ◇ x)) ◇ w) ◇ x
equation 2986 := x = ((y ◇ (z ◇ x)) ◇ w) ◇ y
equation 2987 := x = ((y ◇ (z ◇ x)) ◇ w) ◇ z
equation 2988 := x = ((y ◇ (z ◇ x)) ◇ w) ◇ w
equation 2989 := x = ((y ◇ (z ◇ x)) ◇ w) ◇ u
equation 2990 := x = ((y ◇ (z ◇ y)) ◇ x) ◇ x
equation 2991 := x = ((y ◇ (z ◇ y)) ◇ x) ◇ y
equation 2992 := x = ((y ◇ (z ◇ y)) ◇ x) ◇ z
equation 2993 := x = ((y ◇ (z ◇ y)) ◇ x) ◇ w
equation 2994 := x = ((y ◇ (z ◇ y)) ◇ y) ◇ x
equation 2995 := x = ((y ◇ (z ◇ y)) ◇ y) ◇ y
equation 2996 := x = ((y ◇ (z ◇ y)) ◇ y) ◇ z
equation 2997 := x = ((y ◇ (z ◇ y)) ◇ y) ◇ w
equation 2998 := x = ((y ◇ (z ◇ y)) ◇ z) ◇ x
equation 2999 := x = ((y ◇ (z ◇ y)) ◇ z) ◇ y
