generated_triples = [
["x = y * (y * ((x * y) * x))", "x * y = ((z * x) * w) * y", False],
["x * (y * z) = (z * w) * w", "x * (y * x) = (x * y) * z", False],
["x = ((y * y) * z) * x", "x = x * (((y * x) * x) * x)", True],
["(x * y) * x = (x * z) * w", "x * (y * y) = x * (z * y)", False],
["x = ((y * z) * (z * x)) * y", "x * x = (y * (y * y)) * y", False],
["x * x = (x * y) * z", "x * x = (y * z) * w", False],
["x = (y * (y * (y * z))) * x", "x * y = z * (w * (w * y))", True],
["x = x * (y * ((y * z) * y))", "x = x * ((x * (x * x)) * x)", False],
["x = ((x * x) * (y * z)) * y", "x = ((x * (y * x)) * x) * y", False],
["(x * x) * y = (y * y) * z", "x * (y * y) = x * (z * z)", False],
["x = (x * (y * z)) * (w * y)", "x = (y * (z * w)) * (u * z)", False],
["(x * y) * x = (z * w) * u", "x * (x * x) = x * (y * y)", False],
["x * y = ((z * y) * x) * x", "x * y = y * (y * (y * y))", True],
["x = (y * x) * (x * (x * z))", "x = y * (z * (z * (x * y)))", False],
["x * x = x * (y * (z * y))", "x * (x * x) = x * (y * x)", False],
["x = (x * y) * (x * (y * z))", "x = (x * y) * (x * (z * y))", False],
["x = y * (((x * y) * x) * y)", "x = ((x * (y * z)) * z) * y", False],
["x = ((y * x) * y) * (z * z)", "x = x * (((x * y) * x) * y)", True],
["x * y = (x * (y * x)) * z", "x * y = (x * (x * z)) * x", False],
["x * (y * z) = (x * x) * z", "x * (y * z) = (y * y) * x", False],
["x = y * ((y * x) * (x * y))", "x = (y * (x * y)) * x", False],
["x * y = (y * (y * x)) * x", "x * y = (x * y) * (x * y)", False],
["x = (x * y) * (z * z)", "x * x = x * ((y * z) * w)", True],
["x = y * (y * ((x * y) * x))", "x = x * ((y * z) * (z * x))", False],
["x = ((y * (z * z)) * x) * y", "x = y * ((y * (z * x)) * z)", False],
["x = ((x * (y * z)) * z) * x", "x * x = x * (y * (y * x))", False],
["x = x * (y * (x * z))", "x = ((x * y) * (z * w)) * u", True],
["x * y = z * ((x * x) * y)", "x * (x * y) = (y * x) * y", False],
["x = (y * y) * ((z * x) * x)", "x * y = (y * (z * x)) * y", False],
["x = (y * (x * (y * x))) * y", "x * (x * y) = z * (y * x)", False],
["x = ((y * x) * x) * (x * z)", "x = y * ((x * z) * (z * w))", False],
["x = ((y * x) * x) * (x * z)", "x * y = (z * z) * z", False],
["x = ((y * (z * y)) * y) * x", "x = (y * ((z * w) * y)) * x", False],
["x * y = (y * x) * z", "x * y = z * ((w * y) * y)", True],
["x = x * ((y * z) * (w * u))", "x = (x * (x * (y * x))) * x", True],
["x * x = y * (z * (x * z))", "x * x = x * (y * (z * x))", False],
["x = y * (((y * z) * y) * x)", "x = x * (x * (y * (y * x)))", False],
["x * y = (x * (x * y)) * z", "x * y = x * (z * (y * y))", False],
["x = x * ((x * y) * (z * z))", "x = x * (((x * y) * x) * y)", False],
["x = x * ((y * (z * w)) * w)", "x * y = (x * (z * w)) * u", True],
["x = (((y * x) * y) * z) * x", "x * y = z * (w * (z * y))", True],
["x = (y * x) * (x * z)", "x = x * (y * (x * (y * z)))", False],
["x * x = y * (x * (z * w))", "x * x = y * ((x * x) * z)", False],
["x = (y * (y * z)) * x", "x = (((x * y) * x) * x) * x", True],
["x = (y * x) * (x * (x * z))", "x = (x * (y * z)) * (w * w)", False],
["x * y = y * ((x * y) * z)", "x * x = y * (y * (y * y))", True],
["x = (y * x) * (x * (z * z))", "x = y * ((y * x) * (z * y))", False],
["x = (y * (z * y)) * x", "x = (((y * z) * y) * y) * x", False],
["x * (y * z) = (z * x) * y", "x * (y * z) = (w * u) * y", False],
["x = x * (((y * z) * w) * u)", "x = ((x * x) * (x * y)) * y", True],
["x * y = ((x * z) * w) * y", "x * y = ((z * w) * x) * y", False],
["x = (y * x) * (y * x)", "x = ((x * y) * x) * (z * x)", True],
["x * y = (x * z) * (y * w)", "x * y = (x * y) * (z * x)", False],
["x * y = ((z * w) * x) * u", "x * (y * y) = (x * x) * x", True],
["x = y * (((z * w) * x) * x)", "x = y * (((z * x) * w) * w)", False],
["x = (y * (y * z)) * (w * x)", "x = y * (z * (w * (u * x)))", True],
["x = y * ((z * y) * (y * x))", "x = y * (x * ((z * w) * x))", False],
["x * (y * z) = (w * w) * z", "x * (y * x) = (x * z) * x", False],
["x = ((y * z) * z) * x", "x = x * ((y * (y * x)) * x)", True],
["x = (((y * z) * x) * z) * x", "x = y * (((x * y) * y) * x)", True],
["x = x * (y * (z * (x * y)))", "x = x * (((y * x) * z) * w)", True],
["x = ((y * x) * z) * (z * y)", "x = (y * (y * (x * x))) * x", False],
["x = ((y * z) * w) * x", "x = y * ((z * (w * u)) * x)", True],
["x = x * ((y * z) * (z * z))", "x = (x * ((y * y) * x)) * x", True],
["x = x * (y * (z * y))", "x = (x * (x * (x * y))) * x", True],
["x = ((y * z) * y) * (x * z)", "x = (((y * x) * y) * y) * y", False],
["x = (y * (y * x)) * (z * x)", "x * y = z * (y * (w * y))", True],
["x * x = y * ((x * z) * y)", "x * (y * x) = x * (z * x)", False],
["x = ((y * y) * z) * x", "x = y * (y * (z * (w * x)))", True],
["x = ((y * x) * y) * (z * z)", "x = x * (((x * y) * x) * y)", True],
["x * y = (x * (y * x)) * z", "x * y = (x * (x * z)) * x", False],
["x * (y * z) = (x * x) * z", "x * (y * z) = (y * y) * x", False],
["x = y * ((y * x) * (x * y))", "x = (y * (x * y)) * x", False],
["x * y = (y * (y * x)) * x", "x * y = (x * y) * (x * y)", False],
["x = (x * y) * (z * z)", "x * x = x * ((y * z) * w)", True],
["x = y * (y * ((x * y) * x))", "x = x * ((y * z) * (z * x))", False],
["x = ((y * (z * z)) * x) * y", "x = y * ((y * (z * x)) * z)", False],
["x = ((x * (y * z)) * z) * x", "x * x = x * (y * (y * x))", False],
["x = x * (y * (x * z))", "x = ((x * y) * (z * w)) * u", True],
["x * y = z * ((x * x) * y)", "x * (x * y) = (y * x) * y", False],
["x = (y * y) * ((z * x) * x)", "x * y = (y * (z * x)) * y", False],
["x = (y * (x * (y * x))) * y", "x * (x * y) = z * (y * x)", False],
["x = ((y * x) * x) * (x * z)", "x = y * ((x * z) * (z * w))", False],
["x = ((y * x) * x) * (x * z)", "x * y = (z * z) * z", False],
["x = ((y * (z * y)) * y) * x", "x = (y * ((z * w) * y)) * x", False],
["x * y = (y * x) * z", "x * y = z * ((w * y) * y)", True],
["x = x * ((y * z) * (w * u))", "x = (x * (x * (y * x))) * x", True],
["x * x = y * (z * (x * z))", "x * x = x * (y * (z * x))", False],
["x = y * (((y * z) * y) * x)", "x = x * (x * (y * (y * x)))", False],
["x * y = (x * (x * y)) * z", "x * y = x * (z * (y * y))", False],
["x = x * ((x * y) * (z * z))", "x = x * (((x * y) * x) * y)", False],
["x = x * ((y * (z * w)) * w)", "x * y = (x * (z * w)) * u", True],
["x = (((y * x) * y) * z) * x", "x * y = z * (w * (z * y))", True],
["x = (y * x) * (x * z)", "x = x * (y * (x * (y * z)))", False],
["x * x = y * (x * (z * w))", "x * x = y * ((x * x) * z)", False],
["x = (y * (y * z)) * x", "x = (((x * y) * x) * x) * x", True],
["x = (y * x) * (x * (x * z))", "x = (x * (y * z)) * (w * w)", False],
["x * y = y * ((x * y) * z)", "x * x = y * (y * (y * y))", True],
["x = (y * x) * (x * (z * z))", "x = y * ((y * x) * (z * y))", False],
["x = (y * (z * y)) * x", "x = (((y * z) * y) * y) * x", False],
["x * (y * z) = (z * x) * y", "x * (y * z) = (w * u) * y", False],
["x = x * (((y * z) * w) * u)", "x = ((x * x) * (x * y)) * y", True],
["x * y = ((x * z) * w) * y", "x * y = ((z * w) * x) * y", False],
["x = (y * x) * (y * x)", "x = ((x * y) * x) * (z * x)", True],
["x * y = (x * z) * (y * w)", "x * y = (x * y) * (z * x)", False],
["x * y = ((z * w) * x) * u", "x * (y * y) = (x * x) * x", True],
["x = y * (((z * w) * x) * x)", "x = y * (((z * x) * w) * w)", False],
["x = (y * (y * z)) * (w * x)", "x = y * (z * (w * (u * x)))", True],
["x = y * ((z * y) * (y * x))", "x = y * (x * ((z * w) * x))", False],
["x * (y * z) = (w * w) * z", "x * (y * x) = (x * z) * x", False],
["x = ((y * z) * z) * x", "x = x * ((y * (y * x)) * x)", True],
["x = (((y * z) * x) * z) * x", "x = y * (((x * y) * y) * x)", True],
["x = x * (y * (z * (x * y)))", "x = x * (((y * x) * z) * w)", True],
["x = ((y * x) * z) * (z * y)", "x = (y * (y * (x * x))) * x", False],
["x = ((y * z) * w) * x", "x = y * ((z * (w * u)) * x)", True],
["x = x * ((y * z) * (z * z))", "x = (x * ((y * y) * x)) * x", True],
["x = x * (y * (z * y))", "x = (x * (x * (x * y))) * x", True],
["x = ((y * z) * y) * (x * z)", "x = (((y * x) * y) * y) * y", False],
["x = (y * (y * x)) * (z * x)", "x * y = z * (y * (w * y))", True],
["x * x = y * ((x * z) * y)", "x * (y * x) = x * (z * x)", False],
["x = ((y * y) * z) * x", "x = y * (y * (z * (w * x)))", True],
["x = ((y * x) * y) * (z * z)", "x = x * (((x * y) * x) * y)", True],
["x * y = (x * (y * x)) * z", "x * y = (x * (x * z)) * x", False],
["x * (y * z) = (x * x) * z", "x * (y * z) = (y * y) * x", False],
["x = y * ((y * x) * (x * y))", "x = (y * (x * y)) * x", False],
["x * y = (y * (y * x)) * x", "x * y = (x * y) * (x * y)", False],
["x = (x * y) * (z * z)", "x * x = x * ((y * z) * w)", True],
["x = y * (y * ((x * y) * x))", "x = x * ((y * z) * (z * x))", False],
["x = ((y * (z * z)) * x) * y", "x = y * ((y * (z * x)) * z)", False],
["x = ((x * (y * z)) * z) * x", "x * x = x * (y * (y * x))", False],
["x = x * (y * (x * z))", "x = ((x * y) * (z * w)) * u", True],
["x * y = z * ((x * x) * y)", "x * (x * y) = (y * x) * y", False],
["x = (y * y) * ((z * x) * x)", "x * y = (y * (z * x)) * y", False],
["x = (y * (x * (y * x))) * y", "x * (x * y) = z * (y * x)", False],
["x = ((y * x) * x) * (x * z)", "x = y * ((x * z) * (z * w))", False],
["x = ((y * x) * x) * (x * z)", "x * y = (z * z) * z", False],
["x = ((y * (z * y)) * y) * x", "x = (y * ((z * w) * y)) * x", False],
["x * y = (y * x) * z", "x * y = z * ((w * y) * y)", True],
["x = x * ((y * z) * (w * u))", "x = (x * (x * (y * x))) * x", True],
["x * x = y * (z * (x * z))", "x * x = x * (y * (z * x))", False],
["x = y * (((y * z) * y) * x)", "x = x * (x * (y * (y * x)))", False],
["x * y = (x * (x * y)) * z", "x * y = x * (z * (y * y))", False],
["x = x * ((x * y) * (z * z))", "x = x * (((x * y) * x) * y)", False],
["x = x * ((y * (z * w)) * w)", "x * y = (x * (z * w)) * u", True],
["x = (((y * x) * y) * z) * x", "x * y = z * (w * (z * y))", True],
["x = (y * x) * (x * z)", "x = x * (y * (x * (y * z)))", False],
["x * x = y * (x * (z * w))", "x * x = y * ((x * x) * z)", False],
["x = (y * (y * z)) * x", "x = (((x * y) * x) * x) * x", True],
["x = (y * x) * (x * (x * z))", "x = (x * (y * z)) * (w * w)", False],
["x * y = y * ((x * y) * z)", "x * x = y * (y * (y * y))", True],
["x = (y * x) * (x * (z * z))", "x = y * ((y * x) * (z * y))", False],
["x = (y * (z * y)) * x", "x = (((y * z) * y) * y) * x", False],
["x * (y * z) = (z * x) * y", "x * (y * z) = (w * u) * y", False],
["x = x * (((y * z) * w) * u)", "x = ((x * x) * (x * y)) * y", True],
["x * y = ((x * z) * w) * y", "x * y = ((z * w) * x) * y", False],
["x = (y * x) * (y * x)", "x = ((x * y) * x) * (z * x)", True],
["x * y = (x * z) * (y * w)", "x * y = (x * y) * (z * x)", False],
["x * y = ((z * w) * x) * u", "x * (y * y) = (x * x) * x", True],
["x = y * (((z * w) * x) * x)", "x = y * (((z * x) * w) * w)", False],
["x = (y * (y * z)) * (w * x)", "x = y * (z * (w * (u * x)))", True],
["x = y * ((z * y) * (y * x))", "x = y * (x * ((z * w) * x))", False],
["x * (y * z) = (w * w) * z", "x * (y * x) = (x * z) * x", False],
["x = ((y * z) * z) * x", "x = x * ((y * (y * x)) * x)", True],
["x = (((y * z) * x) * z) * x", "x = y * (((x * y) * y) * x)", True],
["x = x * (y * (z * (x * y)))", "x = x * (((y * x) * z) * w)", True],
["x = ((y * x) * z) * (z * y)", "x = (y * (y * (x * x))) * x", False],
["x = ((y * z) * w) * x", "x = y * ((z * (w * u)) * x)", True],
["x = x * ((y * z) * (z * z))", "x = (x * ((y * y) * x)) * x", True],
["x = x * (y * (z * y))", "x = (x * (x * (x * y))) * x", True],
["x = ((y * z) * y) * (x * z)", "x = (((y * x) * y) * y) * y", False],
["x = (y * (y * x)) * (z * x)", "x * y = z * (y * (w * y))", True],
["x * x = y * ((x * z) * y)", "x * (y * x) = x * (z * x)", False],
["x = ((y * y) * z) * x", "x = y * (y * (z * (w * x)))", True],
["x = ((y * x) * y) * (z * z)", "x = x * (((x * y) * x) * y)", True],
["x * y = (x * (y * x)) * z", "x * y = (x * (x * z)) * x", False],
["x * (y * z) = (x * x) * z", "x * (y * z) = (y * y) * x", False],
["x = y * ((y * x) * (x * y))", "x = (y * (x * y)) * x", False],
["x * y = (y * (y * x)) * x", "x * y = (x * y) * (x * y)", False],
["x = (x * y) * (z * z)", "x * x = x * ((y * z) * w)", True],
["x = y * (y * ((x * y) * x))", "x = x * ((y * z) * (z * x))", False],
["x = ((y * (z * z)) * x) * y", "x = y * ((y * (z * x)) * z)", False],
["x = ((x * (y * z)) * z) * x", "x * x = x * (y * (y * x))", False],
["x = x * (y * (x * z))", "x = ((x * y) * (z * w)) * u", True],
["x * y = z * ((x * x) * y)", "x * (x * y) = (y * x) * y", False],
["x = (y * y) * ((z * x) * x)", "x * y = (y * (z * x)) * y", False],
["x = (y * (x * (y * x))) * y", "x * (x * y) = z * (y * x)", False],
["x = ((y * x) * x) * (x * z)", "x = y * ((x * z) * (z * w))", False],
["x = ((y * x) * x) * (x * z)", "x * y = (z * z) * z", False],
["x = ((y * (z * y)) * y) * x", "x = (y * ((z * w) * y)) * x", False],
["x * y = (y * x) * z", "x * y = z * ((w * y) * y)", True],
["x = x * ((y * z) * (w * u))", "x = (x * (x * (y * x))) * x", True],
["x * x = y * (z * (x * z))", "x * x = x * (y * (z * x))", False],
["x = y * (((y * z) * y) * x)", "x = x * (x * (y * (y * x)))", False],
["x * y = (x * (x * y)) * z", "x * y = x * (z * (y * y))", False],
["x = x * ((x * y) * (z * z))", "x = x * (((x * y) * x) * y)", False],
["x = x * ((y * (z * w)) * w)", "x * y = (x * (z * w)) * u", True],
["x = (((y * x) * y) * z) * x", "x * y = z * (w * (z * y))", True],
["x = (y * x) * (x * z)", "x = x * (y * (x * (y * z)))", False],
["x * x = y * (x * (z * w))", "x * x = y * ((x * x) * z)", False],
["x = (y * (y * z)) * x", "x = (((x * y) * x) * x) * x", True]]