generated_triples = [
    ['x = y * ((z * (w * w)) * w)', 'x = ((y * (z * y)) * w) * y', True],
    ['x = ((y * z) * x) * (w * u)', 'x = ((y * z) * w) * (u * y)', True],
    ['x = (x * x) * x', 'x * (x * y) = z * (z * y)', False],
    ['x = y * ((z * (w * u)) * w)', 'x * y = (x * x) * (y * y)', True],
    ['x = ((y * z) * w) * (u * y)', 'x = y * ((x * x) * x)', True],
    ['x * (y * z) = w * (z * y)', 'x = (y * x) * (y * (z * w))', False],
    ['x = y * ((z * w) * (w * x))', 'x = (y * z) * ((w * w) * y)', False],
    ['x = ((y * z) * (x * w)) * x', 'x = (y * y) * (z * (z * y))', False],
    ['x = y * ((y * z) * (z * z))', 'x = (y * (z * z)) * y', True],
    ['x = y * ((y * (x * y)) * z)', 'x = y * (x * ((z * x) * w))', True],
    ['x = ((y * z) * y) * (w * x)', 'x = ((x * x) * x) * x', False],
    ['x = y * (((z * z) * w) * z)', 'x = (y * y) * ((x * x) * x)', True],
    ['x = (y * ((z * x) * w)) * u', 'x = ((y * (x * y)) * x) * z', True],
    ['x * y = ((z * w) * u) * u', 'x = (x * x) * (y * (z * y))', False],
    ['x * (y * x) = z * (w * u)', 'x = (x * y) * ((z * w) * y)', False],
    ['x * (y * y) = (y * z) * y', 'x = (y * (z * w)) * (z * u)', False],
    ['x = ((y * z) * w) * (y * y)', 'x * y = ((y * z) * w) * u', True],
    ['x * (y * x) = (x * x) * y', 'x * (x * y) = x * (y * z)', False],
    ['x = y * ((x * (y * z)) * w)', 'x = y * (z * z)', True],
    ['x = (y * (z * (x * z))) * y', 'x = ((y * z) * w) * (u * x)', False],
]