name: Intentions
on:
  issue_comment:
    types: [created]
jobs:
  intentions:
    permissions:
      issues: write
      pull-requests: write
    uses: leanprover-community/intentions/.github/workflows/intentions.yml@v1
    with:
      project-title: "Equational Theories Project"
      default-ttl: "none"
      status-unclaimed: "Unclaimed Outstanding Tasks"
      status-claimed: "Claimed Tasks"
      terminal-statuses: "PRs in Review,Completed"
    secrets:
      project-token: ${{ secrets.PAT_TOKEN }}
